[project]
name = "econometrics_thesis_jonathan_rietveld"
dynamic = ["version"]
readme = "README.md"
license = { file = "LICENSE" }

dependencies = [
    "pandas",
    "numpy",
    "matplotlib",
    "scipy",

    "pyreadstat",

    "semopy",
]

[tool.ruff]
line-length = 120
