```{r Dependencies}
if (!requireNamespace("lavaan")) {
    install.packages("lavaan")
}
if (!requireNamespace("arrow")) {
    install.packages("arrow")
}
if (!requireNamespace("rsample")) {
    install.packages("rsample")
}

library(lavaan)
library(arrow)
library(rsample)
```

```{r Load data}
all_data <- read_feather("/tmp/panel_data.feather")
head(all_data)

options(max.print = 2500)
```

```{r Potentially adjust y scale to make variances similar}
mask <- grepl("mhi5", colnames(all_data), fixed = TRUE)

# all_data[mask] <- lapply(all_data[mask], function(column) column / 100)

head(all_data)
```

```{r Define base model}
sem_model <- "
# Regressions (structural part)
mhi5_13 ~ alpha_mhi5_13*1 + rho1*mhi5_12 + rho2*mhi5_11 + rho3*mhi5_10 + beta0_cs104*cs104_13 + beta1_cs104*cs104_12 + delta_leeftijd.18.24*leeftijd_first.18.24 + delta_leeftijd.25.39*leeftijd_first.25.39 + delta_leeftijd.40.66*leeftijd_first.40.66 + delta_leeftijd.over.67*leeftijd_first.over.67 + delta_nettohh_f.under.15k*nettohh_f_first.under.15k + delta_nettohh_f.over.50k*nettohh_f_first.over.50k + delta_herkomstgroep.first.w*herkomstgroep_first.first.w + delta_herkomstgroep.first.nonw*herkomstgroep_first.first.nonw + delta_herkomstgroep.second.w*herkomstgroep_first.second.w + delta_herkomstgroep.second.nonw*herkomstgroep_first.second.nonw + delta_geslacht.male*geslacht_first.male + delta_burgstat.married*burgstat_first.married + delta_burgstat.never.been.married*burgstat_first.never.been.married + delta_burgstat.separated*burgstat_first.separated + delta_burgstat.widow.or.widower*burgstat_first.widow.or.widower + delta_oplcat.hbo*oplcat_first.hbo + delta_oplcat.mbo*oplcat_first.mbo + delta_oplcat.primary.school*oplcat_first.primary.school + delta_oplcat.vmbo*oplcat_first.vmbo + delta_oplcat.wo*oplcat_first.wo + delta_employment.homemaker*employment_first.homemaker + delta_employment.retired*employment_first.retired + delta_employment.student*employment_first.student + delta_employment.unable.to.work*employment_first.unable.to.work + delta_employment.unemployed*employment_first.unemployed
mhi5_18 ~ alpha_mhi5_18*1 + rho1*mhi5_17 + rho2*mhi5_16 + rho3*mhi5_15 + beta0_cs104*cs104_18 + beta1_cs104*cs104_17 + delta_leeftijd.18.24*leeftijd_first.18.24 + delta_leeftijd.25.39*leeftijd_first.25.39 + delta_leeftijd.40.66*leeftijd_first.40.66 + delta_leeftijd.over.67*leeftijd_first.over.67 + delta_nettohh_f.under.15k*nettohh_f_first.under.15k + delta_nettohh_f.over.50k*nettohh_f_first.over.50k + delta_herkomstgroep.first.w*herkomstgroep_first.first.w + delta_herkomstgroep.first.nonw*herkomstgroep_first.first.nonw + delta_herkomstgroep.second.w*herkomstgroep_first.second.w + delta_herkomstgroep.second.nonw*herkomstgroep_first.second.nonw + delta_geslacht.male*geslacht_first.male + delta_burgstat.married*burgstat_first.married + delta_burgstat.never.been.married*burgstat_first.never.been.married + delta_burgstat.separated*burgstat_first.separated + delta_burgstat.widow.or.widower*burgstat_first.widow.or.widower + delta_oplcat.hbo*oplcat_first.hbo + delta_oplcat.mbo*oplcat_first.mbo + delta_oplcat.primary.school*oplcat_first.primary.school + delta_oplcat.vmbo*oplcat_first.vmbo + delta_oplcat.wo*oplcat_first.wo + delta_employment.homemaker*employment_first.homemaker + delta_employment.retired*employment_first.retired + delta_employment.student*employment_first.student + delta_employment.unable.to.work*employment_first.unable.to.work + delta_employment.unemployed*employment_first.unemployed
mhi5_19 ~ alpha_mhi5_19*1 + rho1*mhi5_18 + rho2*mhi5_17 + rho3*mhi5_16 + beta0_cs104*cs104_19 + beta1_cs104*cs104_18 + delta_leeftijd.18.24*leeftijd_first.18.24 + delta_leeftijd.25.39*leeftijd_first.25.39 + delta_leeftijd.40.66*leeftijd_first.40.66 + delta_leeftijd.over.67*leeftijd_first.over.67 + delta_nettohh_f.under.15k*nettohh_f_first.under.15k + delta_nettohh_f.over.50k*nettohh_f_first.over.50k + delta_herkomstgroep.first.w*herkomstgroep_first.first.w + delta_herkomstgroep.first.nonw*herkomstgroep_first.first.nonw + delta_herkomstgroep.second.w*herkomstgroep_first.second.w + delta_herkomstgroep.second.nonw*herkomstgroep_first.second.nonw + delta_geslacht.male*geslacht_first.male + delta_burgstat.married*burgstat_first.married + delta_burgstat.never.been.married*burgstat_first.never.been.married + delta_burgstat.separated*burgstat_first.separated + delta_burgstat.widow.or.widower*burgstat_first.widow.or.widower + delta_oplcat.hbo*oplcat_first.hbo + delta_oplcat.mbo*oplcat_first.mbo + delta_oplcat.primary.school*oplcat_first.primary.school + delta_oplcat.vmbo*oplcat_first.vmbo + delta_oplcat.wo*oplcat_first.wo + delta_employment.homemaker*employment_first.homemaker + delta_employment.retired*employment_first.retired + delta_employment.student*employment_first.student + delta_employment.unable.to.work*employment_first.unable.to.work + delta_employment.unemployed*employment_first.unemployed
mhi5_20 ~ alpha_mhi5_20*1 + rho1*mhi5_19 + rho2*mhi5_18 + rho3*mhi5_17 + beta0_cs104*cs104_20 + beta1_cs104*cs104_19 + delta_leeftijd.18.24*leeftijd_first.18.24 + delta_leeftijd.25.39*leeftijd_first.25.39 + delta_leeftijd.40.66*leeftijd_first.40.66 + delta_leeftijd.over.67*leeftijd_first.over.67 + delta_nettohh_f.under.15k*nettohh_f_first.under.15k + delta_nettohh_f.over.50k*nettohh_f_first.over.50k + delta_herkomstgroep.first.w*herkomstgroep_first.first.w + delta_herkomstgroep.first.nonw*herkomstgroep_first.first.nonw + delta_herkomstgroep.second.w*herkomstgroep_first.second.w + delta_herkomstgroep.second.nonw*herkomstgroep_first.second.nonw + delta_geslacht.male*geslacht_first.male + delta_burgstat.married*burgstat_first.married + delta_burgstat.never.been.married*burgstat_first.never.been.married + delta_burgstat.separated*burgstat_first.separated + delta_burgstat.widow.or.widower*burgstat_first.widow.or.widower + delta_oplcat.hbo*oplcat_first.hbo + delta_oplcat.mbo*oplcat_first.mbo + delta_oplcat.primary.school*oplcat_first.primary.school + delta_oplcat.vmbo*oplcat_first.vmbo + delta_oplcat.wo*oplcat_first.wo + delta_employment.homemaker*employment_first.homemaker + delta_employment.retired*employment_first.retired + delta_employment.student*employment_first.student + delta_employment.unable.to.work*employment_first.unable.to.work + delta_employment.unemployed*employment_first.unemployed
mhi5_21 ~ alpha_mhi5_21*1 + rho1*mhi5_20 + rho2*mhi5_19 + rho3*mhi5_18 + beta0_cs104*cs104_21 + beta1_cs104*cs104_20 + delta_leeftijd.18.24*leeftijd_first.18.24 + delta_leeftijd.25.39*leeftijd_first.25.39 + delta_leeftijd.40.66*leeftijd_first.40.66 + delta_leeftijd.over.67*leeftijd_first.over.67 + delta_nettohh_f.under.15k*nettohh_f_first.under.15k + delta_nettohh_f.over.50k*nettohh_f_first.over.50k + delta_herkomstgroep.first.w*herkomstgroep_first.first.w + delta_herkomstgroep.first.nonw*herkomstgroep_first.first.nonw + delta_herkomstgroep.second.w*herkomstgroep_first.second.w + delta_herkomstgroep.second.nonw*herkomstgroep_first.second.nonw + delta_geslacht.male*geslacht_first.male + delta_burgstat.married*burgstat_first.married + delta_burgstat.never.been.married*burgstat_first.never.been.married + delta_burgstat.separated*burgstat_first.separated + delta_burgstat.widow.or.widower*burgstat_first.widow.or.widower + delta_oplcat.hbo*oplcat_first.hbo + delta_oplcat.mbo*oplcat_first.mbo + delta_oplcat.primary.school*oplcat_first.primary.school + delta_oplcat.vmbo*oplcat_first.vmbo + delta_oplcat.wo*oplcat_first.wo + delta_employment.homemaker*employment_first.homemaker + delta_employment.retired*employment_first.retired + delta_employment.student*employment_first.student + delta_employment.unable.to.work*employment_first.unable.to.work + delta_employment.unemployed*employment_first.unemployed
mhi5_22 ~ alpha_mhi5_22*1 + rho1*mhi5_21 + rho2*mhi5_20 + rho3*mhi5_19 + beta0_cs104*cs104_22 + beta1_cs104*cs104_21 + delta_leeftijd.18.24*leeftijd_first.18.24 + delta_leeftijd.25.39*leeftijd_first.25.39 + delta_leeftijd.40.66*leeftijd_first.40.66 + delta_leeftijd.over.67*leeftijd_first.over.67 + delta_nettohh_f.under.15k*nettohh_f_first.under.15k + delta_nettohh_f.over.50k*nettohh_f_first.over.50k + delta_herkomstgroep.first.w*herkomstgroep_first.first.w + delta_herkomstgroep.first.nonw*herkomstgroep_first.first.nonw + delta_herkomstgroep.second.w*herkomstgroep_first.second.w + delta_herkomstgroep.second.nonw*herkomstgroep_first.second.nonw + delta_geslacht.male*geslacht_first.male + delta_burgstat.married*burgstat_first.married + delta_burgstat.never.been.married*burgstat_first.never.been.married + delta_burgstat.separated*burgstat_first.separated + delta_burgstat.widow.or.widower*burgstat_first.widow.or.widower + delta_oplcat.hbo*oplcat_first.hbo + delta_oplcat.mbo*oplcat_first.mbo + delta_oplcat.primary.school*oplcat_first.primary.school + delta_oplcat.vmbo*oplcat_first.vmbo + delta_oplcat.wo*oplcat_first.wo + delta_employment.homemaker*employment_first.homemaker + delta_employment.retired*employment_first.retired + delta_employment.student*employment_first.student + delta_employment.unable.to.work*employment_first.unable.to.work + delta_employment.unemployed*employment_first.unemployed
mhi5_23 ~ alpha_mhi5_23*1 + rho1*mhi5_22 + rho2*mhi5_21 + rho3*mhi5_20 + beta0_cs104*cs104_23 + beta1_cs104*cs104_22 + delta_leeftijd.18.24*leeftijd_first.18.24 + delta_leeftijd.25.39*leeftijd_first.25.39 + delta_leeftijd.40.66*leeftijd_first.40.66 + delta_leeftijd.over.67*leeftijd_first.over.67 + delta_nettohh_f.under.15k*nettohh_f_first.under.15k + delta_nettohh_f.over.50k*nettohh_f_first.over.50k + delta_herkomstgroep.first.w*herkomstgroep_first.first.w + delta_herkomstgroep.first.nonw*herkomstgroep_first.first.nonw + delta_herkomstgroep.second.w*herkomstgroep_first.second.w + delta_herkomstgroep.second.nonw*herkomstgroep_first.second.nonw + delta_geslacht.male*geslacht_first.male + delta_burgstat.married*burgstat_first.married + delta_burgstat.never.been.married*burgstat_first.never.been.married + delta_burgstat.separated*burgstat_first.separated + delta_burgstat.widow.or.widower*burgstat_first.widow.or.widower + delta_oplcat.hbo*oplcat_first.hbo + delta_oplcat.mbo*oplcat_first.mbo + delta_oplcat.primary.school*oplcat_first.primary.school + delta_oplcat.vmbo*oplcat_first.vmbo + delta_oplcat.wo*oplcat_first.wo + delta_employment.homemaker*employment_first.homemaker + delta_employment.retired*employment_first.retired + delta_employment.student*employment_first.student + delta_employment.unable.to.work*employment_first.unable.to.work + delta_employment.unemployed*employment_first.unemployed

"
```

```{r Fit base model}
fit <- sem(sem_model, data = all_data, estimator = "MLR", missing = "fiml.x")

summary(fit, fit.measures = TRUE)
```

```{r Potential model improvements}
# Adding paths (= relaxing 0 constraints)
mi <- modificationindices(fit)

head(mi[order(-mi$mi), , ], 10)

# Relaxing equality constraints
lts <- lavTestScore(fit)

big_lts <- lts$uni[order(-lts$uni$X2), ]
big_lts <- big_lts[big_lts$p.value <= 0.1, ]
big_lts

pt <- partable(fit)
pt[pt$plabel %in% c(as.character(big_lts$lhs), as.character(big_lts$rhs)), ]
```

```{r Define mediation model}
sem_model_mediation <- "
# Regressions
mhi5_13 ~ alpha_mhi5_13*1 + rho1*mhi5_12 + rho2*mhi5_11 + rho3*mhi5_10 + beta0_cs104*cs104_13 + beta1_cs104*cs104_12 + zeta_ch4.good*ch4_13.good + zeta_ch4.moderate*ch4_13.moderate + zeta_ch4.poor*ch4_13.poor + zeta_ch4.very.good*ch4_13.very.good + zeta_bmi.normal.weight*bmi_13.normal.weight + zeta_bmi.overweight*bmi_13.overweight + zeta_bmi.obese*bmi_13.obese + zeta_ch98*ch98_13 + delta_leeftijd.18.24*leeftijd_first.18.24 + delta_leeftijd.25.39*leeftijd_first.25.39 + delta_leeftijd.40.66*leeftijd_first.40.66 + delta_leeftijd.over.67*leeftijd_first.over.67 + delta_nettohh_f.under.15k*nettohh_f_first.under.15k + delta_nettohh_f.over.50k*nettohh_f_first.over.50k + delta_herkomstgroep.first.w*herkomstgroep_first.first.w + delta_herkomstgroep.first.nonw*herkomstgroep_first.first.nonw + delta_herkomstgroep.second.w*herkomstgroep_first.second.w + delta_herkomstgroep.second.nonw*herkomstgroep_first.second.nonw + delta_geslacht.male*geslacht_first.male + delta_burgstat.married*burgstat_first.married + delta_burgstat.never.been.married*burgstat_first.never.been.married + delta_burgstat.separated*burgstat_first.separated + delta_burgstat.widow.or.widower*burgstat_first.widow.or.widower + delta_oplcat.hbo*oplcat_first.hbo + delta_oplcat.mbo*oplcat_first.mbo + delta_oplcat.primary.school*oplcat_first.primary.school + delta_oplcat.vmbo*oplcat_first.vmbo + delta_oplcat.wo*oplcat_first.wo + delta_employment.homemaker*employment_first.homemaker + delta_employment.retired*employment_first.retired + delta_employment.student*employment_first.student + delta_employment.unable.to.work*employment_first.unable.to.work + delta_employment.unemployed*employment_first.unemployed
ch4_13.good ~ alpha_ch4.good_13*1 + eta_ch4.good_y1*mhi5_12 + eta_ch4.good_y2*mhi5_11 + eta_ch4.good_y3*mhi5_10 + eta_ch4.good_x0*cs104_13 + eta_ch4.good_x1*cs104_12 + eta_ch4.good_leeftijd.18.24*leeftijd_first.18.24 + eta_ch4.good_leeftijd.25.39*leeftijd_first.25.39 + eta_ch4.good_leeftijd.40.66*leeftijd_first.40.66 + eta_ch4.good_leeftijd.over.67*leeftijd_first.over.67 + eta_ch4.good_nettohh_f.under.15k*nettohh_f_first.under.15k + eta_ch4.good_nettohh_f.over.50k*nettohh_f_first.over.50k + eta_ch4.good_herkomstgroep.first.w*herkomstgroep_first.first.w + eta_ch4.good_herkomstgroep.first.nonw*herkomstgroep_first.first.nonw + eta_ch4.good_herkomstgroep.second.w*herkomstgroep_first.second.w + eta_ch4.good_herkomstgroep.second.nonw*herkomstgroep_first.second.nonw + eta_ch4.good_geslacht.male*geslacht_first.male + eta_ch4.good_burgstat.married*burgstat_first.married + eta_ch4.good_burgstat.never.been.married*burgstat_first.never.been.married + eta_ch4.good_burgstat.separated*burgstat_first.separated + eta_ch4.good_burgstat.widow.or.widower*burgstat_first.widow.or.widower + eta_ch4.good_oplcat.hbo*oplcat_first.hbo + eta_ch4.good_oplcat.mbo*oplcat_first.mbo + eta_ch4.good_oplcat.primary.school*oplcat_first.primary.school + eta_ch4.good_oplcat.vmbo*oplcat_first.vmbo + eta_ch4.good_oplcat.wo*oplcat_first.wo + eta_ch4.good_employment.homemaker*employment_first.homemaker + eta_ch4.good_employment.retired*employment_first.retired + eta_ch4.good_employment.student*employment_first.student + eta_ch4.good_employment.unable.to.work*employment_first.unable.to.work + eta_ch4.good_employment.unemployed*employment_first.unemployed
ch4_13.moderate ~ alpha_ch4.moderate_13*1 + eta_ch4.moderate_y1*mhi5_12 + eta_ch4.moderate_y2*mhi5_11 + eta_ch4.moderate_y3*mhi5_10 + eta_ch4.moderate_x0*cs104_13 + eta_ch4.moderate_x1*cs104_12 + eta_ch4.moderate_leeftijd.18.24*leeftijd_first.18.24 + eta_ch4.moderate_leeftijd.25.39*leeftijd_first.25.39 + eta_ch4.moderate_leeftijd.40.66*leeftijd_first.40.66 + eta_ch4.moderate_leeftijd.over.67*leeftijd_first.over.67 + eta_ch4.moderate_nettohh_f.under.15k*nettohh_f_first.under.15k + eta_ch4.moderate_nettohh_f.over.50k*nettohh_f_first.over.50k + eta_ch4.moderate_herkomstgroep.first.w*herkomstgroep_first.first.w + eta_ch4.moderate_herkomstgroep.first.nonw*herkomstgroep_first.first.nonw + eta_ch4.moderate_herkomstgroep.second.w*herkomstgroep_first.second.w + eta_ch4.moderate_herkomstgroep.second.nonw*herkomstgroep_first.second.nonw + eta_ch4.moderate_geslacht.male*geslacht_first.male + eta_ch4.moderate_burgstat.married*burgstat_first.married + eta_ch4.moderate_burgstat.never.been.married*burgstat_first.never.been.married + eta_ch4.moderate_burgstat.separated*burgstat_first.separated + eta_ch4.moderate_burgstat.widow.or.widower*burgstat_first.widow.or.widower + eta_ch4.moderate_oplcat.hbo*oplcat_first.hbo + eta_ch4.moderate_oplcat.mbo*oplcat_first.mbo + eta_ch4.moderate_oplcat.primary.school*oplcat_first.primary.school + eta_ch4.moderate_oplcat.vmbo*oplcat_first.vmbo + eta_ch4.moderate_oplcat.wo*oplcat_first.wo + eta_ch4.moderate_employment.homemaker*employment_first.homemaker + eta_ch4.moderate_employment.retired*employment_first.retired + eta_ch4.moderate_employment.student*employment_first.student + eta_ch4.moderate_employment.unable.to.work*employment_first.unable.to.work + eta_ch4.moderate_employment.unemployed*employment_first.unemployed
ch4_13.poor ~ alpha_ch4.poor_13*1 + eta_ch4.poor_y1*mhi5_12 + eta_ch4.poor_y2*mhi5_11 + eta_ch4.poor_y3*mhi5_10 + eta_ch4.poor_x0*cs104_13 + eta_ch4.poor_x1*cs104_12 + eta_ch4.poor_leeftijd.18.24*leeftijd_first.18.24 + eta_ch4.poor_leeftijd.25.39*leeftijd_first.25.39 + eta_ch4.poor_leeftijd.40.66*leeftijd_first.40.66 + eta_ch4.poor_leeftijd.over.67*leeftijd_first.over.67 + eta_ch4.poor_nettohh_f.under.15k*nettohh_f_first.under.15k + eta_ch4.poor_nettohh_f.over.50k*nettohh_f_first.over.50k + eta_ch4.poor_herkomstgroep.first.w*herkomstgroep_first.first.w + eta_ch4.poor_herkomstgroep.first.nonw*herkomstgroep_first.first.nonw + eta_ch4.poor_herkomstgroep.second.w*herkomstgroep_first.second.w + eta_ch4.poor_herkomstgroep.second.nonw*herkomstgroep_first.second.nonw + eta_ch4.poor_geslacht.male*geslacht_first.male + eta_ch4.poor_burgstat.married*burgstat_first.married + eta_ch4.poor_burgstat.never.been.married*burgstat_first.never.been.married + eta_ch4.poor_burgstat.separated*burgstat_first.separated + eta_ch4.poor_burgstat.widow.or.widower*burgstat_first.widow.or.widower + eta_ch4.poor_oplcat.hbo*oplcat_first.hbo + eta_ch4.poor_oplcat.mbo*oplcat_first.mbo + eta_ch4.poor_oplcat.primary.school*oplcat_first.primary.school + eta_ch4.poor_oplcat.vmbo*oplcat_first.vmbo + eta_ch4.poor_oplcat.wo*oplcat_first.wo + eta_ch4.poor_employment.homemaker*employment_first.homemaker + eta_ch4.poor_employment.retired*employment_first.retired + eta_ch4.poor_employment.student*employment_first.student + eta_ch4.poor_employment.unable.to.work*employment_first.unable.to.work + eta_ch4.poor_employment.unemployed*employment_first.unemployed
ch4_13.very.good ~ alpha_ch4.very.good_13*1 + eta_ch4.very.good_y1*mhi5_12 + eta_ch4.very.good_y2*mhi5_11 + eta_ch4.very.good_y3*mhi5_10 + eta_ch4.very.good_x0*cs104_13 + eta_ch4.very.good_x1*cs104_12 + eta_ch4.very.good_leeftijd.18.24*leeftijd_first.18.24 + eta_ch4.very.good_leeftijd.25.39*leeftijd_first.25.39 + eta_ch4.very.good_leeftijd.40.66*leeftijd_first.40.66 + eta_ch4.very.good_leeftijd.over.67*leeftijd_first.over.67 + eta_ch4.very.good_nettohh_f.under.15k*nettohh_f_first.under.15k + eta_ch4.very.good_nettohh_f.over.50k*nettohh_f_first.over.50k + eta_ch4.very.good_herkomstgroep.first.w*herkomstgroep_first.first.w + eta_ch4.very.good_herkomstgroep.first.nonw*herkomstgroep_first.first.nonw + eta_ch4.very.good_herkomstgroep.second.w*herkomstgroep_first.second.w + eta_ch4.very.good_herkomstgroep.second.nonw*herkomstgroep_first.second.nonw + eta_ch4.very.good_geslacht.male*geslacht_first.male + eta_ch4.very.good_burgstat.married*burgstat_first.married + eta_ch4.very.good_burgstat.never.been.married*burgstat_first.never.been.married + eta_ch4.very.good_burgstat.separated*burgstat_first.separated + eta_ch4.very.good_burgstat.widow.or.widower*burgstat_first.widow.or.widower + eta_ch4.very.good_oplcat.hbo*oplcat_first.hbo + eta_ch4.very.good_oplcat.mbo*oplcat_first.mbo + eta_ch4.very.good_oplcat.primary.school*oplcat_first.primary.school + eta_ch4.very.good_oplcat.vmbo*oplcat_first.vmbo + eta_ch4.very.good_oplcat.wo*oplcat_first.wo + eta_ch4.very.good_employment.homemaker*employment_first.homemaker + eta_ch4.very.good_employment.retired*employment_first.retired + eta_ch4.very.good_employment.student*employment_first.student + eta_ch4.very.good_employment.unable.to.work*employment_first.unable.to.work + eta_ch4.very.good_employment.unemployed*employment_first.unemployed
bmi_13.normal.weight ~ alpha_bmi.normal.weight_13*1 + eta_bmi.normal.weight_y1*mhi5_12 + eta_bmi.normal.weight_y2*mhi5_11 + eta_bmi.normal.weight_y3*mhi5_10 + eta_bmi.normal.weight_x0*cs104_13 + eta_bmi.normal.weight_x1*cs104_12 + eta_bmi.normal.weight_leeftijd.18.24*leeftijd_first.18.24 + eta_bmi.normal.weight_leeftijd.25.39*leeftijd_first.25.39 + eta_bmi.normal.weight_leeftijd.40.66*leeftijd_first.40.66 + eta_bmi.normal.weight_leeftijd.over.67*leeftijd_first.over.67 + eta_bmi.normal.weight_nettohh_f.under.15k*nettohh_f_first.under.15k + eta_bmi.normal.weight_nettohh_f.over.50k*nettohh_f_first.over.50k + eta_bmi.normal.weight_herkomstgroep.first.w*herkomstgroep_first.first.w + eta_bmi.normal.weight_herkomstgroep.first.nonw*herkomstgroep_first.first.nonw + eta_bmi.normal.weight_herkomstgroep.second.w*herkomstgroep_first.second.w + eta_bmi.normal.weight_herkomstgroep.second.nonw*herkomstgroep_first.second.nonw + eta_bmi.normal.weight_geslacht.male*geslacht_first.male + eta_bmi.normal.weight_burgstat.married*burgstat_first.married + eta_bmi.normal.weight_burgstat.never.been.married*burgstat_first.never.been.married + eta_bmi.normal.weight_burgstat.separated*burgstat_first.separated + eta_bmi.normal.weight_burgstat.widow.or.widower*burgstat_first.widow.or.widower + eta_bmi.normal.weight_oplcat.hbo*oplcat_first.hbo + eta_bmi.normal.weight_oplcat.mbo*oplcat_first.mbo + eta_bmi.normal.weight_oplcat.primary.school*oplcat_first.primary.school + eta_bmi.normal.weight_oplcat.vmbo*oplcat_first.vmbo + eta_bmi.normal.weight_oplcat.wo*oplcat_first.wo + eta_bmi.normal.weight_employment.homemaker*employment_first.homemaker + eta_bmi.normal.weight_employment.retired*employment_first.retired + eta_bmi.normal.weight_employment.student*employment_first.student + eta_bmi.normal.weight_employment.unable.to.work*employment_first.unable.to.work + eta_bmi.normal.weight_employment.unemployed*employment_first.unemployed
bmi_13.overweight ~ alpha_bmi.overweight_13*1 + eta_bmi.overweight_y1*mhi5_12 + eta_bmi.overweight_y2*mhi5_11 + eta_bmi.overweight_y3*mhi5_10 + eta_bmi.overweight_x0*cs104_13 + eta_bmi.overweight_x1*cs104_12 + eta_bmi.overweight_leeftijd.18.24*leeftijd_first.18.24 + eta_bmi.overweight_leeftijd.25.39*leeftijd_first.25.39 + eta_bmi.overweight_leeftijd.40.66*leeftijd_first.40.66 + eta_bmi.overweight_leeftijd.over.67*leeftijd_first.over.67 + eta_bmi.overweight_nettohh_f.under.15k*nettohh_f_first.under.15k + eta_bmi.overweight_nettohh_f.over.50k*nettohh_f_first.over.50k + eta_bmi.overweight_herkomstgroep.first.w*herkomstgroep_first.first.w + eta_bmi.overweight_herkomstgroep.first.nonw*herkomstgroep_first.first.nonw + eta_bmi.overweight_herkomstgroep.second.w*herkomstgroep_first.second.w + eta_bmi.overweight_herkomstgroep.second.nonw*herkomstgroep_first.second.nonw + eta_bmi.overweight_geslacht.male*geslacht_first.male + eta_bmi.overweight_burgstat.married*burgstat_first.married + eta_bmi.overweight_burgstat.never.been.married*burgstat_first.never.been.married + eta_bmi.overweight_burgstat.separated*burgstat_first.separated + eta_bmi.overweight_burgstat.widow.or.widower*burgstat_first.widow.or.widower + eta_bmi.overweight_oplcat.hbo*oplcat_first.hbo + eta_bmi.overweight_oplcat.mbo*oplcat_first.mbo + eta_bmi.overweight_oplcat.primary.school*oplcat_first.primary.school + eta_bmi.overweight_oplcat.vmbo*oplcat_first.vmbo + eta_bmi.overweight_oplcat.wo*oplcat_first.wo + eta_bmi.overweight_employment.homemaker*employment_first.homemaker + eta_bmi.overweight_employment.retired*employment_first.retired + eta_bmi.overweight_employment.student*employment_first.student + eta_bmi.overweight_employment.unable.to.work*employment_first.unable.to.work + eta_bmi.overweight_employment.unemployed*employment_first.unemployed
bmi_13.obese ~ alpha_bmi.obese_13*1 + eta_bmi.obese_y1*mhi5_12 + eta_bmi.obese_y2*mhi5_11 + eta_bmi.obese_y3*mhi5_10 + eta_bmi.obese_x0*cs104_13 + eta_bmi.obese_x1*cs104_12 + eta_bmi.obese_leeftijd.18.24*leeftijd_first.18.24 + eta_bmi.obese_leeftijd.25.39*leeftijd_first.25.39 + eta_bmi.obese_leeftijd.40.66*leeftijd_first.40.66 + eta_bmi.obese_leeftijd.over.67*leeftijd_first.over.67 + eta_bmi.obese_nettohh_f.under.15k*nettohh_f_first.under.15k + eta_bmi.obese_nettohh_f.over.50k*nettohh_f_first.over.50k + eta_bmi.obese_herkomstgroep.first.w*herkomstgroep_first.first.w + eta_bmi.obese_herkomstgroep.first.nonw*herkomstgroep_first.first.nonw + eta_bmi.obese_herkomstgroep.second.w*herkomstgroep_first.second.w + eta_bmi.obese_herkomstgroep.second.nonw*herkomstgroep_first.second.nonw + eta_bmi.obese_geslacht.male*geslacht_first.male + eta_bmi.obese_burgstat.married*burgstat_first.married + eta_bmi.obese_burgstat.never.been.married*burgstat_first.never.been.married + eta_bmi.obese_burgstat.separated*burgstat_first.separated + eta_bmi.obese_burgstat.widow.or.widower*burgstat_first.widow.or.widower + eta_bmi.obese_oplcat.hbo*oplcat_first.hbo + eta_bmi.obese_oplcat.mbo*oplcat_first.mbo + eta_bmi.obese_oplcat.primary.school*oplcat_first.primary.school + eta_bmi.obese_oplcat.vmbo*oplcat_first.vmbo + eta_bmi.obese_oplcat.wo*oplcat_first.wo + eta_bmi.obese_employment.homemaker*employment_first.homemaker + eta_bmi.obese_employment.retired*employment_first.retired + eta_bmi.obese_employment.student*employment_first.student + eta_bmi.obese_employment.unable.to.work*employment_first.unable.to.work + eta_bmi.obese_employment.unemployed*employment_first.unemployed
ch98_13 ~ alpha_ch98_13*1 + eta_ch98_y1*mhi5_12 + eta_ch98_y2*mhi5_11 + eta_ch98_y3*mhi5_10 + eta_ch98_x0*cs104_13 + eta_ch98_x1*cs104_12 + eta_ch98_leeftijd.18.24*leeftijd_first.18.24 + eta_ch98_leeftijd.25.39*leeftijd_first.25.39 + eta_ch98_leeftijd.40.66*leeftijd_first.40.66 + eta_ch98_leeftijd.over.67*leeftijd_first.over.67 + eta_ch98_nettohh_f.under.15k*nettohh_f_first.under.15k + eta_ch98_nettohh_f.over.50k*nettohh_f_first.over.50k + eta_ch98_herkomstgroep.first.w*herkomstgroep_first.first.w + eta_ch98_herkomstgroep.first.nonw*herkomstgroep_first.first.nonw + eta_ch98_herkomstgroep.second.w*herkomstgroep_first.second.w + eta_ch98_herkomstgroep.second.nonw*herkomstgroep_first.second.nonw + eta_ch98_geslacht.male*geslacht_first.male + eta_ch98_burgstat.married*burgstat_first.married + eta_ch98_burgstat.never.been.married*burgstat_first.never.been.married + eta_ch98_burgstat.separated*burgstat_first.separated + eta_ch98_burgstat.widow.or.widower*burgstat_first.widow.or.widower + eta_ch98_oplcat.hbo*oplcat_first.hbo + eta_ch98_oplcat.mbo*oplcat_first.mbo + eta_ch98_oplcat.primary.school*oplcat_first.primary.school + eta_ch98_oplcat.vmbo*oplcat_first.vmbo + eta_ch98_oplcat.wo*oplcat_first.wo + eta_ch98_employment.homemaker*employment_first.homemaker + eta_ch98_employment.retired*employment_first.retired + eta_ch98_employment.student*employment_first.student + eta_ch98_employment.unable.to.work*employment_first.unable.to.work + eta_ch98_employment.unemployed*employment_first.unemployed
mhi5_18 ~ alpha_mhi5_18*1 + rho1*mhi5_17 + rho2*mhi5_16 + rho3*mhi5_15 + beta0_cs104*cs104_18 + beta1_cs104*cs104_17 + zeta_ch4.good*ch4_18.good + zeta_ch4.moderate*ch4_18.moderate + zeta_ch4.poor*ch4_18.poor + zeta_ch4.very.good*ch4_18.very.good + zeta_bmi.normal.weight*bmi_18.normal.weight + zeta_bmi.overweight*bmi_18.overweight + zeta_bmi.obese*bmi_18.obese + zeta_ch98*ch98_18 + delta_leeftijd.18.24*leeftijd_first.18.24 + delta_leeftijd.25.39*leeftijd_first.25.39 + delta_leeftijd.40.66*leeftijd_first.40.66 + delta_leeftijd.over.67*leeftijd_first.over.67 + delta_nettohh_f.under.15k*nettohh_f_first.under.15k + delta_nettohh_f.over.50k*nettohh_f_first.over.50k + delta_herkomstgroep.first.w*herkomstgroep_first.first.w + delta_herkomstgroep.first.nonw*herkomstgroep_first.first.nonw + delta_herkomstgroep.second.w*herkomstgroep_first.second.w + delta_herkomstgroep.second.nonw*herkomstgroep_first.second.nonw + delta_geslacht.male*geslacht_first.male + delta_burgstat.married*burgstat_first.married + delta_burgstat.never.been.married*burgstat_first.never.been.married + delta_burgstat.separated*burgstat_first.separated + delta_burgstat.widow.or.widower*burgstat_first.widow.or.widower + delta_oplcat.hbo*oplcat_first.hbo + delta_oplcat.mbo*oplcat_first.mbo + delta_oplcat.primary.school*oplcat_first.primary.school + delta_oplcat.vmbo*oplcat_first.vmbo + delta_oplcat.wo*oplcat_first.wo + delta_employment.homemaker*employment_first.homemaker + delta_employment.retired*employment_first.retired + delta_employment.student*employment_first.student + delta_employment.unable.to.work*employment_first.unable.to.work + delta_employment.unemployed*employment_first.unemployed
ch4_18.good ~ alpha_ch4.good_18*1 + eta_ch4.good_y1*mhi5_17 + eta_ch4.good_y2*mhi5_16 + eta_ch4.good_y3*mhi5_15 + eta_ch4.good_x0*cs104_18 + eta_ch4.good_x1*cs104_17 + eta_ch4.good_leeftijd.18.24*leeftijd_first.18.24 + eta_ch4.good_leeftijd.25.39*leeftijd_first.25.39 + eta_ch4.good_leeftijd.40.66*leeftijd_first.40.66 + eta_ch4.good_leeftijd.over.67*leeftijd_first.over.67 + eta_ch4.good_nettohh_f.under.15k*nettohh_f_first.under.15k + eta_ch4.good_nettohh_f.over.50k*nettohh_f_first.over.50k + eta_ch4.good_herkomstgroep.first.w*herkomstgroep_first.first.w + eta_ch4.good_herkomstgroep.first.nonw*herkomstgroep_first.first.nonw + eta_ch4.good_herkomstgroep.second.w*herkomstgroep_first.second.w + eta_ch4.good_herkomstgroep.second.nonw*herkomstgroep_first.second.nonw + eta_ch4.good_geslacht.male*geslacht_first.male + eta_ch4.good_burgstat.married*burgstat_first.married + eta_ch4.good_burgstat.never.been.married*burgstat_first.never.been.married + eta_ch4.good_burgstat.separated*burgstat_first.separated + eta_ch4.good_burgstat.widow.or.widower*burgstat_first.widow.or.widower + eta_ch4.good_oplcat.hbo*oplcat_first.hbo + eta_ch4.good_oplcat.mbo*oplcat_first.mbo + eta_ch4.good_oplcat.primary.school*oplcat_first.primary.school + eta_ch4.good_oplcat.vmbo*oplcat_first.vmbo + eta_ch4.good_oplcat.wo*oplcat_first.wo + eta_ch4.good_employment.homemaker*employment_first.homemaker + eta_ch4.good_employment.retired*employment_first.retired + eta_ch4.good_employment.student*employment_first.student + eta_ch4.good_employment.unable.to.work*employment_first.unable.to.work + eta_ch4.good_employment.unemployed*employment_first.unemployed
ch4_18.moderate ~ alpha_ch4.moderate_18*1 + eta_ch4.moderate_y1*mhi5_17 + eta_ch4.moderate_y2*mhi5_16 + eta_ch4.moderate_y3*mhi5_15 + eta_ch4.moderate_x0*cs104_18 + eta_ch4.moderate_x1*cs104_17 + eta_ch4.moderate_leeftijd.18.24*leeftijd_first.18.24 + eta_ch4.moderate_leeftijd.25.39*leeftijd_first.25.39 + eta_ch4.moderate_leeftijd.40.66*leeftijd_first.40.66 + eta_ch4.moderate_leeftijd.over.67*leeftijd_first.over.67 + eta_ch4.moderate_nettohh_f.under.15k*nettohh_f_first.under.15k + eta_ch4.moderate_nettohh_f.over.50k*nettohh_f_first.over.50k + eta_ch4.moderate_herkomstgroep.first.w*herkomstgroep_first.first.w + eta_ch4.moderate_herkomstgroep.first.nonw*herkomstgroep_first.first.nonw + eta_ch4.moderate_herkomstgroep.second.w*herkomstgroep_first.second.w + eta_ch4.moderate_herkomstgroep.second.nonw*herkomstgroep_first.second.nonw + eta_ch4.moderate_geslacht.male*geslacht_first.male + eta_ch4.moderate_burgstat.married*burgstat_first.married + eta_ch4.moderate_burgstat.never.been.married*burgstat_first.never.been.married + eta_ch4.moderate_burgstat.separated*burgstat_first.separated + eta_ch4.moderate_burgstat.widow.or.widower*burgstat_first.widow.or.widower + eta_ch4.moderate_oplcat.hbo*oplcat_first.hbo + eta_ch4.moderate_oplcat.mbo*oplcat_first.mbo + eta_ch4.moderate_oplcat.primary.school*oplcat_first.primary.school + eta_ch4.moderate_oplcat.vmbo*oplcat_first.vmbo + eta_ch4.moderate_oplcat.wo*oplcat_first.wo + eta_ch4.moderate_employment.homemaker*employment_first.homemaker + eta_ch4.moderate_employment.retired*employment_first.retired + eta_ch4.moderate_employment.student*employment_first.student + eta_ch4.moderate_employment.unable.to.work*employment_first.unable.to.work + eta_ch4.moderate_employment.unemployed*employment_first.unemployed
ch4_18.poor ~ alpha_ch4.poor_18*1 + eta_ch4.poor_y1*mhi5_17 + eta_ch4.poor_y2*mhi5_16 + eta_ch4.poor_y3*mhi5_15 + eta_ch4.poor_x0*cs104_18 + eta_ch4.poor_x1*cs104_17 + eta_ch4.poor_leeftijd.18.24*leeftijd_first.18.24 + eta_ch4.poor_leeftijd.25.39*leeftijd_first.25.39 + eta_ch4.poor_leeftijd.40.66*leeftijd_first.40.66 + eta_ch4.poor_leeftijd.over.67*leeftijd_first.over.67 + eta_ch4.poor_nettohh_f.under.15k*nettohh_f_first.under.15k + eta_ch4.poor_nettohh_f.over.50k*nettohh_f_first.over.50k + eta_ch4.poor_herkomstgroep.first.w*herkomstgroep_first.first.w + eta_ch4.poor_herkomstgroep.first.nonw*herkomstgroep_first.first.nonw + eta_ch4.poor_herkomstgroep.second.w*herkomstgroep_first.second.w + eta_ch4.poor_herkomstgroep.second.nonw*herkomstgroep_first.second.nonw + eta_ch4.poor_geslacht.male*geslacht_first.male + eta_ch4.poor_burgstat.married*burgstat_first.married + eta_ch4.poor_burgstat.never.been.married*burgstat_first.never.been.married + eta_ch4.poor_burgstat.separated*burgstat_first.separated + eta_ch4.poor_burgstat.widow.or.widower*burgstat_first.widow.or.widower + eta_ch4.poor_oplcat.hbo*oplcat_first.hbo + eta_ch4.poor_oplcat.mbo*oplcat_first.mbo + eta_ch4.poor_oplcat.primary.school*oplcat_first.primary.school + eta_ch4.poor_oplcat.vmbo*oplcat_first.vmbo + eta_ch4.poor_oplcat.wo*oplcat_first.wo + eta_ch4.poor_employment.homemaker*employment_first.homemaker + eta_ch4.poor_employment.retired*employment_first.retired + eta_ch4.poor_employment.student*employment_first.student + eta_ch4.poor_employment.unable.to.work*employment_first.unable.to.work + eta_ch4.poor_employment.unemployed*employment_first.unemployed
ch4_18.very.good ~ alpha_ch4.very.good_18*1 + eta_ch4.very.good_y1*mhi5_17 + eta_ch4.very.good_y2*mhi5_16 + eta_ch4.very.good_y3*mhi5_15 + eta_ch4.very.good_x0*cs104_18 + eta_ch4.very.good_x1*cs104_17 + eta_ch4.very.good_leeftijd.18.24*leeftijd_first.18.24 + eta_ch4.very.good_leeftijd.25.39*leeftijd_first.25.39 + eta_ch4.very.good_leeftijd.40.66*leeftijd_first.40.66 + eta_ch4.very.good_leeftijd.over.67*leeftijd_first.over.67 + eta_ch4.very.good_nettohh_f.under.15k*nettohh_f_first.under.15k + eta_ch4.very.good_nettohh_f.over.50k*nettohh_f_first.over.50k + eta_ch4.very.good_herkomstgroep.first.w*herkomstgroep_first.first.w + eta_ch4.very.good_herkomstgroep.first.nonw*herkomstgroep_first.first.nonw + eta_ch4.very.good_herkomstgroep.second.w*herkomstgroep_first.second.w + eta_ch4.very.good_herkomstgroep.second.nonw*herkomstgroep_first.second.nonw + eta_ch4.very.good_geslacht.male*geslacht_first.male + eta_ch4.very.good_burgstat.married*burgstat_first.married + eta_ch4.very.good_burgstat.never.been.married*burgstat_first.never.been.married + eta_ch4.very.good_burgstat.separated*burgstat_first.separated + eta_ch4.very.good_burgstat.widow.or.widower*burgstat_first.widow.or.widower + eta_ch4.very.good_oplcat.hbo*oplcat_first.hbo + eta_ch4.very.good_oplcat.mbo*oplcat_first.mbo + eta_ch4.very.good_oplcat.primary.school*oplcat_first.primary.school + eta_ch4.very.good_oplcat.vmbo*oplcat_first.vmbo + eta_ch4.very.good_oplcat.wo*oplcat_first.wo + eta_ch4.very.good_employment.homemaker*employment_first.homemaker + eta_ch4.very.good_employment.retired*employment_first.retired + eta_ch4.very.good_employment.student*employment_first.student + eta_ch4.very.good_employment.unable.to.work*employment_first.unable.to.work + eta_ch4.very.good_employment.unemployed*employment_first.unemployed
bmi_18.normal.weight ~ alpha_bmi.normal.weight_18*1 + eta_bmi.normal.weight_y1*mhi5_17 + eta_bmi.normal.weight_y2*mhi5_16 + eta_bmi.normal.weight_y3*mhi5_15 + eta_bmi.normal.weight_x0*cs104_18 + eta_bmi.normal.weight_x1*cs104_17 + eta_bmi.normal.weight_leeftijd.18.24*leeftijd_first.18.24 + eta_bmi.normal.weight_leeftijd.25.39*leeftijd_first.25.39 + eta_bmi.normal.weight_leeftijd.40.66*leeftijd_first.40.66 + eta_bmi.normal.weight_leeftijd.over.67*leeftijd_first.over.67 + eta_bmi.normal.weight_nettohh_f.under.15k*nettohh_f_first.under.15k + eta_bmi.normal.weight_nettohh_f.over.50k*nettohh_f_first.over.50k + eta_bmi.normal.weight_herkomstgroep.first.w*herkomstgroep_first.first.w + eta_bmi.normal.weight_herkomstgroep.first.nonw*herkomstgroep_first.first.nonw + eta_bmi.normal.weight_herkomstgroep.second.w*herkomstgroep_first.second.w + eta_bmi.normal.weight_herkomstgroep.second.nonw*herkomstgroep_first.second.nonw + eta_bmi.normal.weight_geslacht.male*geslacht_first.male + eta_bmi.normal.weight_burgstat.married*burgstat_first.married + eta_bmi.normal.weight_burgstat.never.been.married*burgstat_first.never.been.married + eta_bmi.normal.weight_burgstat.separated*burgstat_first.separated + eta_bmi.normal.weight_burgstat.widow.or.widower*burgstat_first.widow.or.widower + eta_bmi.normal.weight_oplcat.hbo*oplcat_first.hbo + eta_bmi.normal.weight_oplcat.mbo*oplcat_first.mbo + eta_bmi.normal.weight_oplcat.primary.school*oplcat_first.primary.school + eta_bmi.normal.weight_oplcat.vmbo*oplcat_first.vmbo + eta_bmi.normal.weight_oplcat.wo*oplcat_first.wo + eta_bmi.normal.weight_employment.homemaker*employment_first.homemaker + eta_bmi.normal.weight_employment.retired*employment_first.retired + eta_bmi.normal.weight_employment.student*employment_first.student + eta_bmi.normal.weight_employment.unable.to.work*employment_first.unable.to.work + eta_bmi.normal.weight_employment.unemployed*employment_first.unemployed
bmi_18.overweight ~ alpha_bmi.overweight_18*1 + eta_bmi.overweight_y1*mhi5_17 + eta_bmi.overweight_y2*mhi5_16 + eta_bmi.overweight_y3*mhi5_15 + eta_bmi.overweight_x0*cs104_18 + eta_bmi.overweight_x1*cs104_17 + eta_bmi.overweight_leeftijd.18.24*leeftijd_first.18.24 + eta_bmi.overweight_leeftijd.25.39*leeftijd_first.25.39 + eta_bmi.overweight_leeftijd.40.66*leeftijd_first.40.66 + eta_bmi.overweight_leeftijd.over.67*leeftijd_first.over.67 + eta_bmi.overweight_nettohh_f.under.15k*nettohh_f_first.under.15k + eta_bmi.overweight_nettohh_f.over.50k*nettohh_f_first.over.50k + eta_bmi.overweight_herkomstgroep.first.w*herkomstgroep_first.first.w + eta_bmi.overweight_herkomstgroep.first.nonw*herkomstgroep_first.first.nonw + eta_bmi.overweight_herkomstgroep.second.w*herkomstgroep_first.second.w + eta_bmi.overweight_herkomstgroep.second.nonw*herkomstgroep_first.second.nonw + eta_bmi.overweight_geslacht.male*geslacht_first.male + eta_bmi.overweight_burgstat.married*burgstat_first.married + eta_bmi.overweight_burgstat.never.been.married*burgstat_first.never.been.married + eta_bmi.overweight_burgstat.separated*burgstat_first.separated + eta_bmi.overweight_burgstat.widow.or.widower*burgstat_first.widow.or.widower + eta_bmi.overweight_oplcat.hbo*oplcat_first.hbo + eta_bmi.overweight_oplcat.mbo*oplcat_first.mbo + eta_bmi.overweight_oplcat.primary.school*oplcat_first.primary.school + eta_bmi.overweight_oplcat.vmbo*oplcat_first.vmbo + eta_bmi.overweight_oplcat.wo*oplcat_first.wo + eta_bmi.overweight_employment.homemaker*employment_first.homemaker + eta_bmi.overweight_employment.retired*employment_first.retired + eta_bmi.overweight_employment.student*employment_first.student + eta_bmi.overweight_employment.unable.to.work*employment_first.unable.to.work + eta_bmi.overweight_employment.unemployed*employment_first.unemployed
bmi_18.obese ~ alpha_bmi.obese_18*1 + eta_bmi.obese_y1*mhi5_17 + eta_bmi.obese_y2*mhi5_16 + eta_bmi.obese_y3*mhi5_15 + eta_bmi.obese_x0*cs104_18 + eta_bmi.obese_x1*cs104_17 + eta_bmi.obese_leeftijd.18.24*leeftijd_first.18.24 + eta_bmi.obese_leeftijd.25.39*leeftijd_first.25.39 + eta_bmi.obese_leeftijd.40.66*leeftijd_first.40.66 + eta_bmi.obese_leeftijd.over.67*leeftijd_first.over.67 + eta_bmi.obese_nettohh_f.under.15k*nettohh_f_first.under.15k + eta_bmi.obese_nettohh_f.over.50k*nettohh_f_first.over.50k + eta_bmi.obese_herkomstgroep.first.w*herkomstgroep_first.first.w + eta_bmi.obese_herkomstgroep.first.nonw*herkomstgroep_first.first.nonw + eta_bmi.obese_herkomstgroep.second.w*herkomstgroep_first.second.w + eta_bmi.obese_herkomstgroep.second.nonw*herkomstgroep_first.second.nonw + eta_bmi.obese_geslacht.male*geslacht_first.male + eta_bmi.obese_burgstat.married*burgstat_first.married + eta_bmi.obese_burgstat.never.been.married*burgstat_first.never.been.married + eta_bmi.obese_burgstat.separated*burgstat_first.separated + eta_bmi.obese_burgstat.widow.or.widower*burgstat_first.widow.or.widower + eta_bmi.obese_oplcat.hbo*oplcat_first.hbo + eta_bmi.obese_oplcat.mbo*oplcat_first.mbo + eta_bmi.obese_oplcat.primary.school*oplcat_first.primary.school + eta_bmi.obese_oplcat.vmbo*oplcat_first.vmbo + eta_bmi.obese_oplcat.wo*oplcat_first.wo + eta_bmi.obese_employment.homemaker*employment_first.homemaker + eta_bmi.obese_employment.retired*employment_first.retired + eta_bmi.obese_employment.student*employment_first.student + eta_bmi.obese_employment.unable.to.work*employment_first.unable.to.work + eta_bmi.obese_employment.unemployed*employment_first.unemployed
ch98_18 ~ alpha_ch98_18*1 + eta_ch98_y1*mhi5_17 + eta_ch98_y2*mhi5_16 + eta_ch98_y3*mhi5_15 + eta_ch98_x0*cs104_18 + eta_ch98_x1*cs104_17 + eta_ch98_leeftijd.18.24*leeftijd_first.18.24 + eta_ch98_leeftijd.25.39*leeftijd_first.25.39 + eta_ch98_leeftijd.40.66*leeftijd_first.40.66 + eta_ch98_leeftijd.over.67*leeftijd_first.over.67 + eta_ch98_nettohh_f.under.15k*nettohh_f_first.under.15k + eta_ch98_nettohh_f.over.50k*nettohh_f_first.over.50k + eta_ch98_herkomstgroep.first.w*herkomstgroep_first.first.w + eta_ch98_herkomstgroep.first.nonw*herkomstgroep_first.first.nonw + eta_ch98_herkomstgroep.second.w*herkomstgroep_first.second.w + eta_ch98_herkomstgroep.second.nonw*herkomstgroep_first.second.nonw + eta_ch98_geslacht.male*geslacht_first.male + eta_ch98_burgstat.married*burgstat_first.married + eta_ch98_burgstat.never.been.married*burgstat_first.never.been.married + eta_ch98_burgstat.separated*burgstat_first.separated + eta_ch98_burgstat.widow.or.widower*burgstat_first.widow.or.widower + eta_ch98_oplcat.hbo*oplcat_first.hbo + eta_ch98_oplcat.mbo*oplcat_first.mbo + eta_ch98_oplcat.primary.school*oplcat_first.primary.school + eta_ch98_oplcat.vmbo*oplcat_first.vmbo + eta_ch98_oplcat.wo*oplcat_first.wo + eta_ch98_employment.homemaker*employment_first.homemaker + eta_ch98_employment.retired*employment_first.retired + eta_ch98_employment.student*employment_first.student + eta_ch98_employment.unable.to.work*employment_first.unable.to.work + eta_ch98_employment.unemployed*employment_first.unemployed
mhi5_19 ~ alpha_mhi5_19*1 + rho1*mhi5_18 + rho2*mhi5_17 + rho3*mhi5_16 + beta0_cs104*cs104_19 + beta1_cs104*cs104_18 + zeta_ch4.good*ch4_19.good + zeta_ch4.moderate*ch4_19.moderate + zeta_ch4.poor*ch4_19.poor + zeta_ch4.very.good*ch4_19.very.good + zeta_bmi.normal.weight*bmi_19.normal.weight + zeta_bmi.overweight*bmi_19.overweight + zeta_bmi.obese*bmi_19.obese + zeta_ch98*ch98_19 + delta_leeftijd.18.24*leeftijd_first.18.24 + delta_leeftijd.25.39*leeftijd_first.25.39 + delta_leeftijd.40.66*leeftijd_first.40.66 + delta_leeftijd.over.67*leeftijd_first.over.67 + delta_nettohh_f.under.15k*nettohh_f_first.under.15k + delta_nettohh_f.over.50k*nettohh_f_first.over.50k + delta_herkomstgroep.first.w*herkomstgroep_first.first.w + delta_herkomstgroep.first.nonw*herkomstgroep_first.first.nonw + delta_herkomstgroep.second.w*herkomstgroep_first.second.w + delta_herkomstgroep.second.nonw*herkomstgroep_first.second.nonw + delta_geslacht.male*geslacht_first.male + delta_burgstat.married*burgstat_first.married + delta_burgstat.never.been.married*burgstat_first.never.been.married + delta_burgstat.separated*burgstat_first.separated + delta_burgstat.widow.or.widower*burgstat_first.widow.or.widower + delta_oplcat.hbo*oplcat_first.hbo + delta_oplcat.mbo*oplcat_first.mbo + delta_oplcat.primary.school*oplcat_first.primary.school + delta_oplcat.vmbo*oplcat_first.vmbo + delta_oplcat.wo*oplcat_first.wo + delta_employment.homemaker*employment_first.homemaker + delta_employment.retired*employment_first.retired + delta_employment.student*employment_first.student + delta_employment.unable.to.work*employment_first.unable.to.work + delta_employment.unemployed*employment_first.unemployed
ch4_19.good ~ alpha_ch4.good_19*1 + eta_ch4.good_y1*mhi5_18 + eta_ch4.good_y2*mhi5_17 + eta_ch4.good_y3*mhi5_16 + eta_ch4.good_x0*cs104_19 + eta_ch4.good_x1*cs104_18 + eta_ch4.good_leeftijd.18.24*leeftijd_first.18.24 + eta_ch4.good_leeftijd.25.39*leeftijd_first.25.39 + eta_ch4.good_leeftijd.40.66*leeftijd_first.40.66 + eta_ch4.good_leeftijd.over.67*leeftijd_first.over.67 + eta_ch4.good_nettohh_f.under.15k*nettohh_f_first.under.15k + eta_ch4.good_nettohh_f.over.50k*nettohh_f_first.over.50k + eta_ch4.good_herkomstgroep.first.w*herkomstgroep_first.first.w + eta_ch4.good_herkomstgroep.first.nonw*herkomstgroep_first.first.nonw + eta_ch4.good_herkomstgroep.second.w*herkomstgroep_first.second.w + eta_ch4.good_herkomstgroep.second.nonw*herkomstgroep_first.second.nonw + eta_ch4.good_geslacht.male*geslacht_first.male + eta_ch4.good_burgstat.married*burgstat_first.married + eta_ch4.good_burgstat.never.been.married*burgstat_first.never.been.married + eta_ch4.good_burgstat.separated*burgstat_first.separated + eta_ch4.good_burgstat.widow.or.widower*burgstat_first.widow.or.widower + eta_ch4.good_oplcat.hbo*oplcat_first.hbo + eta_ch4.good_oplcat.mbo*oplcat_first.mbo + eta_ch4.good_oplcat.primary.school*oplcat_first.primary.school + eta_ch4.good_oplcat.vmbo*oplcat_first.vmbo + eta_ch4.good_oplcat.wo*oplcat_first.wo + eta_ch4.good_employment.homemaker*employment_first.homemaker + eta_ch4.good_employment.retired*employment_first.retired + eta_ch4.good_employment.student*employment_first.student + eta_ch4.good_employment.unable.to.work*employment_first.unable.to.work + eta_ch4.good_employment.unemployed*employment_first.unemployed
ch4_19.moderate ~ alpha_ch4.moderate_19*1 + eta_ch4.moderate_y1*mhi5_18 + eta_ch4.moderate_y2*mhi5_17 + eta_ch4.moderate_y3*mhi5_16 + eta_ch4.moderate_x0*cs104_19 + eta_ch4.moderate_x1*cs104_18 + eta_ch4.moderate_leeftijd.18.24*leeftijd_first.18.24 + eta_ch4.moderate_leeftijd.25.39*leeftijd_first.25.39 + eta_ch4.moderate_leeftijd.40.66*leeftijd_first.40.66 + eta_ch4.moderate_leeftijd.over.67*leeftijd_first.over.67 + eta_ch4.moderate_nettohh_f.under.15k*nettohh_f_first.under.15k + eta_ch4.moderate_nettohh_f.over.50k*nettohh_f_first.over.50k + eta_ch4.moderate_herkomstgroep.first.w*herkomstgroep_first.first.w + eta_ch4.moderate_herkomstgroep.first.nonw*herkomstgroep_first.first.nonw + eta_ch4.moderate_herkomstgroep.second.w*herkomstgroep_first.second.w + eta_ch4.moderate_herkomstgroep.second.nonw*herkomstgroep_first.second.nonw + eta_ch4.moderate_geslacht.male*geslacht_first.male + eta_ch4.moderate_burgstat.married*burgstat_first.married + eta_ch4.moderate_burgstat.never.been.married*burgstat_first.never.been.married + eta_ch4.moderate_burgstat.separated*burgstat_first.separated + eta_ch4.moderate_burgstat.widow.or.widower*burgstat_first.widow.or.widower + eta_ch4.moderate_oplcat.hbo*oplcat_first.hbo + eta_ch4.moderate_oplcat.mbo*oplcat_first.mbo + eta_ch4.moderate_oplcat.primary.school*oplcat_first.primary.school + eta_ch4.moderate_oplcat.vmbo*oplcat_first.vmbo + eta_ch4.moderate_oplcat.wo*oplcat_first.wo + eta_ch4.moderate_employment.homemaker*employment_first.homemaker + eta_ch4.moderate_employment.retired*employment_first.retired + eta_ch4.moderate_employment.student*employment_first.student + eta_ch4.moderate_employment.unable.to.work*employment_first.unable.to.work + eta_ch4.moderate_employment.unemployed*employment_first.unemployed
ch4_19.poor ~ alpha_ch4.poor_19*1 + eta_ch4.poor_y1*mhi5_18 + eta_ch4.poor_y2*mhi5_17 + eta_ch4.poor_y3*mhi5_16 + eta_ch4.poor_x0*cs104_19 + eta_ch4.poor_x1*cs104_18 + eta_ch4.poor_leeftijd.18.24*leeftijd_first.18.24 + eta_ch4.poor_leeftijd.25.39*leeftijd_first.25.39 + eta_ch4.poor_leeftijd.40.66*leeftijd_first.40.66 + eta_ch4.poor_leeftijd.over.67*leeftijd_first.over.67 + eta_ch4.poor_nettohh_f.under.15k*nettohh_f_first.under.15k + eta_ch4.poor_nettohh_f.over.50k*nettohh_f_first.over.50k + eta_ch4.poor_herkomstgroep.first.w*herkomstgroep_first.first.w + eta_ch4.poor_herkomstgroep.first.nonw*herkomstgroep_first.first.nonw + eta_ch4.poor_herkomstgroep.second.w*herkomstgroep_first.second.w + eta_ch4.poor_herkomstgroep.second.nonw*herkomstgroep_first.second.nonw + eta_ch4.poor_geslacht.male*geslacht_first.male + eta_ch4.poor_burgstat.married*burgstat_first.married + eta_ch4.poor_burgstat.never.been.married*burgstat_first.never.been.married + eta_ch4.poor_burgstat.separated*burgstat_first.separated + eta_ch4.poor_burgstat.widow.or.widower*burgstat_first.widow.or.widower + eta_ch4.poor_oplcat.hbo*oplcat_first.hbo + eta_ch4.poor_oplcat.mbo*oplcat_first.mbo + eta_ch4.poor_oplcat.primary.school*oplcat_first.primary.school + eta_ch4.poor_oplcat.vmbo*oplcat_first.vmbo + eta_ch4.poor_oplcat.wo*oplcat_first.wo + eta_ch4.poor_employment.homemaker*employment_first.homemaker + eta_ch4.poor_employment.retired*employment_first.retired + eta_ch4.poor_employment.student*employment_first.student + eta_ch4.poor_employment.unable.to.work*employment_first.unable.to.work + eta_ch4.poor_employment.unemployed*employment_first.unemployed
ch4_19.very.good ~ alpha_ch4.very.good_19*1 + eta_ch4.very.good_y1*mhi5_18 + eta_ch4.very.good_y2*mhi5_17 + eta_ch4.very.good_y3*mhi5_16 + eta_ch4.very.good_x0*cs104_19 + eta_ch4.very.good_x1*cs104_18 + eta_ch4.very.good_leeftijd.18.24*leeftijd_first.18.24 + eta_ch4.very.good_leeftijd.25.39*leeftijd_first.25.39 + eta_ch4.very.good_leeftijd.40.66*leeftijd_first.40.66 + eta_ch4.very.good_leeftijd.over.67*leeftijd_first.over.67 + eta_ch4.very.good_nettohh_f.under.15k*nettohh_f_first.under.15k + eta_ch4.very.good_nettohh_f.over.50k*nettohh_f_first.over.50k + eta_ch4.very.good_herkomstgroep.first.w*herkomstgroep_first.first.w + eta_ch4.very.good_herkomstgroep.first.nonw*herkomstgroep_first.first.nonw + eta_ch4.very.good_herkomstgroep.second.w*herkomstgroep_first.second.w + eta_ch4.very.good_herkomstgroep.second.nonw*herkomstgroep_first.second.nonw + eta_ch4.very.good_geslacht.male*geslacht_first.male + eta_ch4.very.good_burgstat.married*burgstat_first.married + eta_ch4.very.good_burgstat.never.been.married*burgstat_first.never.been.married + eta_ch4.very.good_burgstat.separated*burgstat_first.separated + eta_ch4.very.good_burgstat.widow.or.widower*burgstat_first.widow.or.widower + eta_ch4.very.good_oplcat.hbo*oplcat_first.hbo + eta_ch4.very.good_oplcat.mbo*oplcat_first.mbo + eta_ch4.very.good_oplcat.primary.school*oplcat_first.primary.school + eta_ch4.very.good_oplcat.vmbo*oplcat_first.vmbo + eta_ch4.very.good_oplcat.wo*oplcat_first.wo + eta_ch4.very.good_employment.homemaker*employment_first.homemaker + eta_ch4.very.good_employment.retired*employment_first.retired + eta_ch4.very.good_employment.student*employment_first.student + eta_ch4.very.good_employment.unable.to.work*employment_first.unable.to.work + eta_ch4.very.good_employment.unemployed*employment_first.unemployed
bmi_19.normal.weight ~ alpha_bmi.normal.weight_19*1 + eta_bmi.normal.weight_y1*mhi5_18 + eta_bmi.normal.weight_y2*mhi5_17 + eta_bmi.normal.weight_y3*mhi5_16 + eta_bmi.normal.weight_x0*cs104_19 + eta_bmi.normal.weight_x1*cs104_18 + eta_bmi.normal.weight_leeftijd.18.24*leeftijd_first.18.24 + eta_bmi.normal.weight_leeftijd.25.39*leeftijd_first.25.39 + eta_bmi.normal.weight_leeftijd.40.66*leeftijd_first.40.66 + eta_bmi.normal.weight_leeftijd.over.67*leeftijd_first.over.67 + eta_bmi.normal.weight_nettohh_f.under.15k*nettohh_f_first.under.15k + eta_bmi.normal.weight_nettohh_f.over.50k*nettohh_f_first.over.50k + eta_bmi.normal.weight_herkomstgroep.first.w*herkomstgroep_first.first.w + eta_bmi.normal.weight_herkomstgroep.first.nonw*herkomstgroep_first.first.nonw + eta_bmi.normal.weight_herkomstgroep.second.w*herkomstgroep_first.second.w + eta_bmi.normal.weight_herkomstgroep.second.nonw*herkomstgroep_first.second.nonw + eta_bmi.normal.weight_geslacht.male*geslacht_first.male + eta_bmi.normal.weight_burgstat.married*burgstat_first.married + eta_bmi.normal.weight_burgstat.never.been.married*burgstat_first.never.been.married + eta_bmi.normal.weight_burgstat.separated*burgstat_first.separated + eta_bmi.normal.weight_burgstat.widow.or.widower*burgstat_first.widow.or.widower + eta_bmi.normal.weight_oplcat.hbo*oplcat_first.hbo + eta_bmi.normal.weight_oplcat.mbo*oplcat_first.mbo + eta_bmi.normal.weight_oplcat.primary.school*oplcat_first.primary.school + eta_bmi.normal.weight_oplcat.vmbo*oplcat_first.vmbo + eta_bmi.normal.weight_oplcat.wo*oplcat_first.wo + eta_bmi.normal.weight_employment.homemaker*employment_first.homemaker + eta_bmi.normal.weight_employment.retired*employment_first.retired + eta_bmi.normal.weight_employment.student*employment_first.student + eta_bmi.normal.weight_employment.unable.to.work*employment_first.unable.to.work + eta_bmi.normal.weight_employment.unemployed*employment_first.unemployed
bmi_19.overweight ~ alpha_bmi.overweight_19*1 + eta_bmi.overweight_y1*mhi5_18 + eta_bmi.overweight_y2*mhi5_17 + eta_bmi.overweight_y3*mhi5_16 + eta_bmi.overweight_x0*cs104_19 + eta_bmi.overweight_x1*cs104_18 + eta_bmi.overweight_leeftijd.18.24*leeftijd_first.18.24 + eta_bmi.overweight_leeftijd.25.39*leeftijd_first.25.39 + eta_bmi.overweight_leeftijd.40.66*leeftijd_first.40.66 + eta_bmi.overweight_leeftijd.over.67*leeftijd_first.over.67 + eta_bmi.overweight_nettohh_f.under.15k*nettohh_f_first.under.15k + eta_bmi.overweight_nettohh_f.over.50k*nettohh_f_first.over.50k + eta_bmi.overweight_herkomstgroep.first.w*herkomstgroep_first.first.w + eta_bmi.overweight_herkomstgroep.first.nonw*herkomstgroep_first.first.nonw + eta_bmi.overweight_herkomstgroep.second.w*herkomstgroep_first.second.w + eta_bmi.overweight_herkomstgroep.second.nonw*herkomstgroep_first.second.nonw + eta_bmi.overweight_geslacht.male*geslacht_first.male + eta_bmi.overweight_burgstat.married*burgstat_first.married + eta_bmi.overweight_burgstat.never.been.married*burgstat_first.never.been.married + eta_bmi.overweight_burgstat.separated*burgstat_first.separated + eta_bmi.overweight_burgstat.widow.or.widower*burgstat_first.widow.or.widower + eta_bmi.overweight_oplcat.hbo*oplcat_first.hbo + eta_bmi.overweight_oplcat.mbo*oplcat_first.mbo + eta_bmi.overweight_oplcat.primary.school*oplcat_first.primary.school + eta_bmi.overweight_oplcat.vmbo*oplcat_first.vmbo + eta_bmi.overweight_oplcat.wo*oplcat_first.wo + eta_bmi.overweight_employment.homemaker*employment_first.homemaker + eta_bmi.overweight_employment.retired*employment_first.retired + eta_bmi.overweight_employment.student*employment_first.student + eta_bmi.overweight_employment.unable.to.work*employment_first.unable.to.work + eta_bmi.overweight_employment.unemployed*employment_first.unemployed
bmi_19.obese ~ alpha_bmi.obese_19*1 + eta_bmi.obese_y1*mhi5_18 + eta_bmi.obese_y2*mhi5_17 + eta_bmi.obese_y3*mhi5_16 + eta_bmi.obese_x0*cs104_19 + eta_bmi.obese_x1*cs104_18 + eta_bmi.obese_leeftijd.18.24*leeftijd_first.18.24 + eta_bmi.obese_leeftijd.25.39*leeftijd_first.25.39 + eta_bmi.obese_leeftijd.40.66*leeftijd_first.40.66 + eta_bmi.obese_leeftijd.over.67*leeftijd_first.over.67 + eta_bmi.obese_nettohh_f.under.15k*nettohh_f_first.under.15k + eta_bmi.obese_nettohh_f.over.50k*nettohh_f_first.over.50k + eta_bmi.obese_herkomstgroep.first.w*herkomstgroep_first.first.w + eta_bmi.obese_herkomstgroep.first.nonw*herkomstgroep_first.first.nonw + eta_bmi.obese_herkomstgroep.second.w*herkomstgroep_first.second.w + eta_bmi.obese_herkomstgroep.second.nonw*herkomstgroep_first.second.nonw + eta_bmi.obese_geslacht.male*geslacht_first.male + eta_bmi.obese_burgstat.married*burgstat_first.married + eta_bmi.obese_burgstat.never.been.married*burgstat_first.never.been.married + eta_bmi.obese_burgstat.separated*burgstat_first.separated + eta_bmi.obese_burgstat.widow.or.widower*burgstat_first.widow.or.widower + eta_bmi.obese_oplcat.hbo*oplcat_first.hbo + eta_bmi.obese_oplcat.mbo*oplcat_first.mbo + eta_bmi.obese_oplcat.primary.school*oplcat_first.primary.school + eta_bmi.obese_oplcat.vmbo*oplcat_first.vmbo + eta_bmi.obese_oplcat.wo*oplcat_first.wo + eta_bmi.obese_employment.homemaker*employment_first.homemaker + eta_bmi.obese_employment.retired*employment_first.retired + eta_bmi.obese_employment.student*employment_first.student + eta_bmi.obese_employment.unable.to.work*employment_first.unable.to.work + eta_bmi.obese_employment.unemployed*employment_first.unemployed
ch98_19 ~ alpha_ch98_19*1 + eta_ch98_y1*mhi5_18 + eta_ch98_y2*mhi5_17 + eta_ch98_y3*mhi5_16 + eta_ch98_x0*cs104_19 + eta_ch98_x1*cs104_18 + eta_ch98_leeftijd.18.24*leeftijd_first.18.24 + eta_ch98_leeftijd.25.39*leeftijd_first.25.39 + eta_ch98_leeftijd.40.66*leeftijd_first.40.66 + eta_ch98_leeftijd.over.67*leeftijd_first.over.67 + eta_ch98_nettohh_f.under.15k*nettohh_f_first.under.15k + eta_ch98_nettohh_f.over.50k*nettohh_f_first.over.50k + eta_ch98_herkomstgroep.first.w*herkomstgroep_first.first.w + eta_ch98_herkomstgroep.first.nonw*herkomstgroep_first.first.nonw + eta_ch98_herkomstgroep.second.w*herkomstgroep_first.second.w + eta_ch98_herkomstgroep.second.nonw*herkomstgroep_first.second.nonw + eta_ch98_geslacht.male*geslacht_first.male + eta_ch98_burgstat.married*burgstat_first.married + eta_ch98_burgstat.never.been.married*burgstat_first.never.been.married + eta_ch98_burgstat.separated*burgstat_first.separated + eta_ch98_burgstat.widow.or.widower*burgstat_first.widow.or.widower + eta_ch98_oplcat.hbo*oplcat_first.hbo + eta_ch98_oplcat.mbo*oplcat_first.mbo + eta_ch98_oplcat.primary.school*oplcat_first.primary.school + eta_ch98_oplcat.vmbo*oplcat_first.vmbo + eta_ch98_oplcat.wo*oplcat_first.wo + eta_ch98_employment.homemaker*employment_first.homemaker + eta_ch98_employment.retired*employment_first.retired + eta_ch98_employment.student*employment_first.student + eta_ch98_employment.unable.to.work*employment_first.unable.to.work + eta_ch98_employment.unemployed*employment_first.unemployed
mhi5_20 ~ alpha_mhi5_20*1 + rho1*mhi5_19 + rho2*mhi5_18 + rho3*mhi5_17 + beta0_cs104*cs104_20 + beta1_cs104*cs104_19 + zeta_ch4.good*ch4_20.good + zeta_ch4.moderate*ch4_20.moderate + zeta_ch4.poor*ch4_20.poor + zeta_ch4.very.good*ch4_20.very.good + zeta_bmi.normal.weight*bmi_20.normal.weight + zeta_bmi.overweight*bmi_20.overweight + zeta_bmi.obese*bmi_20.obese + zeta_ch98*ch98_20 + delta_leeftijd.18.24*leeftijd_first.18.24 + delta_leeftijd.25.39*leeftijd_first.25.39 + delta_leeftijd.40.66*leeftijd_first.40.66 + delta_leeftijd.over.67*leeftijd_first.over.67 + delta_nettohh_f.under.15k*nettohh_f_first.under.15k + delta_nettohh_f.over.50k*nettohh_f_first.over.50k + delta_herkomstgroep.first.w*herkomstgroep_first.first.w + delta_herkomstgroep.first.nonw*herkomstgroep_first.first.nonw + delta_herkomstgroep.second.w*herkomstgroep_first.second.w + delta_herkomstgroep.second.nonw*herkomstgroep_first.second.nonw + delta_geslacht.male*geslacht_first.male + delta_burgstat.married*burgstat_first.married + delta_burgstat.never.been.married*burgstat_first.never.been.married + delta_burgstat.separated*burgstat_first.separated + delta_burgstat.widow.or.widower*burgstat_first.widow.or.widower + delta_oplcat.hbo*oplcat_first.hbo + delta_oplcat.mbo*oplcat_first.mbo + delta_oplcat.primary.school*oplcat_first.primary.school + delta_oplcat.vmbo*oplcat_first.vmbo + delta_oplcat.wo*oplcat_first.wo + delta_employment.homemaker*employment_first.homemaker + delta_employment.retired*employment_first.retired + delta_employment.student*employment_first.student + delta_employment.unable.to.work*employment_first.unable.to.work + delta_employment.unemployed*employment_first.unemployed
ch4_20.good ~ alpha_ch4.good_20*1 + eta_ch4.good_y1*mhi5_19 + eta_ch4.good_y2*mhi5_18 + eta_ch4.good_y3*mhi5_17 + eta_ch4.good_x0*cs104_20 + eta_ch4.good_x1*cs104_19 + eta_ch4.good_leeftijd.18.24*leeftijd_first.18.24 + eta_ch4.good_leeftijd.25.39*leeftijd_first.25.39 + eta_ch4.good_leeftijd.40.66*leeftijd_first.40.66 + eta_ch4.good_leeftijd.over.67*leeftijd_first.over.67 + eta_ch4.good_nettohh_f.under.15k*nettohh_f_first.under.15k + eta_ch4.good_nettohh_f.over.50k*nettohh_f_first.over.50k + eta_ch4.good_herkomstgroep.first.w*herkomstgroep_first.first.w + eta_ch4.good_herkomstgroep.first.nonw*herkomstgroep_first.first.nonw + eta_ch4.good_herkomstgroep.second.w*herkomstgroep_first.second.w + eta_ch4.good_herkomstgroep.second.nonw*herkomstgroep_first.second.nonw + eta_ch4.good_geslacht.male*geslacht_first.male + eta_ch4.good_burgstat.married*burgstat_first.married + eta_ch4.good_burgstat.never.been.married*burgstat_first.never.been.married + eta_ch4.good_burgstat.separated*burgstat_first.separated + eta_ch4.good_burgstat.widow.or.widower*burgstat_first.widow.or.widower + eta_ch4.good_oplcat.hbo*oplcat_first.hbo + eta_ch4.good_oplcat.mbo*oplcat_first.mbo + eta_ch4.good_oplcat.primary.school*oplcat_first.primary.school + eta_ch4.good_oplcat.vmbo*oplcat_first.vmbo + eta_ch4.good_oplcat.wo*oplcat_first.wo + eta_ch4.good_employment.homemaker*employment_first.homemaker + eta_ch4.good_employment.retired*employment_first.retired + eta_ch4.good_employment.student*employment_first.student + eta_ch4.good_employment.unable.to.work*employment_first.unable.to.work + eta_ch4.good_employment.unemployed*employment_first.unemployed
ch4_20.moderate ~ alpha_ch4.moderate_20*1 + eta_ch4.moderate_y1*mhi5_19 + eta_ch4.moderate_y2*mhi5_18 + eta_ch4.moderate_y3*mhi5_17 + eta_ch4.moderate_x0*cs104_20 + eta_ch4.moderate_x1*cs104_19 + eta_ch4.moderate_leeftijd.18.24*leeftijd_first.18.24 + eta_ch4.moderate_leeftijd.25.39*leeftijd_first.25.39 + eta_ch4.moderate_leeftijd.40.66*leeftijd_first.40.66 + eta_ch4.moderate_leeftijd.over.67*leeftijd_first.over.67 + eta_ch4.moderate_nettohh_f.under.15k*nettohh_f_first.under.15k + eta_ch4.moderate_nettohh_f.over.50k*nettohh_f_first.over.50k + eta_ch4.moderate_herkomstgroep.first.w*herkomstgroep_first.first.w + eta_ch4.moderate_herkomstgroep.first.nonw*herkomstgroep_first.first.nonw + eta_ch4.moderate_herkomstgroep.second.w*herkomstgroep_first.second.w + eta_ch4.moderate_herkomstgroep.second.nonw*herkomstgroep_first.second.nonw + eta_ch4.moderate_geslacht.male*geslacht_first.male + eta_ch4.moderate_burgstat.married*burgstat_first.married + eta_ch4.moderate_burgstat.never.been.married*burgstat_first.never.been.married + eta_ch4.moderate_burgstat.separated*burgstat_first.separated + eta_ch4.moderate_burgstat.widow.or.widower*burgstat_first.widow.or.widower + eta_ch4.moderate_oplcat.hbo*oplcat_first.hbo + eta_ch4.moderate_oplcat.mbo*oplcat_first.mbo + eta_ch4.moderate_oplcat.primary.school*oplcat_first.primary.school + eta_ch4.moderate_oplcat.vmbo*oplcat_first.vmbo + eta_ch4.moderate_oplcat.wo*oplcat_first.wo + eta_ch4.moderate_employment.homemaker*employment_first.homemaker + eta_ch4.moderate_employment.retired*employment_first.retired + eta_ch4.moderate_employment.student*employment_first.student + eta_ch4.moderate_employment.unable.to.work*employment_first.unable.to.work + eta_ch4.moderate_employment.unemployed*employment_first.unemployed
ch4_20.poor ~ alpha_ch4.poor_20*1 + eta_ch4.poor_y1*mhi5_19 + eta_ch4.poor_y2*mhi5_18 + eta_ch4.poor_y3*mhi5_17 + eta_ch4.poor_x0*cs104_20 + eta_ch4.poor_x1*cs104_19 + eta_ch4.poor_leeftijd.18.24*leeftijd_first.18.24 + eta_ch4.poor_leeftijd.25.39*leeftijd_first.25.39 + eta_ch4.poor_leeftijd.40.66*leeftijd_first.40.66 + eta_ch4.poor_leeftijd.over.67*leeftijd_first.over.67 + eta_ch4.poor_nettohh_f.under.15k*nettohh_f_first.under.15k + eta_ch4.poor_nettohh_f.over.50k*nettohh_f_first.over.50k + eta_ch4.poor_herkomstgroep.first.w*herkomstgroep_first.first.w + eta_ch4.poor_herkomstgroep.first.nonw*herkomstgroep_first.first.nonw + eta_ch4.poor_herkomstgroep.second.w*herkomstgroep_first.second.w + eta_ch4.poor_herkomstgroep.second.nonw*herkomstgroep_first.second.nonw + eta_ch4.poor_geslacht.male*geslacht_first.male + eta_ch4.poor_burgstat.married*burgstat_first.married + eta_ch4.poor_burgstat.never.been.married*burgstat_first.never.been.married + eta_ch4.poor_burgstat.separated*burgstat_first.separated + eta_ch4.poor_burgstat.widow.or.widower*burgstat_first.widow.or.widower + eta_ch4.poor_oplcat.hbo*oplcat_first.hbo + eta_ch4.poor_oplcat.mbo*oplcat_first.mbo + eta_ch4.poor_oplcat.primary.school*oplcat_first.primary.school + eta_ch4.poor_oplcat.vmbo*oplcat_first.vmbo + eta_ch4.poor_oplcat.wo*oplcat_first.wo + eta_ch4.poor_employment.homemaker*employment_first.homemaker + eta_ch4.poor_employment.retired*employment_first.retired + eta_ch4.poor_employment.student*employment_first.student + eta_ch4.poor_employment.unable.to.work*employment_first.unable.to.work + eta_ch4.poor_employment.unemployed*employment_first.unemployed
ch4_20.very.good ~ alpha_ch4.very.good_20*1 + eta_ch4.very.good_y1*mhi5_19 + eta_ch4.very.good_y2*mhi5_18 + eta_ch4.very.good_y3*mhi5_17 + eta_ch4.very.good_x0*cs104_20 + eta_ch4.very.good_x1*cs104_19 + eta_ch4.very.good_leeftijd.18.24*leeftijd_first.18.24 + eta_ch4.very.good_leeftijd.25.39*leeftijd_first.25.39 + eta_ch4.very.good_leeftijd.40.66*leeftijd_first.40.66 + eta_ch4.very.good_leeftijd.over.67*leeftijd_first.over.67 + eta_ch4.very.good_nettohh_f.under.15k*nettohh_f_first.under.15k + eta_ch4.very.good_nettohh_f.over.50k*nettohh_f_first.over.50k + eta_ch4.very.good_herkomstgroep.first.w*herkomstgroep_first.first.w + eta_ch4.very.good_herkomstgroep.first.nonw*herkomstgroep_first.first.nonw + eta_ch4.very.good_herkomstgroep.second.w*herkomstgroep_first.second.w + eta_ch4.very.good_herkomstgroep.second.nonw*herkomstgroep_first.second.nonw + eta_ch4.very.good_geslacht.male*geslacht_first.male + eta_ch4.very.good_burgstat.married*burgstat_first.married + eta_ch4.very.good_burgstat.never.been.married*burgstat_first.never.been.married + eta_ch4.very.good_burgstat.separated*burgstat_first.separated + eta_ch4.very.good_burgstat.widow.or.widower*burgstat_first.widow.or.widower + eta_ch4.very.good_oplcat.hbo*oplcat_first.hbo + eta_ch4.very.good_oplcat.mbo*oplcat_first.mbo + eta_ch4.very.good_oplcat.primary.school*oplcat_first.primary.school + eta_ch4.very.good_oplcat.vmbo*oplcat_first.vmbo + eta_ch4.very.good_oplcat.wo*oplcat_first.wo + eta_ch4.very.good_employment.homemaker*employment_first.homemaker + eta_ch4.very.good_employment.retired*employment_first.retired + eta_ch4.very.good_employment.student*employment_first.student + eta_ch4.very.good_employment.unable.to.work*employment_first.unable.to.work + eta_ch4.very.good_employment.unemployed*employment_first.unemployed
bmi_20.normal.weight ~ alpha_bmi.normal.weight_20*1 + eta_bmi.normal.weight_y1*mhi5_19 + eta_bmi.normal.weight_y2*mhi5_18 + eta_bmi.normal.weight_y3*mhi5_17 + eta_bmi.normal.weight_x0*cs104_20 + eta_bmi.normal.weight_x1*cs104_19 + eta_bmi.normal.weight_leeftijd.18.24*leeftijd_first.18.24 + eta_bmi.normal.weight_leeftijd.25.39*leeftijd_first.25.39 + eta_bmi.normal.weight_leeftijd.40.66*leeftijd_first.40.66 + eta_bmi.normal.weight_leeftijd.over.67*leeftijd_first.over.67 + eta_bmi.normal.weight_nettohh_f.under.15k*nettohh_f_first.under.15k + eta_bmi.normal.weight_nettohh_f.over.50k*nettohh_f_first.over.50k + eta_bmi.normal.weight_herkomstgroep.first.w*herkomstgroep_first.first.w + eta_bmi.normal.weight_herkomstgroep.first.nonw*herkomstgroep_first.first.nonw + eta_bmi.normal.weight_herkomstgroep.second.w*herkomstgroep_first.second.w + eta_bmi.normal.weight_herkomstgroep.second.nonw*herkomstgroep_first.second.nonw + eta_bmi.normal.weight_geslacht.male*geslacht_first.male + eta_bmi.normal.weight_burgstat.married*burgstat_first.married + eta_bmi.normal.weight_burgstat.never.been.married*burgstat_first.never.been.married + eta_bmi.normal.weight_burgstat.separated*burgstat_first.separated + eta_bmi.normal.weight_burgstat.widow.or.widower*burgstat_first.widow.or.widower + eta_bmi.normal.weight_oplcat.hbo*oplcat_first.hbo + eta_bmi.normal.weight_oplcat.mbo*oplcat_first.mbo + eta_bmi.normal.weight_oplcat.primary.school*oplcat_first.primary.school + eta_bmi.normal.weight_oplcat.vmbo*oplcat_first.vmbo + eta_bmi.normal.weight_oplcat.wo*oplcat_first.wo + eta_bmi.normal.weight_employment.homemaker*employment_first.homemaker + eta_bmi.normal.weight_employment.retired*employment_first.retired + eta_bmi.normal.weight_employment.student*employment_first.student + eta_bmi.normal.weight_employment.unable.to.work*employment_first.unable.to.work + eta_bmi.normal.weight_employment.unemployed*employment_first.unemployed
bmi_20.overweight ~ alpha_bmi.overweight_20*1 + eta_bmi.overweight_y1*mhi5_19 + eta_bmi.overweight_y2*mhi5_18 + eta_bmi.overweight_y3*mhi5_17 + eta_bmi.overweight_x0*cs104_20 + eta_bmi.overweight_x1*cs104_19 + eta_bmi.overweight_leeftijd.18.24*leeftijd_first.18.24 + eta_bmi.overweight_leeftijd.25.39*leeftijd_first.25.39 + eta_bmi.overweight_leeftijd.40.66*leeftijd_first.40.66 + eta_bmi.overweight_leeftijd.over.67*leeftijd_first.over.67 + eta_bmi.overweight_nettohh_f.under.15k*nettohh_f_first.under.15k + eta_bmi.overweight_nettohh_f.over.50k*nettohh_f_first.over.50k + eta_bmi.overweight_herkomstgroep.first.w*herkomstgroep_first.first.w + eta_bmi.overweight_herkomstgroep.first.nonw*herkomstgroep_first.first.nonw + eta_bmi.overweight_herkomstgroep.second.w*herkomstgroep_first.second.w + eta_bmi.overweight_herkomstgroep.second.nonw*herkomstgroep_first.second.nonw + eta_bmi.overweight_geslacht.male*geslacht_first.male + eta_bmi.overweight_burgstat.married*burgstat_first.married + eta_bmi.overweight_burgstat.never.been.married*burgstat_first.never.been.married + eta_bmi.overweight_burgstat.separated*burgstat_first.separated + eta_bmi.overweight_burgstat.widow.or.widower*burgstat_first.widow.or.widower + eta_bmi.overweight_oplcat.hbo*oplcat_first.hbo + eta_bmi.overweight_oplcat.mbo*oplcat_first.mbo + eta_bmi.overweight_oplcat.primary.school*oplcat_first.primary.school + eta_bmi.overweight_oplcat.vmbo*oplcat_first.vmbo + eta_bmi.overweight_oplcat.wo*oplcat_first.wo + eta_bmi.overweight_employment.homemaker*employment_first.homemaker + eta_bmi.overweight_employment.retired*employment_first.retired + eta_bmi.overweight_employment.student*employment_first.student + eta_bmi.overweight_employment.unable.to.work*employment_first.unable.to.work + eta_bmi.overweight_employment.unemployed*employment_first.unemployed
bmi_20.obese ~ alpha_bmi.obese_20*1 + eta_bmi.obese_y1*mhi5_19 + eta_bmi.obese_y2*mhi5_18 + eta_bmi.obese_y3*mhi5_17 + eta_bmi.obese_x0*cs104_20 + eta_bmi.obese_x1*cs104_19 + eta_bmi.obese_leeftijd.18.24*leeftijd_first.18.24 + eta_bmi.obese_leeftijd.25.39*leeftijd_first.25.39 + eta_bmi.obese_leeftijd.40.66*leeftijd_first.40.66 + eta_bmi.obese_leeftijd.over.67*leeftijd_first.over.67 + eta_bmi.obese_nettohh_f.under.15k*nettohh_f_first.under.15k + eta_bmi.obese_nettohh_f.over.50k*nettohh_f_first.over.50k + eta_bmi.obese_herkomstgroep.first.w*herkomstgroep_first.first.w + eta_bmi.obese_herkomstgroep.first.nonw*herkomstgroep_first.first.nonw + eta_bmi.obese_herkomstgroep.second.w*herkomstgroep_first.second.w + eta_bmi.obese_herkomstgroep.second.nonw*herkomstgroep_first.second.nonw + eta_bmi.obese_geslacht.male*geslacht_first.male + eta_bmi.obese_burgstat.married*burgstat_first.married + eta_bmi.obese_burgstat.never.been.married*burgstat_first.never.been.married + eta_bmi.obese_burgstat.separated*burgstat_first.separated + eta_bmi.obese_burgstat.widow.or.widower*burgstat_first.widow.or.widower + eta_bmi.obese_oplcat.hbo*oplcat_first.hbo + eta_bmi.obese_oplcat.mbo*oplcat_first.mbo + eta_bmi.obese_oplcat.primary.school*oplcat_first.primary.school + eta_bmi.obese_oplcat.vmbo*oplcat_first.vmbo + eta_bmi.obese_oplcat.wo*oplcat_first.wo + eta_bmi.obese_employment.homemaker*employment_first.homemaker + eta_bmi.obese_employment.retired*employment_first.retired + eta_bmi.obese_employment.student*employment_first.student + eta_bmi.obese_employment.unable.to.work*employment_first.unable.to.work + eta_bmi.obese_employment.unemployed*employment_first.unemployed
ch98_20 ~ alpha_ch98_20*1 + eta_ch98_y1*mhi5_19 + eta_ch98_y2*mhi5_18 + eta_ch98_y3*mhi5_17 + eta_ch98_x0*cs104_20 + eta_ch98_x1*cs104_19 + eta_ch98_leeftijd.18.24*leeftijd_first.18.24 + eta_ch98_leeftijd.25.39*leeftijd_first.25.39 + eta_ch98_leeftijd.40.66*leeftijd_first.40.66 + eta_ch98_leeftijd.over.67*leeftijd_first.over.67 + eta_ch98_nettohh_f.under.15k*nettohh_f_first.under.15k + eta_ch98_nettohh_f.over.50k*nettohh_f_first.over.50k + eta_ch98_herkomstgroep.first.w*herkomstgroep_first.first.w + eta_ch98_herkomstgroep.first.nonw*herkomstgroep_first.first.nonw + eta_ch98_herkomstgroep.second.w*herkomstgroep_first.second.w + eta_ch98_herkomstgroep.second.nonw*herkomstgroep_first.second.nonw + eta_ch98_geslacht.male*geslacht_first.male + eta_ch98_burgstat.married*burgstat_first.married + eta_ch98_burgstat.never.been.married*burgstat_first.never.been.married + eta_ch98_burgstat.separated*burgstat_first.separated + eta_ch98_burgstat.widow.or.widower*burgstat_first.widow.or.widower + eta_ch98_oplcat.hbo*oplcat_first.hbo + eta_ch98_oplcat.mbo*oplcat_first.mbo + eta_ch98_oplcat.primary.school*oplcat_first.primary.school + eta_ch98_oplcat.vmbo*oplcat_first.vmbo + eta_ch98_oplcat.wo*oplcat_first.wo + eta_ch98_employment.homemaker*employment_first.homemaker + eta_ch98_employment.retired*employment_first.retired + eta_ch98_employment.student*employment_first.student + eta_ch98_employment.unable.to.work*employment_first.unable.to.work + eta_ch98_employment.unemployed*employment_first.unemployed
mhi5_21 ~ alpha_mhi5_21*1 + rho1*mhi5_20 + rho2*mhi5_19 + rho3*mhi5_18 + beta0_cs104*cs104_21 + beta1_cs104*cs104_20 + zeta_ch4.good*ch4_21.good + zeta_ch4.moderate*ch4_21.moderate + zeta_ch4.poor*ch4_21.poor + zeta_ch4.very.good*ch4_21.very.good + zeta_bmi.normal.weight*bmi_21.normal.weight + zeta_bmi.overweight*bmi_21.overweight + zeta_bmi.obese*bmi_21.obese + zeta_ch98*ch98_21 + delta_leeftijd.18.24*leeftijd_first.18.24 + delta_leeftijd.25.39*leeftijd_first.25.39 + delta_leeftijd.40.66*leeftijd_first.40.66 + delta_leeftijd.over.67*leeftijd_first.over.67 + delta_nettohh_f.under.15k*nettohh_f_first.under.15k + delta_nettohh_f.over.50k*nettohh_f_first.over.50k + delta_herkomstgroep.first.w*herkomstgroep_first.first.w + delta_herkomstgroep.first.nonw*herkomstgroep_first.first.nonw + delta_herkomstgroep.second.w*herkomstgroep_first.second.w + delta_herkomstgroep.second.nonw*herkomstgroep_first.second.nonw + delta_geslacht.male*geslacht_first.male + delta_burgstat.married*burgstat_first.married + delta_burgstat.never.been.married*burgstat_first.never.been.married + delta_burgstat.separated*burgstat_first.separated + delta_burgstat.widow.or.widower*burgstat_first.widow.or.widower + delta_oplcat.hbo*oplcat_first.hbo + delta_oplcat.mbo*oplcat_first.mbo + delta_oplcat.primary.school*oplcat_first.primary.school + delta_oplcat.vmbo*oplcat_first.vmbo + delta_oplcat.wo*oplcat_first.wo + delta_employment.homemaker*employment_first.homemaker + delta_employment.retired*employment_first.retired + delta_employment.student*employment_first.student + delta_employment.unable.to.work*employment_first.unable.to.work + delta_employment.unemployed*employment_first.unemployed
ch4_21.good ~ alpha_ch4.good_21*1 + eta_ch4.good_y1*mhi5_20 + eta_ch4.good_y2*mhi5_19 + eta_ch4.good_y3*mhi5_18 + eta_ch4.good_x0*cs104_21 + eta_ch4.good_x1*cs104_20 + eta_ch4.good_leeftijd.18.24*leeftijd_first.18.24 + eta_ch4.good_leeftijd.25.39*leeftijd_first.25.39 + eta_ch4.good_leeftijd.40.66*leeftijd_first.40.66 + eta_ch4.good_leeftijd.over.67*leeftijd_first.over.67 + eta_ch4.good_nettohh_f.under.15k*nettohh_f_first.under.15k + eta_ch4.good_nettohh_f.over.50k*nettohh_f_first.over.50k + eta_ch4.good_herkomstgroep.first.w*herkomstgroep_first.first.w + eta_ch4.good_herkomstgroep.first.nonw*herkomstgroep_first.first.nonw + eta_ch4.good_herkomstgroep.second.w*herkomstgroep_first.second.w + eta_ch4.good_herkomstgroep.second.nonw*herkomstgroep_first.second.nonw + eta_ch4.good_geslacht.male*geslacht_first.male + eta_ch4.good_burgstat.married*burgstat_first.married + eta_ch4.good_burgstat.never.been.married*burgstat_first.never.been.married + eta_ch4.good_burgstat.separated*burgstat_first.separated + eta_ch4.good_burgstat.widow.or.widower*burgstat_first.widow.or.widower + eta_ch4.good_oplcat.hbo*oplcat_first.hbo + eta_ch4.good_oplcat.mbo*oplcat_first.mbo + eta_ch4.good_oplcat.primary.school*oplcat_first.primary.school + eta_ch4.good_oplcat.vmbo*oplcat_first.vmbo + eta_ch4.good_oplcat.wo*oplcat_first.wo + eta_ch4.good_employment.homemaker*employment_first.homemaker + eta_ch4.good_employment.retired*employment_first.retired + eta_ch4.good_employment.student*employment_first.student + eta_ch4.good_employment.unable.to.work*employment_first.unable.to.work + eta_ch4.good_employment.unemployed*employment_first.unemployed
ch4_21.moderate ~ alpha_ch4.moderate_21*1 + eta_ch4.moderate_y1*mhi5_20 + eta_ch4.moderate_y2*mhi5_19 + eta_ch4.moderate_y3*mhi5_18 + eta_ch4.moderate_x0*cs104_21 + eta_ch4.moderate_x1*cs104_20 + eta_ch4.moderate_leeftijd.18.24*leeftijd_first.18.24 + eta_ch4.moderate_leeftijd.25.39*leeftijd_first.25.39 + eta_ch4.moderate_leeftijd.40.66*leeftijd_first.40.66 + eta_ch4.moderate_leeftijd.over.67*leeftijd_first.over.67 + eta_ch4.moderate_nettohh_f.under.15k*nettohh_f_first.under.15k + eta_ch4.moderate_nettohh_f.over.50k*nettohh_f_first.over.50k + eta_ch4.moderate_herkomstgroep.first.w*herkomstgroep_first.first.w + eta_ch4.moderate_herkomstgroep.first.nonw*herkomstgroep_first.first.nonw + eta_ch4.moderate_herkomstgroep.second.w*herkomstgroep_first.second.w + eta_ch4.moderate_herkomstgroep.second.nonw*herkomstgroep_first.second.nonw + eta_ch4.moderate_geslacht.male*geslacht_first.male + eta_ch4.moderate_burgstat.married*burgstat_first.married + eta_ch4.moderate_burgstat.never.been.married*burgstat_first.never.been.married + eta_ch4.moderate_burgstat.separated*burgstat_first.separated + eta_ch4.moderate_burgstat.widow.or.widower*burgstat_first.widow.or.widower + eta_ch4.moderate_oplcat.hbo*oplcat_first.hbo + eta_ch4.moderate_oplcat.mbo*oplcat_first.mbo + eta_ch4.moderate_oplcat.primary.school*oplcat_first.primary.school + eta_ch4.moderate_oplcat.vmbo*oplcat_first.vmbo + eta_ch4.moderate_oplcat.wo*oplcat_first.wo + eta_ch4.moderate_employment.homemaker*employment_first.homemaker + eta_ch4.moderate_employment.retired*employment_first.retired + eta_ch4.moderate_employment.student*employment_first.student + eta_ch4.moderate_employment.unable.to.work*employment_first.unable.to.work + eta_ch4.moderate_employment.unemployed*employment_first.unemployed
ch4_21.poor ~ alpha_ch4.poor_21*1 + eta_ch4.poor_y1*mhi5_20 + eta_ch4.poor_y2*mhi5_19 + eta_ch4.poor_y3*mhi5_18 + eta_ch4.poor_x0*cs104_21 + eta_ch4.poor_x1*cs104_20 + eta_ch4.poor_leeftijd.18.24*leeftijd_first.18.24 + eta_ch4.poor_leeftijd.25.39*leeftijd_first.25.39 + eta_ch4.poor_leeftijd.40.66*leeftijd_first.40.66 + eta_ch4.poor_leeftijd.over.67*leeftijd_first.over.67 + eta_ch4.poor_nettohh_f.under.15k*nettohh_f_first.under.15k + eta_ch4.poor_nettohh_f.over.50k*nettohh_f_first.over.50k + eta_ch4.poor_herkomstgroep.first.w*herkomstgroep_first.first.w + eta_ch4.poor_herkomstgroep.first.nonw*herkomstgroep_first.first.nonw + eta_ch4.poor_herkomstgroep.second.w*herkomstgroep_first.second.w + eta_ch4.poor_herkomstgroep.second.nonw*herkomstgroep_first.second.nonw + eta_ch4.poor_geslacht.male*geslacht_first.male + eta_ch4.poor_burgstat.married*burgstat_first.married + eta_ch4.poor_burgstat.never.been.married*burgstat_first.never.been.married + eta_ch4.poor_burgstat.separated*burgstat_first.separated + eta_ch4.poor_burgstat.widow.or.widower*burgstat_first.widow.or.widower + eta_ch4.poor_oplcat.hbo*oplcat_first.hbo + eta_ch4.poor_oplcat.mbo*oplcat_first.mbo + eta_ch4.poor_oplcat.primary.school*oplcat_first.primary.school + eta_ch4.poor_oplcat.vmbo*oplcat_first.vmbo + eta_ch4.poor_oplcat.wo*oplcat_first.wo + eta_ch4.poor_employment.homemaker*employment_first.homemaker + eta_ch4.poor_employment.retired*employment_first.retired + eta_ch4.poor_employment.student*employment_first.student + eta_ch4.poor_employment.unable.to.work*employment_first.unable.to.work + eta_ch4.poor_employment.unemployed*employment_first.unemployed
ch4_21.very.good ~ alpha_ch4.very.good_21*1 + eta_ch4.very.good_y1*mhi5_20 + eta_ch4.very.good_y2*mhi5_19 + eta_ch4.very.good_y3*mhi5_18 + eta_ch4.very.good_x0*cs104_21 + eta_ch4.very.good_x1*cs104_20 + eta_ch4.very.good_leeftijd.18.24*leeftijd_first.18.24 + eta_ch4.very.good_leeftijd.25.39*leeftijd_first.25.39 + eta_ch4.very.good_leeftijd.40.66*leeftijd_first.40.66 + eta_ch4.very.good_leeftijd.over.67*leeftijd_first.over.67 + eta_ch4.very.good_nettohh_f.under.15k*nettohh_f_first.under.15k + eta_ch4.very.good_nettohh_f.over.50k*nettohh_f_first.over.50k + eta_ch4.very.good_herkomstgroep.first.w*herkomstgroep_first.first.w + eta_ch4.very.good_herkomstgroep.first.nonw*herkomstgroep_first.first.nonw + eta_ch4.very.good_herkomstgroep.second.w*herkomstgroep_first.second.w + eta_ch4.very.good_herkomstgroep.second.nonw*herkomstgroep_first.second.nonw + eta_ch4.very.good_geslacht.male*geslacht_first.male + eta_ch4.very.good_burgstat.married*burgstat_first.married + eta_ch4.very.good_burgstat.never.been.married*burgstat_first.never.been.married + eta_ch4.very.good_burgstat.separated*burgstat_first.separated + eta_ch4.very.good_burgstat.widow.or.widower*burgstat_first.widow.or.widower + eta_ch4.very.good_oplcat.hbo*oplcat_first.hbo + eta_ch4.very.good_oplcat.mbo*oplcat_first.mbo + eta_ch4.very.good_oplcat.primary.school*oplcat_first.primary.school + eta_ch4.very.good_oplcat.vmbo*oplcat_first.vmbo + eta_ch4.very.good_oplcat.wo*oplcat_first.wo + eta_ch4.very.good_employment.homemaker*employment_first.homemaker + eta_ch4.very.good_employment.retired*employment_first.retired + eta_ch4.very.good_employment.student*employment_first.student + eta_ch4.very.good_employment.unable.to.work*employment_first.unable.to.work + eta_ch4.very.good_employment.unemployed*employment_first.unemployed
bmi_21.normal.weight ~ alpha_bmi.normal.weight_21*1 + eta_bmi.normal.weight_y1*mhi5_20 + eta_bmi.normal.weight_y2*mhi5_19 + eta_bmi.normal.weight_y3*mhi5_18 + eta_bmi.normal.weight_x0*cs104_21 + eta_bmi.normal.weight_x1*cs104_20 + eta_bmi.normal.weight_leeftijd.18.24*leeftijd_first.18.24 + eta_bmi.normal.weight_leeftijd.25.39*leeftijd_first.25.39 + eta_bmi.normal.weight_leeftijd.40.66*leeftijd_first.40.66 + eta_bmi.normal.weight_leeftijd.over.67*leeftijd_first.over.67 + eta_bmi.normal.weight_nettohh_f.under.15k*nettohh_f_first.under.15k + eta_bmi.normal.weight_nettohh_f.over.50k*nettohh_f_first.over.50k + eta_bmi.normal.weight_herkomstgroep.first.w*herkomstgroep_first.first.w + eta_bmi.normal.weight_herkomstgroep.first.nonw*herkomstgroep_first.first.nonw + eta_bmi.normal.weight_herkomstgroep.second.w*herkomstgroep_first.second.w + eta_bmi.normal.weight_herkomstgroep.second.nonw*herkomstgroep_first.second.nonw + eta_bmi.normal.weight_geslacht.male*geslacht_first.male + eta_bmi.normal.weight_burgstat.married*burgstat_first.married + eta_bmi.normal.weight_burgstat.never.been.married*burgstat_first.never.been.married + eta_bmi.normal.weight_burgstat.separated*burgstat_first.separated + eta_bmi.normal.weight_burgstat.widow.or.widower*burgstat_first.widow.or.widower + eta_bmi.normal.weight_oplcat.hbo*oplcat_first.hbo + eta_bmi.normal.weight_oplcat.mbo*oplcat_first.mbo + eta_bmi.normal.weight_oplcat.primary.school*oplcat_first.primary.school + eta_bmi.normal.weight_oplcat.vmbo*oplcat_first.vmbo + eta_bmi.normal.weight_oplcat.wo*oplcat_first.wo + eta_bmi.normal.weight_employment.homemaker*employment_first.homemaker + eta_bmi.normal.weight_employment.retired*employment_first.retired + eta_bmi.normal.weight_employment.student*employment_first.student + eta_bmi.normal.weight_employment.unable.to.work*employment_first.unable.to.work + eta_bmi.normal.weight_employment.unemployed*employment_first.unemployed
bmi_21.overweight ~ alpha_bmi.overweight_21*1 + eta_bmi.overweight_y1*mhi5_20 + eta_bmi.overweight_y2*mhi5_19 + eta_bmi.overweight_y3*mhi5_18 + eta_bmi.overweight_x0*cs104_21 + eta_bmi.overweight_x1*cs104_20 + eta_bmi.overweight_leeftijd.18.24*leeftijd_first.18.24 + eta_bmi.overweight_leeftijd.25.39*leeftijd_first.25.39 + eta_bmi.overweight_leeftijd.40.66*leeftijd_first.40.66 + eta_bmi.overweight_leeftijd.over.67*leeftijd_first.over.67 + eta_bmi.overweight_nettohh_f.under.15k*nettohh_f_first.under.15k + eta_bmi.overweight_nettohh_f.over.50k*nettohh_f_first.over.50k + eta_bmi.overweight_herkomstgroep.first.w*herkomstgroep_first.first.w + eta_bmi.overweight_herkomstgroep.first.nonw*herkomstgroep_first.first.nonw + eta_bmi.overweight_herkomstgroep.second.w*herkomstgroep_first.second.w + eta_bmi.overweight_herkomstgroep.second.nonw*herkomstgroep_first.second.nonw + eta_bmi.overweight_geslacht.male*geslacht_first.male + eta_bmi.overweight_burgstat.married*burgstat_first.married + eta_bmi.overweight_burgstat.never.been.married*burgstat_first.never.been.married + eta_bmi.overweight_burgstat.separated*burgstat_first.separated + eta_bmi.overweight_burgstat.widow.or.widower*burgstat_first.widow.or.widower + eta_bmi.overweight_oplcat.hbo*oplcat_first.hbo + eta_bmi.overweight_oplcat.mbo*oplcat_first.mbo + eta_bmi.overweight_oplcat.primary.school*oplcat_first.primary.school + eta_bmi.overweight_oplcat.vmbo*oplcat_first.vmbo + eta_bmi.overweight_oplcat.wo*oplcat_first.wo + eta_bmi.overweight_employment.homemaker*employment_first.homemaker + eta_bmi.overweight_employment.retired*employment_first.retired + eta_bmi.overweight_employment.student*employment_first.student + eta_bmi.overweight_employment.unable.to.work*employment_first.unable.to.work + eta_bmi.overweight_employment.unemployed*employment_first.unemployed
bmi_21.obese ~ alpha_bmi.obese_21*1 + eta_bmi.obese_y1*mhi5_20 + eta_bmi.obese_y2*mhi5_19 + eta_bmi.obese_y3*mhi5_18 + eta_bmi.obese_x0*cs104_21 + eta_bmi.obese_x1*cs104_20 + eta_bmi.obese_leeftijd.18.24*leeftijd_first.18.24 + eta_bmi.obese_leeftijd.25.39*leeftijd_first.25.39 + eta_bmi.obese_leeftijd.40.66*leeftijd_first.40.66 + eta_bmi.obese_leeftijd.over.67*leeftijd_first.over.67 + eta_bmi.obese_nettohh_f.under.15k*nettohh_f_first.under.15k + eta_bmi.obese_nettohh_f.over.50k*nettohh_f_first.over.50k + eta_bmi.obese_herkomstgroep.first.w*herkomstgroep_first.first.w + eta_bmi.obese_herkomstgroep.first.nonw*herkomstgroep_first.first.nonw + eta_bmi.obese_herkomstgroep.second.w*herkomstgroep_first.second.w + eta_bmi.obese_herkomstgroep.second.nonw*herkomstgroep_first.second.nonw + eta_bmi.obese_geslacht.male*geslacht_first.male + eta_bmi.obese_burgstat.married*burgstat_first.married + eta_bmi.obese_burgstat.never.been.married*burgstat_first.never.been.married + eta_bmi.obese_burgstat.separated*burgstat_first.separated + eta_bmi.obese_burgstat.widow.or.widower*burgstat_first.widow.or.widower + eta_bmi.obese_oplcat.hbo*oplcat_first.hbo + eta_bmi.obese_oplcat.mbo*oplcat_first.mbo + eta_bmi.obese_oplcat.primary.school*oplcat_first.primary.school + eta_bmi.obese_oplcat.vmbo*oplcat_first.vmbo + eta_bmi.obese_oplcat.wo*oplcat_first.wo + eta_bmi.obese_employment.homemaker*employment_first.homemaker + eta_bmi.obese_employment.retired*employment_first.retired + eta_bmi.obese_employment.student*employment_first.student + eta_bmi.obese_employment.unable.to.work*employment_first.unable.to.work + eta_bmi.obese_employment.unemployed*employment_first.unemployed
ch98_21 ~ alpha_ch98_21*1 + eta_ch98_y1*mhi5_20 + eta_ch98_y2*mhi5_19 + eta_ch98_y3*mhi5_18 + eta_ch98_x0*cs104_21 + eta_ch98_x1*cs104_20 + eta_ch98_leeftijd.18.24*leeftijd_first.18.24 + eta_ch98_leeftijd.25.39*leeftijd_first.25.39 + eta_ch98_leeftijd.40.66*leeftijd_first.40.66 + eta_ch98_leeftijd.over.67*leeftijd_first.over.67 + eta_ch98_nettohh_f.under.15k*nettohh_f_first.under.15k + eta_ch98_nettohh_f.over.50k*nettohh_f_first.over.50k + eta_ch98_herkomstgroep.first.w*herkomstgroep_first.first.w + eta_ch98_herkomstgroep.first.nonw*herkomstgroep_first.first.nonw + eta_ch98_herkomstgroep.second.w*herkomstgroep_first.second.w + eta_ch98_herkomstgroep.second.nonw*herkomstgroep_first.second.nonw + eta_ch98_geslacht.male*geslacht_first.male + eta_ch98_burgstat.married*burgstat_first.married + eta_ch98_burgstat.never.been.married*burgstat_first.never.been.married + eta_ch98_burgstat.separated*burgstat_first.separated + eta_ch98_burgstat.widow.or.widower*burgstat_first.widow.or.widower + eta_ch98_oplcat.hbo*oplcat_first.hbo + eta_ch98_oplcat.mbo*oplcat_first.mbo + eta_ch98_oplcat.primary.school*oplcat_first.primary.school + eta_ch98_oplcat.vmbo*oplcat_first.vmbo + eta_ch98_oplcat.wo*oplcat_first.wo + eta_ch98_employment.homemaker*employment_first.homemaker + eta_ch98_employment.retired*employment_first.retired + eta_ch98_employment.student*employment_first.student + eta_ch98_employment.unable.to.work*employment_first.unable.to.work + eta_ch98_employment.unemployed*employment_first.unemployed
mhi5_22 ~ alpha_mhi5_22*1 + rho1*mhi5_21 + rho2*mhi5_20 + rho3*mhi5_19 + beta0_cs104*cs104_22 + beta1_cs104*cs104_21 + zeta_ch4.good*ch4_22.good + zeta_ch4.moderate*ch4_22.moderate + zeta_ch4.poor*ch4_22.poor + zeta_ch4.very.good*ch4_22.very.good + zeta_bmi.normal.weight*bmi_22.normal.weight + zeta_bmi.overweight*bmi_22.overweight + zeta_bmi.obese*bmi_22.obese + zeta_ch98*ch98_22 + delta_leeftijd.18.24*leeftijd_first.18.24 + delta_leeftijd.25.39*leeftijd_first.25.39 + delta_leeftijd.40.66*leeftijd_first.40.66 + delta_leeftijd.over.67*leeftijd_first.over.67 + delta_nettohh_f.under.15k*nettohh_f_first.under.15k + delta_nettohh_f.over.50k*nettohh_f_first.over.50k + delta_herkomstgroep.first.w*herkomstgroep_first.first.w + delta_herkomstgroep.first.nonw*herkomstgroep_first.first.nonw + delta_herkomstgroep.second.w*herkomstgroep_first.second.w + delta_herkomstgroep.second.nonw*herkomstgroep_first.second.nonw + delta_geslacht.male*geslacht_first.male + delta_burgstat.married*burgstat_first.married + delta_burgstat.never.been.married*burgstat_first.never.been.married + delta_burgstat.separated*burgstat_first.separated + delta_burgstat.widow.or.widower*burgstat_first.widow.or.widower + delta_oplcat.hbo*oplcat_first.hbo + delta_oplcat.mbo*oplcat_first.mbo + delta_oplcat.primary.school*oplcat_first.primary.school + delta_oplcat.vmbo*oplcat_first.vmbo + delta_oplcat.wo*oplcat_first.wo + delta_employment.homemaker*employment_first.homemaker + delta_employment.retired*employment_first.retired + delta_employment.student*employment_first.student + delta_employment.unable.to.work*employment_first.unable.to.work + delta_employment.unemployed*employment_first.unemployed
ch4_22.good ~ alpha_ch4.good_22*1 + eta_ch4.good_y1*mhi5_21 + eta_ch4.good_y2*mhi5_20 + eta_ch4.good_y3*mhi5_19 + eta_ch4.good_x0*cs104_22 + eta_ch4.good_x1*cs104_21 + eta_ch4.good_leeftijd.18.24*leeftijd_first.18.24 + eta_ch4.good_leeftijd.25.39*leeftijd_first.25.39 + eta_ch4.good_leeftijd.40.66*leeftijd_first.40.66 + eta_ch4.good_leeftijd.over.67*leeftijd_first.over.67 + eta_ch4.good_nettohh_f.under.15k*nettohh_f_first.under.15k + eta_ch4.good_nettohh_f.over.50k*nettohh_f_first.over.50k + eta_ch4.good_herkomstgroep.first.w*herkomstgroep_first.first.w + eta_ch4.good_herkomstgroep.first.nonw*herkomstgroep_first.first.nonw + eta_ch4.good_herkomstgroep.second.w*herkomstgroep_first.second.w + eta_ch4.good_herkomstgroep.second.nonw*herkomstgroep_first.second.nonw + eta_ch4.good_geslacht.male*geslacht_first.male + eta_ch4.good_burgstat.married*burgstat_first.married + eta_ch4.good_burgstat.never.been.married*burgstat_first.never.been.married + eta_ch4.good_burgstat.separated*burgstat_first.separated + eta_ch4.good_burgstat.widow.or.widower*burgstat_first.widow.or.widower + eta_ch4.good_oplcat.hbo*oplcat_first.hbo + eta_ch4.good_oplcat.mbo*oplcat_first.mbo + eta_ch4.good_oplcat.primary.school*oplcat_first.primary.school + eta_ch4.good_oplcat.vmbo*oplcat_first.vmbo + eta_ch4.good_oplcat.wo*oplcat_first.wo + eta_ch4.good_employment.homemaker*employment_first.homemaker + eta_ch4.good_employment.retired*employment_first.retired + eta_ch4.good_employment.student*employment_first.student + eta_ch4.good_employment.unable.to.work*employment_first.unable.to.work + eta_ch4.good_employment.unemployed*employment_first.unemployed
ch4_22.moderate ~ alpha_ch4.moderate_22*1 + eta_ch4.moderate_y1*mhi5_21 + eta_ch4.moderate_y2*mhi5_20 + eta_ch4.moderate_y3*mhi5_19 + eta_ch4.moderate_x0*cs104_22 + eta_ch4.moderate_x1*cs104_21 + eta_ch4.moderate_leeftijd.18.24*leeftijd_first.18.24 + eta_ch4.moderate_leeftijd.25.39*leeftijd_first.25.39 + eta_ch4.moderate_leeftijd.40.66*leeftijd_first.40.66 + eta_ch4.moderate_leeftijd.over.67*leeftijd_first.over.67 + eta_ch4.moderate_nettohh_f.under.15k*nettohh_f_first.under.15k + eta_ch4.moderate_nettohh_f.over.50k*nettohh_f_first.over.50k + eta_ch4.moderate_herkomstgroep.first.w*herkomstgroep_first.first.w + eta_ch4.moderate_herkomstgroep.first.nonw*herkomstgroep_first.first.nonw + eta_ch4.moderate_herkomstgroep.second.w*herkomstgroep_first.second.w + eta_ch4.moderate_herkomstgroep.second.nonw*herkomstgroep_first.second.nonw + eta_ch4.moderate_geslacht.male*geslacht_first.male + eta_ch4.moderate_burgstat.married*burgstat_first.married + eta_ch4.moderate_burgstat.never.been.married*burgstat_first.never.been.married + eta_ch4.moderate_burgstat.separated*burgstat_first.separated + eta_ch4.moderate_burgstat.widow.or.widower*burgstat_first.widow.or.widower + eta_ch4.moderate_oplcat.hbo*oplcat_first.hbo + eta_ch4.moderate_oplcat.mbo*oplcat_first.mbo + eta_ch4.moderate_oplcat.primary.school*oplcat_first.primary.school + eta_ch4.moderate_oplcat.vmbo*oplcat_first.vmbo + eta_ch4.moderate_oplcat.wo*oplcat_first.wo + eta_ch4.moderate_employment.homemaker*employment_first.homemaker + eta_ch4.moderate_employment.retired*employment_first.retired + eta_ch4.moderate_employment.student*employment_first.student + eta_ch4.moderate_employment.unable.to.work*employment_first.unable.to.work + eta_ch4.moderate_employment.unemployed*employment_first.unemployed
ch4_22.poor ~ alpha_ch4.poor_22*1 + eta_ch4.poor_y1*mhi5_21 + eta_ch4.poor_y2*mhi5_20 + eta_ch4.poor_y3*mhi5_19 + eta_ch4.poor_x0*cs104_22 + eta_ch4.poor_x1*cs104_21 + eta_ch4.poor_leeftijd.18.24*leeftijd_first.18.24 + eta_ch4.poor_leeftijd.25.39*leeftijd_first.25.39 + eta_ch4.poor_leeftijd.40.66*leeftijd_first.40.66 + eta_ch4.poor_leeftijd.over.67*leeftijd_first.over.67 + eta_ch4.poor_nettohh_f.under.15k*nettohh_f_first.under.15k + eta_ch4.poor_nettohh_f.over.50k*nettohh_f_first.over.50k + eta_ch4.poor_herkomstgroep.first.w*herkomstgroep_first.first.w + eta_ch4.poor_herkomstgroep.first.nonw*herkomstgroep_first.first.nonw + eta_ch4.poor_herkomstgroep.second.w*herkomstgroep_first.second.w + eta_ch4.poor_herkomstgroep.second.nonw*herkomstgroep_first.second.nonw + eta_ch4.poor_geslacht.male*geslacht_first.male + eta_ch4.poor_burgstat.married*burgstat_first.married + eta_ch4.poor_burgstat.never.been.married*burgstat_first.never.been.married + eta_ch4.poor_burgstat.separated*burgstat_first.separated + eta_ch4.poor_burgstat.widow.or.widower*burgstat_first.widow.or.widower + eta_ch4.poor_oplcat.hbo*oplcat_first.hbo + eta_ch4.poor_oplcat.mbo*oplcat_first.mbo + eta_ch4.poor_oplcat.primary.school*oplcat_first.primary.school + eta_ch4.poor_oplcat.vmbo*oplcat_first.vmbo + eta_ch4.poor_oplcat.wo*oplcat_first.wo + eta_ch4.poor_employment.homemaker*employment_first.homemaker + eta_ch4.poor_employment.retired*employment_first.retired + eta_ch4.poor_employment.student*employment_first.student + eta_ch4.poor_employment.unable.to.work*employment_first.unable.to.work + eta_ch4.poor_employment.unemployed*employment_first.unemployed
ch4_22.very.good ~ alpha_ch4.very.good_22*1 + eta_ch4.very.good_y1*mhi5_21 + eta_ch4.very.good_y2*mhi5_20 + eta_ch4.very.good_y3*mhi5_19 + eta_ch4.very.good_x0*cs104_22 + eta_ch4.very.good_x1*cs104_21 + eta_ch4.very.good_leeftijd.18.24*leeftijd_first.18.24 + eta_ch4.very.good_leeftijd.25.39*leeftijd_first.25.39 + eta_ch4.very.good_leeftijd.40.66*leeftijd_first.40.66 + eta_ch4.very.good_leeftijd.over.67*leeftijd_first.over.67 + eta_ch4.very.good_nettohh_f.under.15k*nettohh_f_first.under.15k + eta_ch4.very.good_nettohh_f.over.50k*nettohh_f_first.over.50k + eta_ch4.very.good_herkomstgroep.first.w*herkomstgroep_first.first.w + eta_ch4.very.good_herkomstgroep.first.nonw*herkomstgroep_first.first.nonw + eta_ch4.very.good_herkomstgroep.second.w*herkomstgroep_first.second.w + eta_ch4.very.good_herkomstgroep.second.nonw*herkomstgroep_first.second.nonw + eta_ch4.very.good_geslacht.male*geslacht_first.male + eta_ch4.very.good_burgstat.married*burgstat_first.married + eta_ch4.very.good_burgstat.never.been.married*burgstat_first.never.been.married + eta_ch4.very.good_burgstat.separated*burgstat_first.separated + eta_ch4.very.good_burgstat.widow.or.widower*burgstat_first.widow.or.widower + eta_ch4.very.good_oplcat.hbo*oplcat_first.hbo + eta_ch4.very.good_oplcat.mbo*oplcat_first.mbo + eta_ch4.very.good_oplcat.primary.school*oplcat_first.primary.school + eta_ch4.very.good_oplcat.vmbo*oplcat_first.vmbo + eta_ch4.very.good_oplcat.wo*oplcat_first.wo + eta_ch4.very.good_employment.homemaker*employment_first.homemaker + eta_ch4.very.good_employment.retired*employment_first.retired + eta_ch4.very.good_employment.student*employment_first.student + eta_ch4.very.good_employment.unable.to.work*employment_first.unable.to.work + eta_ch4.very.good_employment.unemployed*employment_first.unemployed
bmi_22.normal.weight ~ alpha_bmi.normal.weight_22*1 + eta_bmi.normal.weight_y1*mhi5_21 + eta_bmi.normal.weight_y2*mhi5_20 + eta_bmi.normal.weight_y3*mhi5_19 + eta_bmi.normal.weight_x0*cs104_22 + eta_bmi.normal.weight_x1*cs104_21 + eta_bmi.normal.weight_leeftijd.18.24*leeftijd_first.18.24 + eta_bmi.normal.weight_leeftijd.25.39*leeftijd_first.25.39 + eta_bmi.normal.weight_leeftijd.40.66*leeftijd_first.40.66 + eta_bmi.normal.weight_leeftijd.over.67*leeftijd_first.over.67 + eta_bmi.normal.weight_nettohh_f.under.15k*nettohh_f_first.under.15k + eta_bmi.normal.weight_nettohh_f.over.50k*nettohh_f_first.over.50k + eta_bmi.normal.weight_herkomstgroep.first.w*herkomstgroep_first.first.w + eta_bmi.normal.weight_herkomstgroep.first.nonw*herkomstgroep_first.first.nonw + eta_bmi.normal.weight_herkomstgroep.second.w*herkomstgroep_first.second.w + eta_bmi.normal.weight_herkomstgroep.second.nonw*herkomstgroep_first.second.nonw + eta_bmi.normal.weight_geslacht.male*geslacht_first.male + eta_bmi.normal.weight_burgstat.married*burgstat_first.married + eta_bmi.normal.weight_burgstat.never.been.married*burgstat_first.never.been.married + eta_bmi.normal.weight_burgstat.separated*burgstat_first.separated + eta_bmi.normal.weight_burgstat.widow.or.widower*burgstat_first.widow.or.widower + eta_bmi.normal.weight_oplcat.hbo*oplcat_first.hbo + eta_bmi.normal.weight_oplcat.mbo*oplcat_first.mbo + eta_bmi.normal.weight_oplcat.primary.school*oplcat_first.primary.school + eta_bmi.normal.weight_oplcat.vmbo*oplcat_first.vmbo + eta_bmi.normal.weight_oplcat.wo*oplcat_first.wo + eta_bmi.normal.weight_employment.homemaker*employment_first.homemaker + eta_bmi.normal.weight_employment.retired*employment_first.retired + eta_bmi.normal.weight_employment.student*employment_first.student + eta_bmi.normal.weight_employment.unable.to.work*employment_first.unable.to.work + eta_bmi.normal.weight_employment.unemployed*employment_first.unemployed
bmi_22.overweight ~ alpha_bmi.overweight_22*1 + eta_bmi.overweight_y1*mhi5_21 + eta_bmi.overweight_y2*mhi5_20 + eta_bmi.overweight_y3*mhi5_19 + eta_bmi.overweight_x0*cs104_22 + eta_bmi.overweight_x1*cs104_21 + eta_bmi.overweight_leeftijd.18.24*leeftijd_first.18.24 + eta_bmi.overweight_leeftijd.25.39*leeftijd_first.25.39 + eta_bmi.overweight_leeftijd.40.66*leeftijd_first.40.66 + eta_bmi.overweight_leeftijd.over.67*leeftijd_first.over.67 + eta_bmi.overweight_nettohh_f.under.15k*nettohh_f_first.under.15k + eta_bmi.overweight_nettohh_f.over.50k*nettohh_f_first.over.50k + eta_bmi.overweight_herkomstgroep.first.w*herkomstgroep_first.first.w + eta_bmi.overweight_herkomstgroep.first.nonw*herkomstgroep_first.first.nonw + eta_bmi.overweight_herkomstgroep.second.w*herkomstgroep_first.second.w + eta_bmi.overweight_herkomstgroep.second.nonw*herkomstgroep_first.second.nonw + eta_bmi.overweight_geslacht.male*geslacht_first.male + eta_bmi.overweight_burgstat.married*burgstat_first.married + eta_bmi.overweight_burgstat.never.been.married*burgstat_first.never.been.married + eta_bmi.overweight_burgstat.separated*burgstat_first.separated + eta_bmi.overweight_burgstat.widow.or.widower*burgstat_first.widow.or.widower + eta_bmi.overweight_oplcat.hbo*oplcat_first.hbo + eta_bmi.overweight_oplcat.mbo*oplcat_first.mbo + eta_bmi.overweight_oplcat.primary.school*oplcat_first.primary.school + eta_bmi.overweight_oplcat.vmbo*oplcat_first.vmbo + eta_bmi.overweight_oplcat.wo*oplcat_first.wo + eta_bmi.overweight_employment.homemaker*employment_first.homemaker + eta_bmi.overweight_employment.retired*employment_first.retired + eta_bmi.overweight_employment.student*employment_first.student + eta_bmi.overweight_employment.unable.to.work*employment_first.unable.to.work + eta_bmi.overweight_employment.unemployed*employment_first.unemployed
bmi_22.obese ~ alpha_bmi.obese_22*1 + eta_bmi.obese_y1*mhi5_21 + eta_bmi.obese_y2*mhi5_20 + eta_bmi.obese_y3*mhi5_19 + eta_bmi.obese_x0*cs104_22 + eta_bmi.obese_x1*cs104_21 + eta_bmi.obese_leeftijd.18.24*leeftijd_first.18.24 + eta_bmi.obese_leeftijd.25.39*leeftijd_first.25.39 + eta_bmi.obese_leeftijd.40.66*leeftijd_first.40.66 + eta_bmi.obese_leeftijd.over.67*leeftijd_first.over.67 + eta_bmi.obese_nettohh_f.under.15k*nettohh_f_first.under.15k + eta_bmi.obese_nettohh_f.over.50k*nettohh_f_first.over.50k + eta_bmi.obese_herkomstgroep.first.w*herkomstgroep_first.first.w + eta_bmi.obese_herkomstgroep.first.nonw*herkomstgroep_first.first.nonw + eta_bmi.obese_herkomstgroep.second.w*herkomstgroep_first.second.w + eta_bmi.obese_herkomstgroep.second.nonw*herkomstgroep_first.second.nonw + eta_bmi.obese_geslacht.male*geslacht_first.male + eta_bmi.obese_burgstat.married*burgstat_first.married + eta_bmi.obese_burgstat.never.been.married*burgstat_first.never.been.married + eta_bmi.obese_burgstat.separated*burgstat_first.separated + eta_bmi.obese_burgstat.widow.or.widower*burgstat_first.widow.or.widower + eta_bmi.obese_oplcat.hbo*oplcat_first.hbo + eta_bmi.obese_oplcat.mbo*oplcat_first.mbo + eta_bmi.obese_oplcat.primary.school*oplcat_first.primary.school + eta_bmi.obese_oplcat.vmbo*oplcat_first.vmbo + eta_bmi.obese_oplcat.wo*oplcat_first.wo + eta_bmi.obese_employment.homemaker*employment_first.homemaker + eta_bmi.obese_employment.retired*employment_first.retired + eta_bmi.obese_employment.student*employment_first.student + eta_bmi.obese_employment.unable.to.work*employment_first.unable.to.work + eta_bmi.obese_employment.unemployed*employment_first.unemployed
ch98_22 ~ alpha_ch98_22*1 + eta_ch98_y1*mhi5_21 + eta_ch98_y2*mhi5_20 + eta_ch98_y3*mhi5_19 + eta_ch98_x0*cs104_22 + eta_ch98_x1*cs104_21 + eta_ch98_leeftijd.18.24*leeftijd_first.18.24 + eta_ch98_leeftijd.25.39*leeftijd_first.25.39 + eta_ch98_leeftijd.40.66*leeftijd_first.40.66 + eta_ch98_leeftijd.over.67*leeftijd_first.over.67 + eta_ch98_nettohh_f.under.15k*nettohh_f_first.under.15k + eta_ch98_nettohh_f.over.50k*nettohh_f_first.over.50k + eta_ch98_herkomstgroep.first.w*herkomstgroep_first.first.w + eta_ch98_herkomstgroep.first.nonw*herkomstgroep_first.first.nonw + eta_ch98_herkomstgroep.second.w*herkomstgroep_first.second.w + eta_ch98_herkomstgroep.second.nonw*herkomstgroep_first.second.nonw + eta_ch98_geslacht.male*geslacht_first.male + eta_ch98_burgstat.married*burgstat_first.married + eta_ch98_burgstat.never.been.married*burgstat_first.never.been.married + eta_ch98_burgstat.separated*burgstat_first.separated + eta_ch98_burgstat.widow.or.widower*burgstat_first.widow.or.widower + eta_ch98_oplcat.hbo*oplcat_first.hbo + eta_ch98_oplcat.mbo*oplcat_first.mbo + eta_ch98_oplcat.primary.school*oplcat_first.primary.school + eta_ch98_oplcat.vmbo*oplcat_first.vmbo + eta_ch98_oplcat.wo*oplcat_first.wo + eta_ch98_employment.homemaker*employment_first.homemaker + eta_ch98_employment.retired*employment_first.retired + eta_ch98_employment.student*employment_first.student + eta_ch98_employment.unable.to.work*employment_first.unable.to.work + eta_ch98_employment.unemployed*employment_first.unemployed
mhi5_23 ~ alpha_mhi5_23*1 + rho1*mhi5_22 + rho2*mhi5_21 + rho3*mhi5_20 + beta0_cs104*cs104_23 + beta1_cs104*cs104_22 + zeta_ch4.good*ch4_23.good + zeta_ch4.moderate*ch4_23.moderate + zeta_ch4.poor*ch4_23.poor + zeta_ch4.very.good*ch4_23.very.good + zeta_bmi.normal.weight*bmi_23.normal.weight + zeta_bmi.overweight*bmi_23.overweight + zeta_bmi.obese*bmi_23.obese + zeta_ch98*ch98_23 + delta_leeftijd.18.24*leeftijd_first.18.24 + delta_leeftijd.25.39*leeftijd_first.25.39 + delta_leeftijd.40.66*leeftijd_first.40.66 + delta_leeftijd.over.67*leeftijd_first.over.67 + delta_nettohh_f.under.15k*nettohh_f_first.under.15k + delta_nettohh_f.over.50k*nettohh_f_first.over.50k + delta_herkomstgroep.first.w*herkomstgroep_first.first.w + delta_herkomstgroep.first.nonw*herkomstgroep_first.first.nonw + delta_herkomstgroep.second.w*herkomstgroep_first.second.w + delta_herkomstgroep.second.nonw*herkomstgroep_first.second.nonw + delta_geslacht.male*geslacht_first.male + delta_burgstat.married*burgstat_first.married + delta_burgstat.never.been.married*burgstat_first.never.been.married + delta_burgstat.separated*burgstat_first.separated + delta_burgstat.widow.or.widower*burgstat_first.widow.or.widower + delta_oplcat.hbo*oplcat_first.hbo + delta_oplcat.mbo*oplcat_first.mbo + delta_oplcat.primary.school*oplcat_first.primary.school + delta_oplcat.vmbo*oplcat_first.vmbo + delta_oplcat.wo*oplcat_first.wo + delta_employment.homemaker*employment_first.homemaker + delta_employment.retired*employment_first.retired + delta_employment.student*employment_first.student + delta_employment.unable.to.work*employment_first.unable.to.work + delta_employment.unemployed*employment_first.unemployed
ch4_23.good ~ alpha_ch4.good_23*1 + eta_ch4.good_y1*mhi5_22 + eta_ch4.good_y2*mhi5_21 + eta_ch4.good_y3*mhi5_20 + eta_ch4.good_x0*cs104_23 + eta_ch4.good_x1*cs104_22 + eta_ch4.good_leeftijd.18.24*leeftijd_first.18.24 + eta_ch4.good_leeftijd.25.39*leeftijd_first.25.39 + eta_ch4.good_leeftijd.40.66*leeftijd_first.40.66 + eta_ch4.good_leeftijd.over.67*leeftijd_first.over.67 + eta_ch4.good_nettohh_f.under.15k*nettohh_f_first.under.15k + eta_ch4.good_nettohh_f.over.50k*nettohh_f_first.over.50k + eta_ch4.good_herkomstgroep.first.w*herkomstgroep_first.first.w + eta_ch4.good_herkomstgroep.first.nonw*herkomstgroep_first.first.nonw + eta_ch4.good_herkomstgroep.second.w*herkomstgroep_first.second.w + eta_ch4.good_herkomstgroep.second.nonw*herkomstgroep_first.second.nonw + eta_ch4.good_geslacht.male*geslacht_first.male + eta_ch4.good_burgstat.married*burgstat_first.married + eta_ch4.good_burgstat.never.been.married*burgstat_first.never.been.married + eta_ch4.good_burgstat.separated*burgstat_first.separated + eta_ch4.good_burgstat.widow.or.widower*burgstat_first.widow.or.widower + eta_ch4.good_oplcat.hbo*oplcat_first.hbo + eta_ch4.good_oplcat.mbo*oplcat_first.mbo + eta_ch4.good_oplcat.primary.school*oplcat_first.primary.school + eta_ch4.good_oplcat.vmbo*oplcat_first.vmbo + eta_ch4.good_oplcat.wo*oplcat_first.wo + eta_ch4.good_employment.homemaker*employment_first.homemaker + eta_ch4.good_employment.retired*employment_first.retired + eta_ch4.good_employment.student*employment_first.student + eta_ch4.good_employment.unable.to.work*employment_first.unable.to.work + eta_ch4.good_employment.unemployed*employment_first.unemployed
ch4_23.moderate ~ alpha_ch4.moderate_23*1 + eta_ch4.moderate_y1*mhi5_22 + eta_ch4.moderate_y2*mhi5_21 + eta_ch4.moderate_y3*mhi5_20 + eta_ch4.moderate_x0*cs104_23 + eta_ch4.moderate_x1*cs104_22 + eta_ch4.moderate_leeftijd.18.24*leeftijd_first.18.24 + eta_ch4.moderate_leeftijd.25.39*leeftijd_first.25.39 + eta_ch4.moderate_leeftijd.40.66*leeftijd_first.40.66 + eta_ch4.moderate_leeftijd.over.67*leeftijd_first.over.67 + eta_ch4.moderate_nettohh_f.under.15k*nettohh_f_first.under.15k + eta_ch4.moderate_nettohh_f.over.50k*nettohh_f_first.over.50k + eta_ch4.moderate_herkomstgroep.first.w*herkomstgroep_first.first.w + eta_ch4.moderate_herkomstgroep.first.nonw*herkomstgroep_first.first.nonw + eta_ch4.moderate_herkomstgroep.second.w*herkomstgroep_first.second.w + eta_ch4.moderate_herkomstgroep.second.nonw*herkomstgroep_first.second.nonw + eta_ch4.moderate_geslacht.male*geslacht_first.male + eta_ch4.moderate_burgstat.married*burgstat_first.married + eta_ch4.moderate_burgstat.never.been.married*burgstat_first.never.been.married + eta_ch4.moderate_burgstat.separated*burgstat_first.separated + eta_ch4.moderate_burgstat.widow.or.widower*burgstat_first.widow.or.widower + eta_ch4.moderate_oplcat.hbo*oplcat_first.hbo + eta_ch4.moderate_oplcat.mbo*oplcat_first.mbo + eta_ch4.moderate_oplcat.primary.school*oplcat_first.primary.school + eta_ch4.moderate_oplcat.vmbo*oplcat_first.vmbo + eta_ch4.moderate_oplcat.wo*oplcat_first.wo + eta_ch4.moderate_employment.homemaker*employment_first.homemaker + eta_ch4.moderate_employment.retired*employment_first.retired + eta_ch4.moderate_employment.student*employment_first.student + eta_ch4.moderate_employment.unable.to.work*employment_first.unable.to.work + eta_ch4.moderate_employment.unemployed*employment_first.unemployed
ch4_23.poor ~ alpha_ch4.poor_23*1 + eta_ch4.poor_y1*mhi5_22 + eta_ch4.poor_y2*mhi5_21 + eta_ch4.poor_y3*mhi5_20 + eta_ch4.poor_x0*cs104_23 + eta_ch4.poor_x1*cs104_22 + eta_ch4.poor_leeftijd.18.24*leeftijd_first.18.24 + eta_ch4.poor_leeftijd.25.39*leeftijd_first.25.39 + eta_ch4.poor_leeftijd.40.66*leeftijd_first.40.66 + eta_ch4.poor_leeftijd.over.67*leeftijd_first.over.67 + eta_ch4.poor_nettohh_f.under.15k*nettohh_f_first.under.15k + eta_ch4.poor_nettohh_f.over.50k*nettohh_f_first.over.50k + eta_ch4.poor_herkomstgroep.first.w*herkomstgroep_first.first.w + eta_ch4.poor_herkomstgroep.first.nonw*herkomstgroep_first.first.nonw + eta_ch4.poor_herkomstgroep.second.w*herkomstgroep_first.second.w + eta_ch4.poor_herkomstgroep.second.nonw*herkomstgroep_first.second.nonw + eta_ch4.poor_geslacht.male*geslacht_first.male + eta_ch4.poor_burgstat.married*burgstat_first.married + eta_ch4.poor_burgstat.never.been.married*burgstat_first.never.been.married + eta_ch4.poor_burgstat.separated*burgstat_first.separated + eta_ch4.poor_burgstat.widow.or.widower*burgstat_first.widow.or.widower + eta_ch4.poor_oplcat.hbo*oplcat_first.hbo + eta_ch4.poor_oplcat.mbo*oplcat_first.mbo + eta_ch4.poor_oplcat.primary.school*oplcat_first.primary.school + eta_ch4.poor_oplcat.vmbo*oplcat_first.vmbo + eta_ch4.poor_oplcat.wo*oplcat_first.wo + eta_ch4.poor_employment.homemaker*employment_first.homemaker + eta_ch4.poor_employment.retired*employment_first.retired + eta_ch4.poor_employment.student*employment_first.student + eta_ch4.poor_employment.unable.to.work*employment_first.unable.to.work + eta_ch4.poor_employment.unemployed*employment_first.unemployed
ch4_23.very.good ~ alpha_ch4.very.good_23*1 + eta_ch4.very.good_y1*mhi5_22 + eta_ch4.very.good_y2*mhi5_21 + eta_ch4.very.good_y3*mhi5_20 + eta_ch4.very.good_x0*cs104_23 + eta_ch4.very.good_x1*cs104_22 + eta_ch4.very.good_leeftijd.18.24*leeftijd_first.18.24 + eta_ch4.very.good_leeftijd.25.39*leeftijd_first.25.39 + eta_ch4.very.good_leeftijd.40.66*leeftijd_first.40.66 + eta_ch4.very.good_leeftijd.over.67*leeftijd_first.over.67 + eta_ch4.very.good_nettohh_f.under.15k*nettohh_f_first.under.15k + eta_ch4.very.good_nettohh_f.over.50k*nettohh_f_first.over.50k + eta_ch4.very.good_herkomstgroep.first.w*herkomstgroep_first.first.w + eta_ch4.very.good_herkomstgroep.first.nonw*herkomstgroep_first.first.nonw + eta_ch4.very.good_herkomstgroep.second.w*herkomstgroep_first.second.w + eta_ch4.very.good_herkomstgroep.second.nonw*herkomstgroep_first.second.nonw + eta_ch4.very.good_geslacht.male*geslacht_first.male + eta_ch4.very.good_burgstat.married*burgstat_first.married + eta_ch4.very.good_burgstat.never.been.married*burgstat_first.never.been.married + eta_ch4.very.good_burgstat.separated*burgstat_first.separated + eta_ch4.very.good_burgstat.widow.or.widower*burgstat_first.widow.or.widower + eta_ch4.very.good_oplcat.hbo*oplcat_first.hbo + eta_ch4.very.good_oplcat.mbo*oplcat_first.mbo + eta_ch4.very.good_oplcat.primary.school*oplcat_first.primary.school + eta_ch4.very.good_oplcat.vmbo*oplcat_first.vmbo + eta_ch4.very.good_oplcat.wo*oplcat_first.wo + eta_ch4.very.good_employment.homemaker*employment_first.homemaker + eta_ch4.very.good_employment.retired*employment_first.retired + eta_ch4.very.good_employment.student*employment_first.student + eta_ch4.very.good_employment.unable.to.work*employment_first.unable.to.work + eta_ch4.very.good_employment.unemployed*employment_first.unemployed
bmi_23.normal.weight ~ alpha_bmi.normal.weight_23*1 + eta_bmi.normal.weight_y1*mhi5_22 + eta_bmi.normal.weight_y2*mhi5_21 + eta_bmi.normal.weight_y3*mhi5_20 + eta_bmi.normal.weight_x0*cs104_23 + eta_bmi.normal.weight_x1*cs104_22 + eta_bmi.normal.weight_leeftijd.18.24*leeftijd_first.18.24 + eta_bmi.normal.weight_leeftijd.25.39*leeftijd_first.25.39 + eta_bmi.normal.weight_leeftijd.40.66*leeftijd_first.40.66 + eta_bmi.normal.weight_leeftijd.over.67*leeftijd_first.over.67 + eta_bmi.normal.weight_nettohh_f.under.15k*nettohh_f_first.under.15k + eta_bmi.normal.weight_nettohh_f.over.50k*nettohh_f_first.over.50k + eta_bmi.normal.weight_herkomstgroep.first.w*herkomstgroep_first.first.w + eta_bmi.normal.weight_herkomstgroep.first.nonw*herkomstgroep_first.first.nonw + eta_bmi.normal.weight_herkomstgroep.second.w*herkomstgroep_first.second.w + eta_bmi.normal.weight_herkomstgroep.second.nonw*herkomstgroep_first.second.nonw + eta_bmi.normal.weight_geslacht.male*geslacht_first.male + eta_bmi.normal.weight_burgstat.married*burgstat_first.married + eta_bmi.normal.weight_burgstat.never.been.married*burgstat_first.never.been.married + eta_bmi.normal.weight_burgstat.separated*burgstat_first.separated + eta_bmi.normal.weight_burgstat.widow.or.widower*burgstat_first.widow.or.widower + eta_bmi.normal.weight_oplcat.hbo*oplcat_first.hbo + eta_bmi.normal.weight_oplcat.mbo*oplcat_first.mbo + eta_bmi.normal.weight_oplcat.primary.school*oplcat_first.primary.school + eta_bmi.normal.weight_oplcat.vmbo*oplcat_first.vmbo + eta_bmi.normal.weight_oplcat.wo*oplcat_first.wo + eta_bmi.normal.weight_employment.homemaker*employment_first.homemaker + eta_bmi.normal.weight_employment.retired*employment_first.retired + eta_bmi.normal.weight_employment.student*employment_first.student + eta_bmi.normal.weight_employment.unable.to.work*employment_first.unable.to.work + eta_bmi.normal.weight_employment.unemployed*employment_first.unemployed
bmi_23.overweight ~ alpha_bmi.overweight_23*1 + eta_bmi.overweight_y1*mhi5_22 + eta_bmi.overweight_y2*mhi5_21 + eta_bmi.overweight_y3*mhi5_20 + eta_bmi.overweight_x0*cs104_23 + eta_bmi.overweight_x1*cs104_22 + eta_bmi.overweight_leeftijd.18.24*leeftijd_first.18.24 + eta_bmi.overweight_leeftijd.25.39*leeftijd_first.25.39 + eta_bmi.overweight_leeftijd.40.66*leeftijd_first.40.66 + eta_bmi.overweight_leeftijd.over.67*leeftijd_first.over.67 + eta_bmi.overweight_nettohh_f.under.15k*nettohh_f_first.under.15k + eta_bmi.overweight_nettohh_f.over.50k*nettohh_f_first.over.50k + eta_bmi.overweight_herkomstgroep.first.w*herkomstgroep_first.first.w + eta_bmi.overweight_herkomstgroep.first.nonw*herkomstgroep_first.first.nonw + eta_bmi.overweight_herkomstgroep.second.w*herkomstgroep_first.second.w + eta_bmi.overweight_herkomstgroep.second.nonw*herkomstgroep_first.second.nonw + eta_bmi.overweight_geslacht.male*geslacht_first.male + eta_bmi.overweight_burgstat.married*burgstat_first.married + eta_bmi.overweight_burgstat.never.been.married*burgstat_first.never.been.married + eta_bmi.overweight_burgstat.separated*burgstat_first.separated + eta_bmi.overweight_burgstat.widow.or.widower*burgstat_first.widow.or.widower + eta_bmi.overweight_oplcat.hbo*oplcat_first.hbo + eta_bmi.overweight_oplcat.mbo*oplcat_first.mbo + eta_bmi.overweight_oplcat.primary.school*oplcat_first.primary.school + eta_bmi.overweight_oplcat.vmbo*oplcat_first.vmbo + eta_bmi.overweight_oplcat.wo*oplcat_first.wo + eta_bmi.overweight_employment.homemaker*employment_first.homemaker + eta_bmi.overweight_employment.retired*employment_first.retired + eta_bmi.overweight_employment.student*employment_first.student + eta_bmi.overweight_employment.unable.to.work*employment_first.unable.to.work + eta_bmi.overweight_employment.unemployed*employment_first.unemployed
bmi_23.obese ~ alpha_bmi.obese_23*1 + eta_bmi.obese_y1*mhi5_22 + eta_bmi.obese_y2*mhi5_21 + eta_bmi.obese_y3*mhi5_20 + eta_bmi.obese_x0*cs104_23 + eta_bmi.obese_x1*cs104_22 + eta_bmi.obese_leeftijd.18.24*leeftijd_first.18.24 + eta_bmi.obese_leeftijd.25.39*leeftijd_first.25.39 + eta_bmi.obese_leeftijd.40.66*leeftijd_first.40.66 + eta_bmi.obese_leeftijd.over.67*leeftijd_first.over.67 + eta_bmi.obese_nettohh_f.under.15k*nettohh_f_first.under.15k + eta_bmi.obese_nettohh_f.over.50k*nettohh_f_first.over.50k + eta_bmi.obese_herkomstgroep.first.w*herkomstgroep_first.first.w + eta_bmi.obese_herkomstgroep.first.nonw*herkomstgroep_first.first.nonw + eta_bmi.obese_herkomstgroep.second.w*herkomstgroep_first.second.w + eta_bmi.obese_herkomstgroep.second.nonw*herkomstgroep_first.second.nonw + eta_bmi.obese_geslacht.male*geslacht_first.male + eta_bmi.obese_burgstat.married*burgstat_first.married + eta_bmi.obese_burgstat.never.been.married*burgstat_first.never.been.married + eta_bmi.obese_burgstat.separated*burgstat_first.separated + eta_bmi.obese_burgstat.widow.or.widower*burgstat_first.widow.or.widower + eta_bmi.obese_oplcat.hbo*oplcat_first.hbo + eta_bmi.obese_oplcat.mbo*oplcat_first.mbo + eta_bmi.obese_oplcat.primary.school*oplcat_first.primary.school + eta_bmi.obese_oplcat.vmbo*oplcat_first.vmbo + eta_bmi.obese_oplcat.wo*oplcat_first.wo + eta_bmi.obese_employment.homemaker*employment_first.homemaker + eta_bmi.obese_employment.retired*employment_first.retired + eta_bmi.obese_employment.student*employment_first.student + eta_bmi.obese_employment.unable.to.work*employment_first.unable.to.work + eta_bmi.obese_employment.unemployed*employment_first.unemployed
ch98_23 ~ alpha_ch98_23*1 + eta_ch98_y1*mhi5_22 + eta_ch98_y2*mhi5_21 + eta_ch98_y3*mhi5_20 + eta_ch98_x0*cs104_23 + eta_ch98_x1*cs104_22 + eta_ch98_leeftijd.18.24*leeftijd_first.18.24 + eta_ch98_leeftijd.25.39*leeftijd_first.25.39 + eta_ch98_leeftijd.40.66*leeftijd_first.40.66 + eta_ch98_leeftijd.over.67*leeftijd_first.over.67 + eta_ch98_nettohh_f.under.15k*nettohh_f_first.under.15k + eta_ch98_nettohh_f.over.50k*nettohh_f_first.over.50k + eta_ch98_herkomstgroep.first.w*herkomstgroep_first.first.w + eta_ch98_herkomstgroep.first.nonw*herkomstgroep_first.first.nonw + eta_ch98_herkomstgroep.second.w*herkomstgroep_first.second.w + eta_ch98_herkomstgroep.second.nonw*herkomstgroep_first.second.nonw + eta_ch98_geslacht.male*geslacht_first.male + eta_ch98_burgstat.married*burgstat_first.married + eta_ch98_burgstat.never.been.married*burgstat_first.never.been.married + eta_ch98_burgstat.separated*burgstat_first.separated + eta_ch98_burgstat.widow.or.widower*burgstat_first.widow.or.widower + eta_ch98_oplcat.hbo*oplcat_first.hbo + eta_ch98_oplcat.mbo*oplcat_first.mbo + eta_ch98_oplcat.primary.school*oplcat_first.primary.school + eta_ch98_oplcat.vmbo*oplcat_first.vmbo + eta_ch98_oplcat.wo*oplcat_first.wo + eta_ch98_employment.homemaker*employment_first.homemaker + eta_ch98_employment.retired*employment_first.retired + eta_ch98_employment.student*employment_first.student + eta_ch98_employment.unable.to.work*employment_first.unable.to.work + eta_ch98_employment.unemployed*employment_first.unemployed

# Additional covariances
ch4_13.good ~~ ch4_13.moderate + ch4_13.poor + ch4_13.very.good
ch4_13.moderate ~~ ch4_13.poor + ch4_13.very.good
ch4_13.poor ~~ ch4_13.very.good
bmi_13.normal.weight ~~ bmi_13.overweight + bmi_13.obese
bmi_13.overweight ~~ bmi_13.obese
ch4_18.good ~~ ch4_18.moderate + ch4_18.poor + ch4_18.very.good
ch4_18.moderate ~~ ch4_18.poor + ch4_18.very.good
ch4_18.poor ~~ ch4_18.very.good
bmi_18.normal.weight ~~ bmi_18.overweight + bmi_18.obese
bmi_18.overweight ~~ bmi_18.obese
ch4_19.good ~~ ch4_19.moderate + ch4_19.poor + ch4_19.very.good
ch4_19.moderate ~~ ch4_19.poor + ch4_19.very.good
ch4_19.poor ~~ ch4_19.very.good
bmi_19.normal.weight ~~ bmi_19.overweight + bmi_19.obese
bmi_19.overweight ~~ bmi_19.obese
ch4_20.good ~~ ch4_20.moderate + ch4_20.poor + ch4_20.very.good
ch4_20.moderate ~~ ch4_20.poor + ch4_20.very.good
ch4_20.poor ~~ ch4_20.very.good
bmi_20.normal.weight ~~ bmi_20.overweight + bmi_20.obese
bmi_20.overweight ~~ bmi_20.obese
ch4_21.good ~~ ch4_21.moderate + ch4_21.poor + ch4_21.very.good
ch4_21.moderate ~~ ch4_21.poor + ch4_21.very.good
ch4_21.poor ~~ ch4_21.very.good
bmi_21.normal.weight ~~ bmi_21.overweight + bmi_21.obese
bmi_21.overweight ~~ bmi_21.obese
ch4_22.good ~~ ch4_22.moderate + ch4_22.poor + ch4_22.very.good
ch4_22.moderate ~~ ch4_22.poor + ch4_22.very.good
ch4_22.poor ~~ ch4_22.very.good
bmi_22.normal.weight ~~ bmi_22.overweight + bmi_22.obese
bmi_22.overweight ~~ bmi_22.obese
ch4_23.good ~~ ch4_23.moderate + ch4_23.poor + ch4_23.very.good
ch4_23.moderate ~~ ch4_23.poor + ch4_23.very.good
ch4_23.poor ~~ ch4_23.very.good
bmi_23.normal.weight ~~ bmi_23.overweight + bmi_23.obese
bmi_23.overweight ~~ bmi_23.obese
bmi_13.normal.weight ~~ bmi_18.normal.weight + bmi_18.obese + bmi_18.overweight + bmi_19.normal.weight + bmi_19.obese + bmi_19.overweight + bmi_20.normal.weight + bmi_20.obese + bmi_20.overweight + bmi_21.normal.weight + bmi_21.obese + bmi_21.overweight + bmi_22.normal.weight + bmi_22.obese + bmi_22.overweight + bmi_23.normal.weight + bmi_23.obese + bmi_23.overweight
bmi_13.obese ~~ bmi_18.normal.weight + bmi_18.obese + bmi_18.overweight + bmi_19.normal.weight + bmi_19.obese + bmi_19.overweight + bmi_20.normal.weight + bmi_20.obese + bmi_20.overweight + bmi_21.normal.weight + bmi_21.obese + bmi_21.overweight + bmi_22.normal.weight + bmi_22.obese + bmi_22.overweight + bmi_23.normal.weight + bmi_23.obese + bmi_23.overweight
bmi_13.overweight ~~ bmi_18.normal.weight + bmi_18.obese + bmi_18.overweight + bmi_19.normal.weight + bmi_19.obese + bmi_19.overweight + bmi_20.normal.weight + bmi_20.obese + bmi_20.overweight + bmi_21.normal.weight + bmi_21.obese + bmi_21.overweight + bmi_22.normal.weight + bmi_22.obese + bmi_22.overweight + bmi_23.normal.weight + bmi_23.obese + bmi_23.overweight
bmi_18.normal.weight ~~ bmi_19.normal.weight + bmi_19.obese + bmi_19.overweight + bmi_20.normal.weight + bmi_20.obese + bmi_20.overweight + bmi_21.normal.weight + bmi_21.obese + bmi_21.overweight + bmi_22.normal.weight + bmi_22.obese + bmi_22.overweight + bmi_23.normal.weight + bmi_23.obese + bmi_23.overweight
bmi_18.obese ~~ bmi_19.normal.weight + bmi_19.obese + bmi_19.overweight + bmi_20.normal.weight + bmi_20.obese + bmi_20.overweight + bmi_21.normal.weight + bmi_21.obese + bmi_21.overweight + bmi_22.normal.weight + bmi_22.obese + bmi_22.overweight + bmi_23.normal.weight + bmi_23.obese + bmi_23.overweight
bmi_18.overweight ~~ bmi_19.normal.weight + bmi_19.obese + bmi_19.overweight + bmi_20.normal.weight + bmi_20.obese + bmi_20.overweight + bmi_21.normal.weight + bmi_21.obese + bmi_21.overweight + bmi_22.normal.weight + bmi_22.obese + bmi_22.overweight + bmi_23.normal.weight + bmi_23.obese + bmi_23.overweight
bmi_19.normal.weight ~~ bmi_20.normal.weight + bmi_20.obese + bmi_20.overweight + bmi_21.normal.weight + bmi_21.obese + bmi_21.overweight + bmi_22.normal.weight + bmi_22.obese + bmi_22.overweight + bmi_23.normal.weight + bmi_23.obese + bmi_23.overweight
bmi_19.obese ~~ bmi_20.normal.weight + bmi_20.obese + bmi_20.overweight + bmi_21.normal.weight + bmi_21.obese + bmi_21.overweight + bmi_22.normal.weight + bmi_22.obese + bmi_22.overweight + bmi_23.normal.weight + bmi_23.obese + bmi_23.overweight
bmi_19.overweight ~~ bmi_20.normal.weight + bmi_20.obese + bmi_20.overweight + bmi_21.normal.weight + bmi_21.obese + bmi_21.overweight + bmi_22.normal.weight + bmi_22.obese + bmi_22.overweight + bmi_23.normal.weight + bmi_23.obese + bmi_23.overweight
bmi_20.normal.weight ~~ bmi_21.normal.weight + bmi_21.obese + bmi_21.overweight + bmi_22.normal.weight + bmi_22.obese + bmi_22.overweight + bmi_23.normal.weight + bmi_23.obese + bmi_23.overweight
bmi_20.obese ~~ bmi_21.normal.weight + bmi_21.obese + bmi_21.overweight + bmi_22.normal.weight + bmi_22.obese + bmi_22.overweight + bmi_23.normal.weight + bmi_23.obese + bmi_23.overweight
bmi_20.overweight ~~ bmi_21.normal.weight + bmi_21.obese + bmi_21.overweight + bmi_22.normal.weight + bmi_22.obese + bmi_22.overweight + bmi_23.normal.weight + bmi_23.obese + bmi_23.overweight
bmi_21.normal.weight ~~ bmi_22.normal.weight + bmi_22.obese + bmi_22.overweight + bmi_23.normal.weight + bmi_23.obese + bmi_23.overweight
bmi_21.obese ~~ bmi_22.normal.weight + bmi_22.obese + bmi_22.overweight + bmi_23.normal.weight + bmi_23.obese + bmi_23.overweight
bmi_21.overweight ~~ bmi_22.normal.weight + bmi_22.obese + bmi_22.overweight + bmi_23.normal.weight + bmi_23.obese + bmi_23.overweight
bmi_22.normal.weight ~~ bmi_23.normal.weight + bmi_23.obese + bmi_23.overweight
bmi_22.obese ~~ bmi_23.normal.weight + bmi_23.obese + bmi_23.overweight
bmi_22.overweight ~~ bmi_23.normal.weight + bmi_23.obese + bmi_23.overweight
ch4_13.good ~~ ch4_18.good + ch4_18.moderate + ch4_18.poor + ch4_18.very.good + ch4_19.good + ch4_19.moderate + ch4_19.poor + ch4_19.very.good + ch4_20.good + ch4_20.moderate + ch4_20.poor + ch4_20.very.good + ch4_21.good + ch4_21.moderate + ch4_21.poor + ch4_21.very.good + ch4_22.good + ch4_22.moderate + ch4_22.poor + ch4_22.very.good + ch4_23.good + ch4_23.moderate + ch4_23.poor + ch4_23.very.good
ch4_13.moderate ~~ ch4_18.good + ch4_18.moderate + ch4_18.poor + ch4_18.very.good + ch4_19.good + ch4_19.moderate + ch4_19.poor + ch4_19.very.good + ch4_20.good + ch4_20.moderate + ch4_20.poor + ch4_20.very.good + ch4_21.good + ch4_21.moderate + ch4_21.poor + ch4_21.very.good + ch4_22.good + ch4_22.moderate + ch4_22.poor + ch4_22.very.good + ch4_23.good + ch4_23.moderate + ch4_23.poor + ch4_23.very.good
ch4_13.poor ~~ ch4_18.good + ch4_18.moderate + ch4_18.poor + ch4_18.very.good + ch4_19.good + ch4_19.moderate + ch4_19.poor + ch4_19.very.good + ch4_20.good + ch4_20.moderate + ch4_20.poor + ch4_20.very.good + ch4_21.good + ch4_21.moderate + ch4_21.poor + ch4_21.very.good + ch4_22.good + ch4_22.moderate + ch4_22.poor + ch4_22.very.good + ch4_23.good + ch4_23.moderate + ch4_23.poor + ch4_23.very.good
ch4_13.very.good ~~ ch4_18.good + ch4_18.moderate + ch4_18.poor + ch4_18.very.good + ch4_19.good + ch4_19.moderate + ch4_19.poor + ch4_19.very.good + ch4_20.good + ch4_20.moderate + ch4_20.poor + ch4_20.very.good + ch4_21.good + ch4_21.moderate + ch4_21.poor + ch4_21.very.good + ch4_22.good + ch4_22.moderate + ch4_22.poor + ch4_22.very.good + ch4_23.good + ch4_23.moderate + ch4_23.poor + ch4_23.very.good
ch4_18.good ~~ ch4_19.good + ch4_19.moderate + ch4_19.poor + ch4_19.very.good + ch4_20.good + ch4_20.moderate + ch4_20.poor + ch4_20.very.good + ch4_21.good + ch4_21.moderate + ch4_21.poor + ch4_21.very.good + ch4_22.good + ch4_22.moderate + ch4_22.poor + ch4_22.very.good + ch4_23.good + ch4_23.moderate + ch4_23.poor + ch4_23.very.good
ch4_18.moderate ~~ ch4_19.good + ch4_19.moderate + ch4_19.poor + ch4_19.very.good + ch4_20.good + ch4_20.moderate + ch4_20.poor + ch4_20.very.good + ch4_21.good + ch4_21.moderate + ch4_21.poor + ch4_21.very.good + ch4_22.good + ch4_22.moderate + ch4_22.poor + ch4_22.very.good + ch4_23.good + ch4_23.moderate + ch4_23.poor + ch4_23.very.good
ch4_18.poor ~~ ch4_19.good + ch4_19.moderate + ch4_19.poor + ch4_19.very.good + ch4_20.good + ch4_20.moderate + ch4_20.poor + ch4_20.very.good + ch4_21.good + ch4_21.moderate + ch4_21.poor + ch4_21.very.good + ch4_22.good + ch4_22.moderate + ch4_22.poor + ch4_22.very.good + ch4_23.good + ch4_23.moderate + ch4_23.poor + ch4_23.very.good
ch4_18.very.good ~~ ch4_19.good + ch4_19.moderate + ch4_19.poor + ch4_19.very.good + ch4_20.good + ch4_20.moderate + ch4_20.poor + ch4_20.very.good + ch4_21.good + ch4_21.moderate + ch4_21.poor + ch4_21.very.good + ch4_22.good + ch4_22.moderate + ch4_22.poor + ch4_22.very.good + ch4_23.good + ch4_23.moderate + ch4_23.poor + ch4_23.very.good
ch4_19.good ~~ ch4_20.good + ch4_20.moderate + ch4_20.poor + ch4_20.very.good + ch4_21.good + ch4_21.moderate + ch4_21.poor + ch4_21.very.good + ch4_22.good + ch4_22.moderate + ch4_22.poor + ch4_22.very.good + ch4_23.good + ch4_23.moderate + ch4_23.poor + ch4_23.very.good
ch4_19.moderate ~~ ch4_20.good + ch4_20.moderate + ch4_20.poor + ch4_20.very.good + ch4_21.good + ch4_21.moderate + ch4_21.poor + ch4_21.very.good + ch4_22.good + ch4_22.moderate + ch4_22.poor + ch4_22.very.good + ch4_23.good + ch4_23.moderate + ch4_23.poor + ch4_23.very.good
ch4_19.poor ~~ ch4_20.good + ch4_20.moderate + ch4_20.poor + ch4_20.very.good + ch4_21.good + ch4_21.moderate + ch4_21.poor + ch4_21.very.good + ch4_22.good + ch4_22.moderate + ch4_22.poor + ch4_22.very.good + ch4_23.good + ch4_23.moderate + ch4_23.poor + ch4_23.very.good
ch4_19.very.good ~~ ch4_20.good + ch4_20.moderate + ch4_20.poor + ch4_20.very.good + ch4_21.good + ch4_21.moderate + ch4_21.poor + ch4_21.very.good + ch4_22.good + ch4_22.moderate + ch4_22.poor + ch4_22.very.good + ch4_23.good + ch4_23.moderate + ch4_23.poor + ch4_23.very.good
ch4_20.good ~~ ch4_21.good + ch4_21.moderate + ch4_21.poor + ch4_21.very.good + ch4_22.good + ch4_22.moderate + ch4_22.poor + ch4_22.very.good + ch4_23.good + ch4_23.moderate + ch4_23.poor + ch4_23.very.good
ch4_20.moderate ~~ ch4_21.good + ch4_21.moderate + ch4_21.poor + ch4_21.very.good + ch4_22.good + ch4_22.moderate + ch4_22.poor + ch4_22.very.good + ch4_23.good + ch4_23.moderate + ch4_23.poor + ch4_23.very.good
ch4_20.poor ~~ ch4_21.good + ch4_21.moderate + ch4_21.poor + ch4_21.very.good + ch4_22.good + ch4_22.moderate + ch4_22.poor + ch4_22.very.good + ch4_23.good + ch4_23.moderate + ch4_23.poor + ch4_23.very.good
ch4_20.very.good ~~ ch4_21.good + ch4_21.moderate + ch4_21.poor + ch4_21.very.good + ch4_22.good + ch4_22.moderate + ch4_22.poor + ch4_22.very.good + ch4_23.good + ch4_23.moderate + ch4_23.poor + ch4_23.very.good
ch4_21.good ~~ ch4_22.good + ch4_22.moderate + ch4_22.poor + ch4_22.very.good + ch4_23.good + ch4_23.moderate + ch4_23.poor + ch4_23.very.good
ch4_21.moderate ~~ ch4_22.good + ch4_22.moderate + ch4_22.poor + ch4_22.very.good + ch4_23.good + ch4_23.moderate + ch4_23.poor + ch4_23.very.good
ch4_21.poor ~~ ch4_22.good + ch4_22.moderate + ch4_22.poor + ch4_22.very.good + ch4_23.good + ch4_23.moderate + ch4_23.poor + ch4_23.very.good
ch4_21.very.good ~~ ch4_22.good + ch4_22.moderate + ch4_22.poor + ch4_22.very.good + ch4_23.good + ch4_23.moderate + ch4_23.poor + ch4_23.very.good
ch4_22.good ~~ ch4_23.good + ch4_23.moderate + ch4_23.poor + ch4_23.very.good
ch4_22.moderate ~~ ch4_23.good + ch4_23.moderate + ch4_23.poor + ch4_23.very.good
ch4_22.poor ~~ ch4_23.good + ch4_23.moderate + ch4_23.poor + ch4_23.very.good
ch4_22.very.good ~~ ch4_23.good + ch4_23.moderate + ch4_23.poor + ch4_23.very.good
ch98_13 ~~ ch98_18 + ch98_19 + ch98_20 + ch98_21 + ch98_22 + ch98_23
ch98_18 ~~ ch98_19 + ch98_20 + ch98_21 + ch98_22 + ch98_23
ch98_19 ~~ ch98_20 + ch98_21 + ch98_22 + ch98_23
ch98_20 ~~ ch98_21 + ch98_22 + ch98_23
ch98_21 ~~ ch98_22 + ch98_23
ch98_22 ~~ ch98_23

"

# Manually adding the extra regressors to make the mediation lagged
sem_model_mediation <- paste(sem_model_mediation, "
# Add lagged mediators in main regressions
mhi5_13 ~ zeta1_ch98*ch98_12 + zeta1_ch4.good*ch4_12.good + zeta1_ch4.moderate*ch4_12.moderate + zeta1_ch4.poor*ch4_12.poor + zeta1_ch4.very.good*ch4_12.very.good + zeta1_bmi_normal.weight*bmi_12.normal.weight + zeta1_bmi_overweight*bmi_12.overweight + zeta1_bmi_obese*bmi_12.obese
mhi5_18 ~ zeta1_ch98*ch98_17 + zeta1_ch4.good*ch4_17.good + zeta1_ch4.moderate*ch4_17.moderate + zeta1_ch4.poor*ch4_17.poor + zeta1_ch4.very.good*ch4_17.very.good + zeta1_bmi_normal.weight*bmi_17.normal.weight + zeta1_bmi_overweight*bmi_17.overweight + zeta1_bmi_obese*bmi_17.obese
mhi5_19 ~ zeta1_ch98*ch98_18 + zeta1_ch4.good*ch4_18.good + zeta1_ch4.moderate*ch4_18.moderate + zeta1_ch4.poor*ch4_18.poor + zeta1_ch4.very.good*ch4_18.very.good + zeta1_bmi_normal.weight*bmi_18.normal.weight + zeta1_bmi_overweight*bmi_18.overweight + zeta1_bmi_obese*bmi_18.obese
mhi5_20 ~ zeta1_ch98*ch98_19 + zeta1_ch4.good*ch4_19.good + zeta1_ch4.moderate*ch4_19.moderate + zeta1_ch4.poor*ch4_19.poor + zeta1_ch4.very.good*ch4_19.very.good + zeta1_bmi_normal.weight*bmi_19.normal.weight + zeta1_bmi_overweight*bmi_19.overweight + zeta1_bmi_obese*bmi_19.obese
mhi5_21 ~ zeta1_ch98*ch98_20 + zeta1_ch4.good*ch4_20.good + zeta1_ch4.moderate*ch4_20.moderate + zeta1_ch4.poor*ch4_20.poor + zeta1_ch4.very.good*ch4_20.very.good + zeta1_bmi_normal.weight*bmi_20.normal.weight + zeta1_bmi_overweight*bmi_20.overweight + zeta1_bmi_obese*bmi_20.obese
mhi5_22 ~ zeta1_ch98*ch98_21 + zeta1_ch4.good*ch4_21.good + zeta1_ch4.moderate*ch4_21.moderate + zeta1_ch4.poor*ch4_21.poor + zeta1_ch4.very.good*ch4_21.very.good + zeta1_bmi_normal.weight*bmi_21.normal.weight + zeta1_bmi_overweight*bmi_21.overweight + zeta1_bmi_obese*bmi_21.obese
mhi5_23 ~ zeta1_ch98*ch98_22 + zeta1_ch4.good*ch4_22.good + zeta1_ch4.moderate*ch4_22.moderate + zeta1_ch4.poor*ch4_22.poor + zeta1_ch4.very.good*ch4_22.very.good + zeta1_bmi_normal.weight*bmi_22.normal.weight + zeta1_bmi_overweight*bmi_22.overweight + zeta1_bmi_obese*bmi_22.obese

# Add additional covariances for extra introduced mediators
#ch98_12 ~~ gamma0_ch98_ch4.good*ch4_12.good + gamma0_ch98_ch4.moderate*ch4_12.moderate + gamma0_ch98_ch4.poor*ch4_12.poor + gamma0_ch98_ch4.very.good*ch4_12.very.good + gamma0_ch98_bmi.normal.weight*bmi_12.normal.weight + gamma0_ch98_bmi.overweight*bmi_12.overweight + gamma0_ch98_bmi.obese*bmi_12.obese
#ch4_12.good ~~ gamma0_ch4.good_ch4.moderate*ch4_12.moderate + gamma0_ch4.good_ch4.poor*ch4_12.poor + gamma0_ch4.good_ch4.very.good*ch4_12.very.good + gamma0_ch4.good_bmi.normal.weight*bmi_12.normal.weight + gamma0_ch4.good_bmi.overweight*bmi_12.overweight + gamma0_ch4.good_bmi.obese*bmi_12.obese
#ch4_12.moderate ~~ gamma0_ch4.moderate_ch4.poor*ch4_12.poor + gamma0_ch4.moderate_ch4.very.good*ch4_12.very.good + gamma0_ch4.moderate_bmi.normal.weight*bmi_12.normal.weight + gamma0_ch4.moderate_bmi.overweight*bmi_12.overweight + gamma0_ch4.moderate_bmi.obese*bmi_12.obese
#ch4_12.poor ~~ gamma0_ch4.poor_ch4.very.good*ch4_12.very.good + gamma0_ch4.poor_bmi.normal.weight*bmi_12.normal.weight + gamma0_ch4.poor_bmi.overweight*bmi_12.overweight + gamma0_ch4.poor_bmi.obese*bmi_12.obese
#bmi_12.normal.weight ~~ gamma0_bmi.normal.weight_bmi.overweight*bmi_12.overweight + gamma0_bmi.normal.weight_bmi.obese*bmi_12.obese
#bmi_12.overweight ~~ gamma0_bmi.overweight_bmi.obese*bmi_12.obese

ch4_12.good ~~ ch4_13.good + ch4_13.moderate + ch4_13.poor + ch4_13.very.good + ch4_17.good + ch4_17.moderate + ch4_17.poor + ch4_17.very.good + ch4_18.good + ch4_18.moderate + ch4_18.poor + ch4_18.very.good + ch4_19.good + ch4_19.moderate + ch4_19.poor + ch4_19.very.good + ch4_20.good + ch4_20.moderate + ch4_20.poor + ch4_20.very.good + ch4_21.good + ch4_21.moderate + ch4_21.poor + ch4_21.very.good + ch4_22.good + ch4_22.moderate + ch4_22.poor + ch4_22.very.good + ch4_23.good + ch4_23.moderate + ch4_23.poor + ch4_23.very.good
ch4_12.moderate ~~ ch4_13.good + ch4_13.moderate + ch4_13.poor + ch4_13.very.good + ch4_17.good + ch4_17.moderate + ch4_17.poor + ch4_17.very.good + ch4_18.good + ch4_18.moderate + ch4_18.poor + ch4_18.very.good + ch4_19.good + ch4_19.moderate + ch4_19.poor + ch4_19.very.good + ch4_20.good + ch4_20.moderate + ch4_20.poor + ch4_20.very.good + ch4_21.good + ch4_21.moderate + ch4_21.poor + ch4_21.very.good + ch4_22.good + ch4_22.moderate + ch4_22.poor + ch4_22.very.good + ch4_23.good + ch4_23.moderate + ch4_23.poor + ch4_23.very.good
ch4_12.poor ~~ ch4_13.good + ch4_13.moderate + ch4_13.poor + ch4_13.very.good + ch4_17.good + ch4_17.moderate + ch4_17.poor + ch4_17.very.good + ch4_18.good + ch4_18.moderate + ch4_18.poor + ch4_18.very.good + ch4_19.good + ch4_19.moderate + ch4_19.poor + ch4_19.very.good + ch4_20.good + ch4_20.moderate + ch4_20.poor + ch4_20.very.good + ch4_21.good + ch4_21.moderate + ch4_21.poor + ch4_21.very.good + ch4_22.good + ch4_22.moderate + ch4_22.poor + ch4_22.very.good + ch4_23.good + ch4_23.moderate + ch4_23.poor + ch4_23.very.good
ch4_12.very.good ~~ ch4_13.good + ch4_13.moderate + ch4_13.poor + ch4_13.very.good + ch4_17.good + ch4_17.moderate + ch4_17.poor + ch4_17.very.good + ch4_18.good + ch4_18.moderate + ch4_18.poor + ch4_18.very.good + ch4_19.good + ch4_19.moderate + ch4_19.poor + ch4_19.very.good + ch4_20.good + ch4_20.moderate + ch4_20.poor + ch4_20.very.good + ch4_21.good + ch4_21.moderate + ch4_21.poor + ch4_21.very.good + ch4_22.good + ch4_22.moderate + ch4_22.poor + ch4_22.very.good + ch4_23.good + ch4_23.moderate + ch4_23.poor + ch4_23.very.good
bmi_12.normal.weight ~~ bmi_13.normal.weight + bmi_13.obese + bmi_13.overweight + bmi_18.normal.weight + bmi_18.obese + bmi_18.overweight + bmi_19.normal.weight + bmi_19.obese + bmi_19.overweight + bmi_20.normal.weight + bmi_20.obese + bmi_20.overweight + bmi_21.normal.weight + bmi_21.obese + bmi_21.overweight + bmi_22.normal.weight + bmi_22.obese + bmi_22.overweight + bmi_23.normal.weight + bmi_23.obese + bmi_23.overweight
bmi_12.obese ~~ bmi_13.normal.weight + bmi_13.obese + bmi_13.overweight + bmi_18.normal.weight + bmi_18.obese + bmi_18.overweight + bmi_19.normal.weight + bmi_19.obese + bmi_19.overweight + bmi_20.normal.weight + bmi_20.obese + bmi_20.overweight + bmi_21.normal.weight + bmi_21.obese + bmi_21.overweight + bmi_22.normal.weight + bmi_22.obese + bmi_22.overweight + bmi_23.normal.weight + bmi_23.obese + bmi_23.overweight
bmi_12.overweight ~~ bmi_13.normal.weight + bmi_13.obese + bmi_13.overweight + bmi_18.normal.weight + bmi_18.obese + bmi_18.overweight + bmi_19.normal.weight + bmi_19.obese + bmi_19.overweight + bmi_20.normal.weight + bmi_20.obese + bmi_20.overweight + bmi_21.normal.weight + bmi_21.obese + bmi_21.overweight + bmi_22.normal.weight + bmi_22.obese + bmi_22.overweight + bmi_23.normal.weight + bmi_23.obese + bmi_23.overweight
ch98_12 ~~ ch98_13 + ch98_17 + ch98_18 + ch98_19 + ch98_20 + ch98_21 + ch98_22 + ch98_23

")

# Manually adding the total effect calculation
sem_model_mediation <- paste(sem_model_mediation, "
direct := beta1_cs104

indirect_disease := eta_ch98_x1 * zeta1_ch98

indirect_ch4_good := eta_ch4.good_x1 * zeta1_ch4.good
indirect_ch4_moderate := eta_ch4.moderate_x1 * zeta1_ch4.moderate
indirect_ch4_poor := eta_ch4.poor_x1 * zeta1_ch4.poor
indirect_ch4_very.good := eta_ch4.very.good_x1 * zeta1_ch4.very.good
indirect_ch4 := indirect_ch4_good + indirect_ch4_moderate + indirect_ch4_poor + indirect_ch4_very.good

indirect_bmi_normal := eta_bmi.normal.weight_x1 * zeta1_bmi_normal.weight
indirect_bmi_overweight := eta_bmi.overweight_x1 * zeta1_bmi_overweight
indirect_bmi_obese := eta_bmi.obese_x1 * zeta1_bmi_obese
indirect_bmi := indirect_bmi_normal + indirect_bmi_overweight + indirect_bmi_obese

total := direct + indirect_disease + indirect_ch4 + indirect_bmi

")
```

```{r Fit mediation model}
fit_mediation <- sem(sem_model_mediation, data = all_data, estimator = "MLR", missing = "fiml.x")

summary(fit_mediation, fit.measures = TRUE)
```

```{r Cross validation function}
n_fold <- 5

cv <- function(model, do_print) {
    folds <- vfold_cv(all_data, v = n_fold)

    results <- numeric(n_fold)

    for (i in seq_along(folds$splits)) {
        split <- folds$splits[[i]]
        train_split <- analysis(split)
        test_split <- assessment(split)

        fold_successful <- FALSE

        tryCatch(
            {
                # No fiml.x because ho lee that takes five and a half years to run.
                fold_fit <- suppressWarnings(sem(model, train_split, estimator = "MLR", missing = "fiml"))

                predictions <- as.data.frame(lavPredictY(fold_fit, test_split, ynames = lavNames(fold_fit, "eqs.y")))
                actual <- test_split[, names(predictions)]

                if (do_print && i == 1) {
                    cat("Regressands:", names(predictions), "\n")
                }

                differences <- actual - predictions

                # The RMSPE of each regressand
                rmspes <- sapply(differences, function(col) {
                    sqrt(mean(col^2, na.rm = TRUE))
                })

                if (do_print) {
                    cat("Fold", i, "/", n_fold, "RMSPEs:", rmspes, "\n")
                }

                results[[i]] <- mean(rmspes)

                fold_successful <- TRUE
            },
            error = function(error) {
                warning(error)
                cat("Fold", i, "estimation failed\n")
            }
        )

        if (!fold_successful) {
            return(NA)
        }
    }

    c(mean(results), sd(results))
}
```

```{r CV models}
cv_models_AR <- c(
    "
# Regressions
mhi5_23 ~ alpha_mhi5_23*1 + rho1*mhi5_22 + beta0_cs104*cs104_23 + beta1_cs104*cs104_22 + omega0_ch4.good*ch4_23.good + omega0_ch4.moderate*ch4_23.moderate + omega0_ch4.poor*ch4_23.poor + omega0_ch4.very.good*ch4_23.very.good + omega0_ch98*ch98_23 + delta_leeftijd.18.24*leeftijd_first.18.24 + delta_leeftijd.25.39*leeftijd_first.25.39 + delta_leeftijd.40.66*leeftijd_first.40.66 + delta_leeftijd.over.67*leeftijd_first.over.67 + delta_nettohh_f.under.15k*nettohh_f_first.under.15k + delta_nettohh_f.over.50k*nettohh_f_first.over.50k + delta_herkomstgroep.first.w*herkomstgroep_first.first.w + delta_herkomstgroep.first.nonw*herkomstgroep_first.first.nonw + delta_herkomstgroep.second.w*herkomstgroep_first.second.w + delta_herkomstgroep.second.nonw*herkomstgroep_first.second.nonw + delta_geslacht.male*geslacht_first.male + delta_burgstat.married*burgstat_first.married + delta_burgstat.never.been.married*burgstat_first.never.been.married + delta_burgstat.separated*burgstat_first.separated + delta_burgstat.widow.or.widower*burgstat_first.widow.or.widower + delta_oplcat.hbo*oplcat_first.hbo + delta_oplcat.mbo*oplcat_first.mbo + delta_oplcat.primary.school*oplcat_first.primary.school + delta_oplcat.vmbo*oplcat_first.vmbo + delta_oplcat.wo*oplcat_first.wo + delta_employment.homemaker*employment_first.homemaker + delta_employment.retired*employment_first.retired + delta_employment.student*employment_first.student + delta_employment.unable.to.work*employment_first.unable.to.work + delta_employment.unemployed*employment_first.unemployed

", "
# Regressions
mhi5_23 ~ alpha_mhi5_23*1 + rho1*mhi5_22 + rho2*mhi5_21 + beta0_cs104*cs104_23 + beta1_cs104*cs104_22 + omega0_ch4.good*ch4_23.good + omega0_ch4.moderate*ch4_23.moderate + omega0_ch4.poor*ch4_23.poor + omega0_ch4.very.good*ch4_23.very.good + omega0_ch98*ch98_23 + delta_leeftijd.18.24*leeftijd_first.18.24 + delta_leeftijd.25.39*leeftijd_first.25.39 + delta_leeftijd.40.66*leeftijd_first.40.66 + delta_leeftijd.over.67*leeftijd_first.over.67 + delta_nettohh_f.under.15k*nettohh_f_first.under.15k + delta_nettohh_f.over.50k*nettohh_f_first.over.50k + delta_herkomstgroep.first.w*herkomstgroep_first.first.w + delta_herkomstgroep.first.nonw*herkomstgroep_first.first.nonw + delta_herkomstgroep.second.w*herkomstgroep_first.second.w + delta_herkomstgroep.second.nonw*herkomstgroep_first.second.nonw + delta_geslacht.male*geslacht_first.male + delta_burgstat.married*burgstat_first.married + delta_burgstat.never.been.married*burgstat_first.never.been.married + delta_burgstat.separated*burgstat_first.separated + delta_burgstat.widow.or.widower*burgstat_first.widow.or.widower + delta_oplcat.hbo*oplcat_first.hbo + delta_oplcat.mbo*oplcat_first.mbo + delta_oplcat.primary.school*oplcat_first.primary.school + delta_oplcat.vmbo*oplcat_first.vmbo + delta_oplcat.wo*oplcat_first.wo + delta_employment.homemaker*employment_first.homemaker + delta_employment.retired*employment_first.retired + delta_employment.student*employment_first.student + delta_employment.unable.to.work*employment_first.unable.to.work + delta_employment.unemployed*employment_first.unemployed

", "
# Regressions
mhi5_23 ~ alpha_mhi5_23*1 + rho1*mhi5_22 + rho2*mhi5_21 + rho3*mhi5_20 + beta0_cs104*cs104_23 + beta1_cs104*cs104_22 + omega0_ch4.good*ch4_23.good + omega0_ch4.moderate*ch4_23.moderate + omega0_ch4.poor*ch4_23.poor + omega0_ch4.very.good*ch4_23.very.good + omega0_ch98*ch98_23 + delta_leeftijd.18.24*leeftijd_first.18.24 + delta_leeftijd.25.39*leeftijd_first.25.39 + delta_leeftijd.40.66*leeftijd_first.40.66 + delta_leeftijd.over.67*leeftijd_first.over.67 + delta_nettohh_f.under.15k*nettohh_f_first.under.15k + delta_nettohh_f.over.50k*nettohh_f_first.over.50k + delta_herkomstgroep.first.w*herkomstgroep_first.first.w + delta_herkomstgroep.first.nonw*herkomstgroep_first.first.nonw + delta_herkomstgroep.second.w*herkomstgroep_first.second.w + delta_herkomstgroep.second.nonw*herkomstgroep_first.second.nonw + delta_geslacht.male*geslacht_first.male + delta_burgstat.married*burgstat_first.married + delta_burgstat.never.been.married*burgstat_first.never.been.married + delta_burgstat.separated*burgstat_first.separated + delta_burgstat.widow.or.widower*burgstat_first.widow.or.widower + delta_oplcat.hbo*oplcat_first.hbo + delta_oplcat.mbo*oplcat_first.mbo + delta_oplcat.primary.school*oplcat_first.primary.school + delta_oplcat.vmbo*oplcat_first.vmbo + delta_oplcat.wo*oplcat_first.wo + delta_employment.homemaker*employment_first.homemaker + delta_employment.retired*employment_first.retired + delta_employment.student*employment_first.student + delta_employment.unable.to.work*employment_first.unable.to.work + delta_employment.unemployed*employment_first.unemployed

", "
# Regressions
mhi5_23 ~ alpha_mhi5_23*1 + rho1*mhi5_22 + rho2*mhi5_21 + rho3*mhi5_20 + rho4*mhi5_19 + beta0_cs104*cs104_23 + beta1_cs104*cs104_22 + omega0_ch4.good*ch4_23.good + omega0_ch4.moderate*ch4_23.moderate + omega0_ch4.poor*ch4_23.poor + omega0_ch4.very.good*ch4_23.very.good + omega0_ch98*ch98_23 + delta_leeftijd.18.24*leeftijd_first.18.24 + delta_leeftijd.25.39*leeftijd_first.25.39 + delta_leeftijd.40.66*leeftijd_first.40.66 + delta_leeftijd.over.67*leeftijd_first.over.67 + delta_nettohh_f.under.15k*nettohh_f_first.under.15k + delta_nettohh_f.over.50k*nettohh_f_first.over.50k + delta_herkomstgroep.first.w*herkomstgroep_first.first.w + delta_herkomstgroep.first.nonw*herkomstgroep_first.first.nonw + delta_herkomstgroep.second.w*herkomstgroep_first.second.w + delta_herkomstgroep.second.nonw*herkomstgroep_first.second.nonw + delta_geslacht.male*geslacht_first.male + delta_burgstat.married*burgstat_first.married + delta_burgstat.never.been.married*burgstat_first.never.been.married + delta_burgstat.separated*burgstat_first.separated + delta_burgstat.widow.or.widower*burgstat_first.widow.or.widower + delta_oplcat.hbo*oplcat_first.hbo + delta_oplcat.mbo*oplcat_first.mbo + delta_oplcat.primary.school*oplcat_first.primary.school + delta_oplcat.vmbo*oplcat_first.vmbo + delta_oplcat.wo*oplcat_first.wo + delta_employment.homemaker*employment_first.homemaker + delta_employment.retired*employment_first.retired + delta_employment.student*employment_first.student + delta_employment.unable.to.work*employment_first.unable.to.work + delta_employment.unemployed*employment_first.unemployed

", "
# Regressions
mhi5_23 ~ alpha_mhi5_23*1 + rho1*mhi5_22 + rho2*mhi5_21 + rho3*mhi5_20 + rho4*mhi5_19 + rho5*mhi5_18 + beta0_cs104*cs104_23 + beta1_cs104*cs104_22 + omega0_ch4.good*ch4_23.good + omega0_ch4.moderate*ch4_23.moderate + omega0_ch4.poor*ch4_23.poor + omega0_ch4.very.good*ch4_23.very.good + omega0_ch98*ch98_23 + delta_leeftijd.18.24*leeftijd_first.18.24 + delta_leeftijd.25.39*leeftijd_first.25.39 + delta_leeftijd.40.66*leeftijd_first.40.66 + delta_leeftijd.over.67*leeftijd_first.over.67 + delta_nettohh_f.under.15k*nettohh_f_first.under.15k + delta_nettohh_f.over.50k*nettohh_f_first.over.50k + delta_herkomstgroep.first.w*herkomstgroep_first.first.w + delta_herkomstgroep.first.nonw*herkomstgroep_first.first.nonw + delta_herkomstgroep.second.w*herkomstgroep_first.second.w + delta_herkomstgroep.second.nonw*herkomstgroep_first.second.nonw + delta_geslacht.male*geslacht_first.male + delta_burgstat.married*burgstat_first.married + delta_burgstat.never.been.married*burgstat_first.never.been.married + delta_burgstat.separated*burgstat_first.separated + delta_burgstat.widow.or.widower*burgstat_first.widow.or.widower + delta_oplcat.hbo*oplcat_first.hbo + delta_oplcat.mbo*oplcat_first.mbo + delta_oplcat.primary.school*oplcat_first.primary.school + delta_oplcat.vmbo*oplcat_first.vmbo + delta_oplcat.wo*oplcat_first.wo + delta_employment.homemaker*employment_first.homemaker + delta_employment.retired*employment_first.retired + delta_employment.student*employment_first.student + delta_employment.unable.to.work*employment_first.unable.to.work + delta_employment.unemployed*employment_first.unemployed

", "
# Regressions
mhi5_23 ~ alpha_mhi5_23*1 + rho1*mhi5_22 + rho2*mhi5_21 + rho3*mhi5_20 + rho4*mhi5_19 + rho5*mhi5_18 + rho6*mhi5_17 + beta0_cs104*cs104_23 + beta1_cs104*cs104_22 + omega0_ch4.good*ch4_23.good + omega0_ch4.moderate*ch4_23.moderate + omega0_ch4.poor*ch4_23.poor + omega0_ch4.very.good*ch4_23.very.good + omega0_ch98*ch98_23 + delta_leeftijd.18.24*leeftijd_first.18.24 + delta_leeftijd.25.39*leeftijd_first.25.39 + delta_leeftijd.40.66*leeftijd_first.40.66 + delta_leeftijd.over.67*leeftijd_first.over.67 + delta_nettohh_f.under.15k*nettohh_f_first.under.15k + delta_nettohh_f.over.50k*nettohh_f_first.over.50k + delta_herkomstgroep.first.w*herkomstgroep_first.first.w + delta_herkomstgroep.first.nonw*herkomstgroep_first.first.nonw + delta_herkomstgroep.second.w*herkomstgroep_first.second.w + delta_herkomstgroep.second.nonw*herkomstgroep_first.second.nonw + delta_geslacht.male*geslacht_first.male + delta_burgstat.married*burgstat_first.married + delta_burgstat.never.been.married*burgstat_first.never.been.married + delta_burgstat.separated*burgstat_first.separated + delta_burgstat.widow.or.widower*burgstat_first.widow.or.widower + delta_oplcat.hbo*oplcat_first.hbo + delta_oplcat.mbo*oplcat_first.mbo + delta_oplcat.primary.school*oplcat_first.primary.school + delta_oplcat.vmbo*oplcat_first.vmbo + delta_oplcat.wo*oplcat_first.wo + delta_employment.homemaker*employment_first.homemaker + delta_employment.retired*employment_first.retired + delta_employment.student*employment_first.student + delta_employment.unable.to.work*employment_first.unable.to.work + delta_employment.unemployed*employment_first.unemployed

", "
# Regressions
mhi5_23 ~ alpha_mhi5_23*1 + rho1*mhi5_22 + rho2*mhi5_21 + rho3*mhi5_20 + rho4*mhi5_19 + rho5*mhi5_18 + rho6*mhi5_17 + rho7*mhi5_16 + beta0_cs104*cs104_23 + beta1_cs104*cs104_22 + omega0_ch4.good*ch4_23.good + omega0_ch4.moderate*ch4_23.moderate + omega0_ch4.poor*ch4_23.poor + omega0_ch4.very.good*ch4_23.very.good + omega0_ch98*ch98_23 + delta_leeftijd.18.24*leeftijd_first.18.24 + delta_leeftijd.25.39*leeftijd_first.25.39 + delta_leeftijd.40.66*leeftijd_first.40.66 + delta_leeftijd.over.67*leeftijd_first.over.67 + delta_nettohh_f.under.15k*nettohh_f_first.under.15k + delta_nettohh_f.over.50k*nettohh_f_first.over.50k + delta_herkomstgroep.first.w*herkomstgroep_first.first.w + delta_herkomstgroep.first.nonw*herkomstgroep_first.first.nonw + delta_herkomstgroep.second.w*herkomstgroep_first.second.w + delta_herkomstgroep.second.nonw*herkomstgroep_first.second.nonw + delta_geslacht.male*geslacht_first.male + delta_burgstat.married*burgstat_first.married + delta_burgstat.never.been.married*burgstat_first.never.been.married + delta_burgstat.separated*burgstat_first.separated + delta_burgstat.widow.or.widower*burgstat_first.widow.or.widower + delta_oplcat.hbo*oplcat_first.hbo + delta_oplcat.mbo*oplcat_first.mbo + delta_oplcat.primary.school*oplcat_first.primary.school + delta_oplcat.vmbo*oplcat_first.vmbo + delta_oplcat.wo*oplcat_first.wo + delta_employment.homemaker*employment_first.homemaker + delta_employment.retired*employment_first.retired + delta_employment.student*employment_first.student + delta_employment.unable.to.work*employment_first.unable.to.work + delta_employment.unemployed*employment_first.unemployed

", "
# Regressions
mhi5_23 ~ alpha_mhi5_23*1 + rho1*mhi5_22 + rho2*mhi5_21 + rho3*mhi5_20 + rho4*mhi5_19 + rho5*mhi5_18 + rho6*mhi5_17 + rho7*mhi5_16 + rho8*mhi5_15 + beta0_cs104*cs104_23 + beta1_cs104*cs104_22 + omega0_ch4.good*ch4_23.good + omega0_ch4.moderate*ch4_23.moderate + omega0_ch4.poor*ch4_23.poor + omega0_ch4.very.good*ch4_23.very.good + omega0_ch98*ch98_23 + delta_leeftijd.18.24*leeftijd_first.18.24 + delta_leeftijd.25.39*leeftijd_first.25.39 + delta_leeftijd.40.66*leeftijd_first.40.66 + delta_leeftijd.over.67*leeftijd_first.over.67 + delta_nettohh_f.under.15k*nettohh_f_first.under.15k + delta_nettohh_f.over.50k*nettohh_f_first.over.50k + delta_herkomstgroep.first.w*herkomstgroep_first.first.w + delta_herkomstgroep.first.nonw*herkomstgroep_first.first.nonw + delta_herkomstgroep.second.w*herkomstgroep_first.second.w + delta_herkomstgroep.second.nonw*herkomstgroep_first.second.nonw + delta_geslacht.male*geslacht_first.male + delta_burgstat.married*burgstat_first.married + delta_burgstat.never.been.married*burgstat_first.never.been.married + delta_burgstat.separated*burgstat_first.separated + delta_burgstat.widow.or.widower*burgstat_first.widow.or.widower + delta_oplcat.hbo*oplcat_first.hbo + delta_oplcat.mbo*oplcat_first.mbo + delta_oplcat.primary.school*oplcat_first.primary.school + delta_oplcat.vmbo*oplcat_first.vmbo + delta_oplcat.wo*oplcat_first.wo + delta_employment.homemaker*employment_first.homemaker + delta_employment.retired*employment_first.retired + delta_employment.student*employment_first.student + delta_employment.unable.to.work*employment_first.unable.to.work + delta_employment.unemployed*employment_first.unemployed

"
)

cv_models_x <- c(
    "
# Regressions
mhi5_23 ~ alpha_mhi5_23*1 + rho1*mhi5_22 + rho2*mhi5_21 + rho3*mhi5_20 + beta0_cs104*cs104_23 + beta1_cs104*cs104_22 + omega0_ch4.good*ch4_23.good + omega0_ch4.moderate*ch4_23.moderate + omega0_ch4.poor*ch4_23.poor + omega0_ch4.very.good*ch4_23.very.good + omega0_ch98*ch98_23 + delta_leeftijd.18.24*leeftijd_first.18.24 + delta_leeftijd.25.39*leeftijd_first.25.39 + delta_leeftijd.40.66*leeftijd_first.40.66 + delta_leeftijd.over.67*leeftijd_first.over.67 + delta_nettohh_f.under.15k*nettohh_f_first.under.15k + delta_nettohh_f.over.50k*nettohh_f_first.over.50k + delta_herkomstgroep.first.w*herkomstgroep_first.first.w + delta_herkomstgroep.first.nonw*herkomstgroep_first.first.nonw + delta_herkomstgroep.second.w*herkomstgroep_first.second.w + delta_herkomstgroep.second.nonw*herkomstgroep_first.second.nonw + delta_geslacht.male*geslacht_first.male + delta_burgstat.married*burgstat_first.married + delta_burgstat.never.been.married*burgstat_first.never.been.married + delta_burgstat.separated*burgstat_first.separated + delta_burgstat.widow.or.widower*burgstat_first.widow.or.widower + delta_oplcat.hbo*oplcat_first.hbo + delta_oplcat.mbo*oplcat_first.mbo + delta_oplcat.primary.school*oplcat_first.primary.school + delta_oplcat.vmbo*oplcat_first.vmbo + delta_oplcat.wo*oplcat_first.wo + delta_employment.homemaker*employment_first.homemaker + delta_employment.retired*employment_first.retired + delta_employment.student*employment_first.student + delta_employment.unable.to.work*employment_first.unable.to.work + delta_employment.unemployed*employment_first.unemployed

", "
# Regressions
mhi5_23 ~ alpha_mhi5_23*1 + rho1*mhi5_22 + rho2*mhi5_21 + rho3*mhi5_20 + beta0_cs104*cs104_23 + beta1_cs104*cs104_22 + beta2_cs104*cs104_21 + omega0_ch4.good*ch4_23.good + omega0_ch4.moderate*ch4_23.moderate + omega0_ch4.poor*ch4_23.poor + omega0_ch4.very.good*ch4_23.very.good + omega0_ch98*ch98_23 + delta_leeftijd.18.24*leeftijd_first.18.24 + delta_leeftijd.25.39*leeftijd_first.25.39 + delta_leeftijd.40.66*leeftijd_first.40.66 + delta_leeftijd.over.67*leeftijd_first.over.67 + delta_nettohh_f.under.15k*nettohh_f_first.under.15k + delta_nettohh_f.over.50k*nettohh_f_first.over.50k + delta_herkomstgroep.first.w*herkomstgroep_first.first.w + delta_herkomstgroep.first.nonw*herkomstgroep_first.first.nonw + delta_herkomstgroep.second.w*herkomstgroep_first.second.w + delta_herkomstgroep.second.nonw*herkomstgroep_first.second.nonw + delta_geslacht.male*geslacht_first.male + delta_burgstat.married*burgstat_first.married + delta_burgstat.never.been.married*burgstat_first.never.been.married + delta_burgstat.separated*burgstat_first.separated + delta_burgstat.widow.or.widower*burgstat_first.widow.or.widower + delta_oplcat.hbo*oplcat_first.hbo + delta_oplcat.mbo*oplcat_first.mbo + delta_oplcat.primary.school*oplcat_first.primary.school + delta_oplcat.vmbo*oplcat_first.vmbo + delta_oplcat.wo*oplcat_first.wo + delta_employment.homemaker*employment_first.homemaker + delta_employment.retired*employment_first.retired + delta_employment.student*employment_first.student + delta_employment.unable.to.work*employment_first.unable.to.work + delta_employment.unemployed*employment_first.unemployed

", "
# Regressions
mhi5_23 ~ alpha_mhi5_23*1 + rho1*mhi5_22 + rho2*mhi5_21 + rho3*mhi5_20 + beta0_cs104*cs104_23 + beta1_cs104*cs104_22 + beta2_cs104*cs104_21 + beta3_cs104*cs104_20 + omega0_ch4.good*ch4_23.good + omega0_ch4.moderate*ch4_23.moderate + omega0_ch4.poor*ch4_23.poor + omega0_ch4.very.good*ch4_23.very.good + omega0_ch98*ch98_23 + delta_leeftijd.18.24*leeftijd_first.18.24 + delta_leeftijd.25.39*leeftijd_first.25.39 + delta_leeftijd.40.66*leeftijd_first.40.66 + delta_leeftijd.over.67*leeftijd_first.over.67 + delta_nettohh_f.under.15k*nettohh_f_first.under.15k + delta_nettohh_f.over.50k*nettohh_f_first.over.50k + delta_herkomstgroep.first.w*herkomstgroep_first.first.w + delta_herkomstgroep.first.nonw*herkomstgroep_first.first.nonw + delta_herkomstgroep.second.w*herkomstgroep_first.second.w + delta_herkomstgroep.second.nonw*herkomstgroep_first.second.nonw + delta_geslacht.male*geslacht_first.male + delta_burgstat.married*burgstat_first.married + delta_burgstat.never.been.married*burgstat_first.never.been.married + delta_burgstat.separated*burgstat_first.separated + delta_burgstat.widow.or.widower*burgstat_first.widow.or.widower + delta_oplcat.hbo*oplcat_first.hbo + delta_oplcat.mbo*oplcat_first.mbo + delta_oplcat.primary.school*oplcat_first.primary.school + delta_oplcat.vmbo*oplcat_first.vmbo + delta_oplcat.wo*oplcat_first.wo + delta_employment.homemaker*employment_first.homemaker + delta_employment.retired*employment_first.retired + delta_employment.student*employment_first.student + delta_employment.unable.to.work*employment_first.unable.to.work + delta_employment.unemployed*employment_first.unemployed

", "
# Regressions
mhi5_23 ~ alpha_mhi5_23*1 + rho1*mhi5_22 + rho2*mhi5_21 + rho3*mhi5_20 + beta0_cs104*cs104_23 + beta1_cs104*cs104_22 + beta2_cs104*cs104_21 + beta3_cs104*cs104_20 + beta4_cs104*cs104_19 + omega0_ch4.good*ch4_23.good + omega0_ch4.moderate*ch4_23.moderate + omega0_ch4.poor*ch4_23.poor + omega0_ch4.very.good*ch4_23.very.good + omega0_ch98*ch98_23 + delta_leeftijd.18.24*leeftijd_first.18.24 + delta_leeftijd.25.39*leeftijd_first.25.39 + delta_leeftijd.40.66*leeftijd_first.40.66 + delta_leeftijd.over.67*leeftijd_first.over.67 + delta_nettohh_f.under.15k*nettohh_f_first.under.15k + delta_nettohh_f.over.50k*nettohh_f_first.over.50k + delta_herkomstgroep.first.w*herkomstgroep_first.first.w + delta_herkomstgroep.first.nonw*herkomstgroep_first.first.nonw + delta_herkomstgroep.second.w*herkomstgroep_first.second.w + delta_herkomstgroep.second.nonw*herkomstgroep_first.second.nonw + delta_geslacht.male*geslacht_first.male + delta_burgstat.married*burgstat_first.married + delta_burgstat.never.been.married*burgstat_first.never.been.married + delta_burgstat.separated*burgstat_first.separated + delta_burgstat.widow.or.widower*burgstat_first.widow.or.widower + delta_oplcat.hbo*oplcat_first.hbo + delta_oplcat.mbo*oplcat_first.mbo + delta_oplcat.primary.school*oplcat_first.primary.school + delta_oplcat.vmbo*oplcat_first.vmbo + delta_oplcat.wo*oplcat_first.wo + delta_employment.homemaker*employment_first.homemaker + delta_employment.retired*employment_first.retired + delta_employment.student*employment_first.student + delta_employment.unable.to.work*employment_first.unable.to.work + delta_employment.unemployed*employment_first.unemployed

", "
# Regressions
mhi5_23 ~ alpha_mhi5_23*1 + rho1*mhi5_22 + rho2*mhi5_21 + rho3*mhi5_20 + beta0_cs104*cs104_23 + beta1_cs104*cs104_22 + beta2_cs104*cs104_21 + beta3_cs104*cs104_20 + beta4_cs104*cs104_19 + beta5_cs104*cs104_18 + omega0_ch4.good*ch4_23.good + omega0_ch4.moderate*ch4_23.moderate + omega0_ch4.poor*ch4_23.poor + omega0_ch4.very.good*ch4_23.very.good + omega0_ch98*ch98_23 + delta_leeftijd.18.24*leeftijd_first.18.24 + delta_leeftijd.25.39*leeftijd_first.25.39 + delta_leeftijd.40.66*leeftijd_first.40.66 + delta_leeftijd.over.67*leeftijd_first.over.67 + delta_nettohh_f.under.15k*nettohh_f_first.under.15k + delta_nettohh_f.over.50k*nettohh_f_first.over.50k + delta_herkomstgroep.first.w*herkomstgroep_first.first.w + delta_herkomstgroep.first.nonw*herkomstgroep_first.first.nonw + delta_herkomstgroep.second.w*herkomstgroep_first.second.w + delta_herkomstgroep.second.nonw*herkomstgroep_first.second.nonw + delta_geslacht.male*geslacht_first.male + delta_burgstat.married*burgstat_first.married + delta_burgstat.never.been.married*burgstat_first.never.been.married + delta_burgstat.separated*burgstat_first.separated + delta_burgstat.widow.or.widower*burgstat_first.widow.or.widower + delta_oplcat.hbo*oplcat_first.hbo + delta_oplcat.mbo*oplcat_first.mbo + delta_oplcat.primary.school*oplcat_first.primary.school + delta_oplcat.vmbo*oplcat_first.vmbo + delta_oplcat.wo*oplcat_first.wo + delta_employment.homemaker*employment_first.homemaker + delta_employment.retired*employment_first.retired + delta_employment.student*employment_first.student + delta_employment.unable.to.work*employment_first.unable.to.work + delta_employment.unemployed*employment_first.unemployed

", "
# Regressions
mhi5_23 ~ alpha_mhi5_23*1 + rho1*mhi5_22 + rho2*mhi5_21 + rho3*mhi5_20 + beta0_cs104*cs104_23 + beta1_cs104*cs104_22 + beta2_cs104*cs104_21 + beta3_cs104*cs104_20 + beta4_cs104*cs104_19 + beta5_cs104*cs104_18 + beta6_cs104*cs104_17 + omega0_ch4.good*ch4_23.good + omega0_ch4.moderate*ch4_23.moderate + omega0_ch4.poor*ch4_23.poor + omega0_ch4.very.good*ch4_23.very.good + omega0_ch98*ch98_23 + delta_leeftijd.18.24*leeftijd_first.18.24 + delta_leeftijd.25.39*leeftijd_first.25.39 + delta_leeftijd.40.66*leeftijd_first.40.66 + delta_leeftijd.over.67*leeftijd_first.over.67 + delta_nettohh_f.under.15k*nettohh_f_first.under.15k + delta_nettohh_f.over.50k*nettohh_f_first.over.50k + delta_herkomstgroep.first.w*herkomstgroep_first.first.w + delta_herkomstgroep.first.nonw*herkomstgroep_first.first.nonw + delta_herkomstgroep.second.w*herkomstgroep_first.second.w + delta_herkomstgroep.second.nonw*herkomstgroep_first.second.nonw + delta_geslacht.male*geslacht_first.male + delta_burgstat.married*burgstat_first.married + delta_burgstat.never.been.married*burgstat_first.never.been.married + delta_burgstat.separated*burgstat_first.separated + delta_burgstat.widow.or.widower*burgstat_first.widow.or.widower + delta_oplcat.hbo*oplcat_first.hbo + delta_oplcat.mbo*oplcat_first.mbo + delta_oplcat.primary.school*oplcat_first.primary.school + delta_oplcat.vmbo*oplcat_first.vmbo + delta_oplcat.wo*oplcat_first.wo + delta_employment.homemaker*employment_first.homemaker + delta_employment.retired*employment_first.retired + delta_employment.student*employment_first.student + delta_employment.unable.to.work*employment_first.unable.to.work + delta_employment.unemployed*employment_first.unemployed

", "
# Regressions
mhi5_23 ~ alpha_mhi5_23*1 + rho1*mhi5_22 + rho2*mhi5_21 + rho3*mhi5_20 + beta0_cs104*cs104_23 + beta1_cs104*cs104_22 + beta2_cs104*cs104_21 + beta3_cs104*cs104_20 + beta4_cs104*cs104_19 + beta5_cs104*cs104_18 + beta6_cs104*cs104_17 + beta7_cs104*cs104_16 + omega0_ch4.good*ch4_23.good + omega0_ch4.moderate*ch4_23.moderate + omega0_ch4.poor*ch4_23.poor + omega0_ch4.very.good*ch4_23.very.good + omega0_ch98*ch98_23 + delta_leeftijd.18.24*leeftijd_first.18.24 + delta_leeftijd.25.39*leeftijd_first.25.39 + delta_leeftijd.40.66*leeftijd_first.40.66 + delta_leeftijd.over.67*leeftijd_first.over.67 + delta_nettohh_f.under.15k*nettohh_f_first.under.15k + delta_nettohh_f.over.50k*nettohh_f_first.over.50k + delta_herkomstgroep.first.w*herkomstgroep_first.first.w + delta_herkomstgroep.first.nonw*herkomstgroep_first.first.nonw + delta_herkomstgroep.second.w*herkomstgroep_first.second.w + delta_herkomstgroep.second.nonw*herkomstgroep_first.second.nonw + delta_geslacht.male*geslacht_first.male + delta_burgstat.married*burgstat_first.married + delta_burgstat.never.been.married*burgstat_first.never.been.married + delta_burgstat.separated*burgstat_first.separated + delta_burgstat.widow.or.widower*burgstat_first.widow.or.widower + delta_oplcat.hbo*oplcat_first.hbo + delta_oplcat.mbo*oplcat_first.mbo + delta_oplcat.primary.school*oplcat_first.primary.school + delta_oplcat.vmbo*oplcat_first.vmbo + delta_oplcat.wo*oplcat_first.wo + delta_employment.homemaker*employment_first.homemaker + delta_employment.retired*employment_first.retired + delta_employment.student*employment_first.student + delta_employment.unable.to.work*employment_first.unable.to.work + delta_employment.unemployed*employment_first.unemployed

", "
# Regressions
mhi5_23 ~ alpha_mhi5_23*1 + rho1*mhi5_22 + rho2*mhi5_21 + rho3*mhi5_20 + beta0_cs104*cs104_23 + beta1_cs104*cs104_22 + beta2_cs104*cs104_21 + beta3_cs104*cs104_20 + beta4_cs104*cs104_19 + beta5_cs104*cs104_18 + beta6_cs104*cs104_17 + beta7_cs104*cs104_16 + beta8_cs104*cs104_15 + omega0_ch4.good*ch4_23.good + omega0_ch4.moderate*ch4_23.moderate + omega0_ch4.poor*ch4_23.poor + omega0_ch4.very.good*ch4_23.very.good + omega0_ch98*ch98_23 + delta_leeftijd.18.24*leeftijd_first.18.24 + delta_leeftijd.25.39*leeftijd_first.25.39 + delta_leeftijd.40.66*leeftijd_first.40.66 + delta_leeftijd.over.67*leeftijd_first.over.67 + delta_nettohh_f.under.15k*nettohh_f_first.under.15k + delta_nettohh_f.over.50k*nettohh_f_first.over.50k + delta_herkomstgroep.first.w*herkomstgroep_first.first.w + delta_herkomstgroep.first.nonw*herkomstgroep_first.first.nonw + delta_herkomstgroep.second.w*herkomstgroep_first.second.w + delta_herkomstgroep.second.nonw*herkomstgroep_first.second.nonw + delta_geslacht.male*geslacht_first.male + delta_burgstat.married*burgstat_first.married + delta_burgstat.never.been.married*burgstat_first.never.been.married + delta_burgstat.separated*burgstat_first.separated + delta_burgstat.widow.or.widower*burgstat_first.widow.or.widower + delta_oplcat.hbo*oplcat_first.hbo + delta_oplcat.mbo*oplcat_first.mbo + delta_oplcat.primary.school*oplcat_first.primary.school + delta_oplcat.vmbo*oplcat_first.vmbo + delta_oplcat.wo*oplcat_first.wo + delta_employment.homemaker*employment_first.homemaker + delta_employment.retired*employment_first.retired + delta_employment.student*employment_first.student + delta_employment.unable.to.work*employment_first.unable.to.work + delta_employment.unemployed*employment_first.unemployed

", "
# Regressions
mhi5_23 ~ alpha_mhi5_23*1 + rho1*mhi5_22 + rho2*mhi5_21 + rho3*mhi5_20 + beta0_cs104*cs104_23 + beta1_cs104*cs104_22 + beta2_cs104*cs104_21 + beta3_cs104*cs104_20 + beta4_cs104*cs104_19 + beta5_cs104*cs104_18 + beta6_cs104*cs104_17 + beta7_cs104*cs104_16 + beta8_cs104*cs104_15 + beta9_cs104*cs104_14 + omega0_ch4.good*ch4_23.good + omega0_ch4.moderate*ch4_23.moderate + omega0_ch4.poor*ch4_23.poor + omega0_ch4.very.good*ch4_23.very.good + omega0_ch98*ch98_23 + delta_leeftijd.18.24*leeftijd_first.18.24 + delta_leeftijd.25.39*leeftijd_first.25.39 + delta_leeftijd.40.66*leeftijd_first.40.66 + delta_leeftijd.over.67*leeftijd_first.over.67 + delta_nettohh_f.under.15k*nettohh_f_first.under.15k + delta_nettohh_f.over.50k*nettohh_f_first.over.50k + delta_herkomstgroep.first.w*herkomstgroep_first.first.w + delta_herkomstgroep.first.nonw*herkomstgroep_first.first.nonw + delta_herkomstgroep.second.w*herkomstgroep_first.second.w + delta_herkomstgroep.second.nonw*herkomstgroep_first.second.nonw + delta_geslacht.male*geslacht_first.male + delta_burgstat.married*burgstat_first.married + delta_burgstat.never.been.married*burgstat_first.never.been.married + delta_burgstat.separated*burgstat_first.separated + delta_burgstat.widow.or.widower*burgstat_first.widow.or.widower + delta_oplcat.hbo*oplcat_first.hbo + delta_oplcat.mbo*oplcat_first.mbo + delta_oplcat.primary.school*oplcat_first.primary.school + delta_oplcat.vmbo*oplcat_first.vmbo + delta_oplcat.wo*oplcat_first.wo + delta_employment.homemaker*employment_first.homemaker + delta_employment.retired*employment_first.retired + delta_employment.student*employment_first.student + delta_employment.unable.to.work*employment_first.unable.to.work + delta_employment.unemployed*employment_first.unemployed

", "
# Regressions
mhi5_23 ~ alpha_mhi5_23*1 + rho1*mhi5_22 + rho2*mhi5_21 + rho3*mhi5_20 + beta0_cs104*cs104_23 + beta1_cs104*cs104_22 + beta2_cs104*cs104_21 + beta3_cs104*cs104_20 + beta4_cs104*cs104_19 + beta5_cs104*cs104_18 + beta6_cs104*cs104_17 + beta7_cs104*cs104_16 + beta8_cs104*cs104_15 + beta9_cs104*cs104_14 + beta10_cs104*cs104_13 + omega0_ch4.good*ch4_23.good + omega0_ch4.moderate*ch4_23.moderate + omega0_ch4.poor*ch4_23.poor + omega0_ch4.very.good*ch4_23.very.good + omega0_ch98*ch98_23 + delta_leeftijd.18.24*leeftijd_first.18.24 + delta_leeftijd.25.39*leeftijd_first.25.39 + delta_leeftijd.40.66*leeftijd_first.40.66 + delta_leeftijd.over.67*leeftijd_first.over.67 + delta_nettohh_f.under.15k*nettohh_f_first.under.15k + delta_nettohh_f.over.50k*nettohh_f_first.over.50k + delta_herkomstgroep.first.w*herkomstgroep_first.first.w + delta_herkomstgroep.first.nonw*herkomstgroep_first.first.nonw + delta_herkomstgroep.second.w*herkomstgroep_first.second.w + delta_herkomstgroep.second.nonw*herkomstgroep_first.second.nonw + delta_geslacht.male*geslacht_first.male + delta_burgstat.married*burgstat_first.married + delta_burgstat.never.been.married*burgstat_first.never.been.married + delta_burgstat.separated*burgstat_first.separated + delta_burgstat.widow.or.widower*burgstat_first.widow.or.widower + delta_oplcat.hbo*oplcat_first.hbo + delta_oplcat.mbo*oplcat_first.mbo + delta_oplcat.primary.school*oplcat_first.primary.school + delta_oplcat.vmbo*oplcat_first.vmbo + delta_oplcat.wo*oplcat_first.wo + delta_employment.homemaker*employment_first.homemaker + delta_employment.retired*employment_first.retired + delta_employment.student*employment_first.student + delta_employment.unable.to.work*employment_first.unable.to.work + delta_employment.unemployed*employment_first.unemployed

", "
# Regressions
mhi5_23 ~ alpha_mhi5_23*1 + rho1*mhi5_22 + rho2*mhi5_21 + rho3*mhi5_20 + beta0_cs104*cs104_23 + beta1_cs104*cs104_22 + beta2_cs104*cs104_21 + beta3_cs104*cs104_20 + beta4_cs104*cs104_19 + beta5_cs104*cs104_18 + beta6_cs104*cs104_17 + beta7_cs104*cs104_16 + beta8_cs104*cs104_15 + beta9_cs104*cs104_14 + beta10_cs104*cs104_13 + beta11_cs104*cs104_12 + omega0_ch4.good*ch4_23.good + omega0_ch4.moderate*ch4_23.moderate + omega0_ch4.poor*ch4_23.poor + omega0_ch4.very.good*ch4_23.very.good + omega0_ch98*ch98_23 + delta_leeftijd.18.24*leeftijd_first.18.24 + delta_leeftijd.25.39*leeftijd_first.25.39 + delta_leeftijd.40.66*leeftijd_first.40.66 + delta_leeftijd.over.67*leeftijd_first.over.67 + delta_nettohh_f.under.15k*nettohh_f_first.under.15k + delta_nettohh_f.over.50k*nettohh_f_first.over.50k + delta_herkomstgroep.first.w*herkomstgroep_first.first.w + delta_herkomstgroep.first.nonw*herkomstgroep_first.first.nonw + delta_herkomstgroep.second.w*herkomstgroep_first.second.w + delta_herkomstgroep.second.nonw*herkomstgroep_first.second.nonw + delta_geslacht.male*geslacht_first.male + delta_burgstat.married*burgstat_first.married + delta_burgstat.never.been.married*burgstat_first.never.been.married + delta_burgstat.separated*burgstat_first.separated + delta_burgstat.widow.or.widower*burgstat_first.widow.or.widower + delta_oplcat.hbo*oplcat_first.hbo + delta_oplcat.mbo*oplcat_first.mbo + delta_oplcat.primary.school*oplcat_first.primary.school + delta_oplcat.vmbo*oplcat_first.vmbo + delta_oplcat.wo*oplcat_first.wo + delta_employment.homemaker*employment_first.homemaker + delta_employment.retired*employment_first.retired + delta_employment.student*employment_first.student + delta_employment.unable.to.work*employment_first.unable.to.work + delta_employment.unemployed*employment_first.unemployed

"
)
```

```{r Do CV}
set.seed(69420)

while (i < len(cv_models_AR)) {
    cat("Model", i, "\n")

    result <- cv(cv_models_AR[[i]], do_print = TRUE)

    if (anyNA(result)) {
        cat("Failed\n")
        # Try again
        next
    }

    cat(result[[1]], "+/-", result[[2]], "\n")

    i <- i + 1
}
```

```{r Repeated CV}
set.seed(69420)

n_repeats <- 50

for (i in seq_along(cv_models_x)) {
    cat("Model", i, "/", length(cv_models_x), "\n")

    # Means and stds across the folds, for each repeat
    results <- matrix(nrow = n_repeats, ncol = 2)

    j <- 1

    while (j <= n_repeats) {
        cat("Repeat", j, "/", n_repeats, "- ")
        result <- cv(cv_models_x[[i]], do_print = FALSE)

        if (anyNA(result)) {
            cat("Failed\n")
            # Try again
            next
        }

        results[j, 1] <- result[[1]]
        results[j, 2] <- result[[2]]

        cat(result[[1]], "+/-", result[[2]], "\n")

        j <- j + 1
    }

    cat("               Estimated mean RMSPE:", mean(results[, 1]), "+/-", sd(results[, 1]) / sqrt(n_repeats), "\n")
    cat("Estimated std of RMSPE across folds:", mean(results[, 2]), "+/-", sd(results[, 2]) / sqrt(n_repeats), "\n")
}
```
