# Reproduce Chekroud

Takes a model and the preprocessed data from the python script and runs the model on the data.

```{r Dependencies}
if (!requireNamespace("lavaan")) {
    install.packages("lavaan")
}
if (!requireNamespace("semPlot")) {
    install.packages("semPlot")
}
if (!requireNamespace("haven")) {
    install.packages("haven")
}

library(lavaan)
library(semPlot)
library(haven)
```

```{r Load data}
all_relevant_data <- read_dta("/tmp/data.dta")
head(data)
```

```{r}
# Define a more complex SEM model with both measurement and structural parts
sem_model <- "

# Regressions (structural part)
ch14_12 ~ beta0*cs104_12 + delta0_leeftijd_nan*leeftijd_12_nan + delta0_leeftijd_25_to_29_years*leeftijd_12_25_to_29_years + delta0_leeftijd_30_to_34_years*leeftijd_12_30_to_34_years + delta0_leeftijd_65_to_69_years*leeftijd_12_65_to_69_years + delta0_leeftijd_35_to_39_years*leeftijd_12_35_to_39_years + delta0_leeftijd_60_to_64_years*leeftijd_12_60_to_64_years + delta0_leeftijd_70_to_74_years*leeftijd_12_70_to_74_years + delta0_leeftijd_45_to_49_years*leeftijd_12_45_to_49_years + delta0_leeftijd_75_to_79_years*leeftijd_12_75_to_79_years + delta0_leeftijd_over_80*leeftijd_12_over_80 + delta0_leeftijd_55_to_59_years*leeftijd_12_55_to_59_years + delta0_leeftijd_50_to_54_years*leeftijd_12_50_to_54_years + delta0_leeftijd_18_to_24_years*leeftijd_12_18_to_24_years + delta0_leeftijd_40_to_44_years*leeftijd_12_40_to_44_years + delta0_herkomstgroep_nan*herkomstgroep_12_nan + delta0_herkomstgroep_first_nonw*herkomstgroep_12_first_nonw + delta0_herkomstgroep_first_w*herkomstgroep_12_first_w + delta0_herkomstgroep_second_w*herkomstgroep_12_second_w + delta0_herkomstgroep_second_nonw*herkomstgroep_12_second_nonw + delta0_geslacht_nan*geslacht_12_nan + delta0_geslacht_male*geslacht_12_male + delta0_burgstat_married*burgstat_12_married + delta0_burgstat_nan*burgstat_12_nan + delta0_burgstat_widow_or_widower*burgstat_12_widow_or_widower + delta0_burgstat_separated*burgstat_12_separated + delta0_burgstat_never_been_married*burgstat_12_never_been_married + delta0_nettohh_f_nan*nettohh_f_12_nan + delta0_nettohh_f_over_50000*nettohh_f_12_over_50000 + delta0_oplcat_nan*oplcat_12_nan + delta0_oplcat_wo*oplcat_12_wo + delta0_oplcat_primary_school*oplcat_12_primary_school + delta0_oplcat_vmbo*oplcat_12_vmbo + delta0_oplcat_mbo*oplcat_12_mbo + delta0_oplcat_hbo*oplcat_12_hbo + delta0_employment_nan*employment_12_nan + delta0_employment_homemaker*employment_12_homemaker + delta0_employment_retired*employment_12_retired + delta0_employment_unable_to_work*employment_12_unable_to_work + delta0_employment_self_employed*employment_12_self_employed + delta0_employment_out_of_work*employment_12_out_of_work + delta0_employment_student*employment_12_student + delta0_ch4_poor*ch4_12_poor + delta0_ch4_nan*ch4_12_nan + delta0_ch4_moderate*ch4_12_moderate + delta0_ch4_good*ch4_12_good + delta0_ch4_very_good*ch4_12_very_good + delta0_bmi_normal_weight*bmi_12_normal_weight + delta0_bmi_nan*bmi_12_nan + delta0_bmi_overweight*bmi_12_overweight + delta0_bmi_obese*bmi_12_obese + delta0_prev_depr*prev_depr_12
ch14_13 ~ beta0*cs104_13 + delta0_leeftijd_nan*leeftijd_13_nan + delta0_leeftijd_25_to_29_years*leeftijd_13_25_to_29_years + delta0_leeftijd_30_to_34_years*leeftijd_13_30_to_34_years + delta0_leeftijd_65_to_69_years*leeftijd_13_65_to_69_years + delta0_leeftijd_35_to_39_years*leeftijd_13_35_to_39_years + delta0_leeftijd_60_to_64_years*leeftijd_13_60_to_64_years + delta0_leeftijd_70_to_74_years*leeftijd_13_70_to_74_years + delta0_leeftijd_45_to_49_years*leeftijd_13_45_to_49_years + delta0_leeftijd_75_to_79_years*leeftijd_13_75_to_79_years + delta0_leeftijd_over_80*leeftijd_13_over_80 + delta0_leeftijd_55_to_59_years*leeftijd_13_55_to_59_years + delta0_leeftijd_50_to_54_years*leeftijd_13_50_to_54_years + delta0_leeftijd_18_to_24_years*leeftijd_13_18_to_24_years + delta0_leeftijd_40_to_44_years*leeftijd_13_40_to_44_years + delta0_herkomstgroep_nan*herkomstgroep_13_nan + delta0_herkomstgroep_first_nonw*herkomstgroep_13_first_nonw + delta0_herkomstgroep_first_w*herkomstgroep_13_first_w + delta0_herkomstgroep_second_w*herkomstgroep_13_second_w + delta0_herkomstgroep_second_nonw*herkomstgroep_13_second_nonw + delta0_geslacht_nan*geslacht_13_nan + delta0_geslacht_male*geslacht_13_male + delta0_burgstat_married*burgstat_13_married + delta0_burgstat_nan*burgstat_13_nan + delta0_burgstat_widow_or_widower*burgstat_13_widow_or_widower + delta0_burgstat_separated*burgstat_13_separated + delta0_burgstat_never_been_married*burgstat_13_never_been_married + delta0_nettohh_f_nan*nettohh_f_13_nan + delta0_nettohh_f_over_50000*nettohh_f_13_over_50000 + delta0_oplcat_nan*oplcat_13_nan + delta0_oplcat_wo*oplcat_13_wo + delta0_oplcat_primary_school*oplcat_13_primary_school + delta0_oplcat_vmbo*oplcat_13_vmbo + delta0_oplcat_mbo*oplcat_13_mbo + delta0_oplcat_hbo*oplcat_13_hbo + delta0_employment_nan*employment_13_nan + delta0_employment_homemaker*employment_13_homemaker + delta0_employment_retired*employment_13_retired + delta0_employment_unable_to_work*employment_13_unable_to_work + delta0_employment_self_employed*employment_13_self_employed + delta0_employment_out_of_work*employment_13_out_of_work + delta0_employment_student*employment_13_student + delta0_ch4_poor*ch4_13_poor + delta0_ch4_nan*ch4_13_nan + delta0_ch4_moderate*ch4_13_moderate + delta0_ch4_good*ch4_13_good + delta0_ch4_very_good*ch4_13_very_good + delta0_bmi_normal_weight*bmi_13_normal_weight + delta0_bmi_nan*bmi_13_nan + delta0_bmi_overweight*bmi_13_overweight + delta0_bmi_obese*bmi_13_obese + delta0_prev_depr*prev_depr_13
ch14_15 ~ beta0*cs104_15 + delta0_leeftijd_nan*leeftijd_15_nan + delta0_leeftijd_25_to_29_years*leeftijd_15_25_to_29_years + delta0_leeftijd_30_to_34_years*leeftijd_15_30_to_34_years + delta0_leeftijd_65_to_69_years*leeftijd_15_65_to_69_years + delta0_leeftijd_35_to_39_years*leeftijd_15_35_to_39_years + delta0_leeftijd_60_to_64_years*leeftijd_15_60_to_64_years + delta0_leeftijd_70_to_74_years*leeftijd_15_70_to_74_years + delta0_leeftijd_45_to_49_years*leeftijd_15_45_to_49_years + delta0_leeftijd_75_to_79_years*leeftijd_15_75_to_79_years + delta0_leeftijd_over_80*leeftijd_15_over_80 + delta0_leeftijd_55_to_59_years*leeftijd_15_55_to_59_years + delta0_leeftijd_50_to_54_years*leeftijd_15_50_to_54_years + delta0_leeftijd_18_to_24_years*leeftijd_15_18_to_24_years + delta0_leeftijd_40_to_44_years*leeftijd_15_40_to_44_years + delta0_herkomstgroep_nan*herkomstgroep_15_nan + delta0_herkomstgroep_first_nonw*herkomstgroep_15_first_nonw + delta0_herkomstgroep_first_w*herkomstgroep_15_first_w + delta0_herkomstgroep_second_w*herkomstgroep_15_second_w + delta0_herkomstgroep_second_nonw*herkomstgroep_15_second_nonw + delta0_geslacht_nan*geslacht_15_nan + delta0_geslacht_male*geslacht_15_male + delta0_burgstat_married*burgstat_15_married + delta0_burgstat_nan*burgstat_15_nan + delta0_burgstat_widow_or_widower*burgstat_15_widow_or_widower + delta0_burgstat_separated*burgstat_15_separated + delta0_burgstat_never_been_married*burgstat_15_never_been_married + delta0_nettohh_f_nan*nettohh_f_15_nan + delta0_nettohh_f_over_50000*nettohh_f_15_over_50000 + delta0_oplcat_nan*oplcat_15_nan + delta0_oplcat_wo*oplcat_15_wo + delta0_oplcat_primary_school*oplcat_15_primary_school + delta0_oplcat_vmbo*oplcat_15_vmbo + delta0_oplcat_mbo*oplcat_15_mbo + delta0_oplcat_hbo*oplcat_15_hbo + delta0_employment_nan*employment_15_nan + delta0_employment_homemaker*employment_15_homemaker + delta0_employment_retired*employment_15_retired + delta0_employment_unable_to_work*employment_15_unable_to_work + delta0_employment_self_employed*employment_15_self_employed + delta0_employment_out_of_work*employment_15_out_of_work + delta0_employment_student*employment_15_student + delta0_ch4_poor*ch4_15_poor + delta0_ch4_nan*ch4_15_nan + delta0_ch4_moderate*ch4_15_moderate + delta0_ch4_good*ch4_15_good + delta0_ch4_very_good*ch4_15_very_good + delta0_bmi_normal_weight*bmi_15_normal_weight + delta0_bmi_nan*bmi_15_nan + delta0_bmi_overweight*bmi_15_overweight + delta0_bmi_obese*bmi_15_obese + delta0_prev_depr*prev_depr_15
ch14_16 ~ beta0*cs104_16 + delta0_leeftijd_nan*leeftijd_16_nan + delta0_leeftijd_25_to_29_years*leeftijd_16_25_to_29_years + delta0_leeftijd_30_to_34_years*leeftijd_16_30_to_34_years + delta0_leeftijd_65_to_69_years*leeftijd_16_65_to_69_years + delta0_leeftijd_35_to_39_years*leeftijd_16_35_to_39_years + delta0_leeftijd_60_to_64_years*leeftijd_16_60_to_64_years + delta0_leeftijd_70_to_74_years*leeftijd_16_70_to_74_years + delta0_leeftijd_45_to_49_years*leeftijd_16_45_to_49_years + delta0_leeftijd_75_to_79_years*leeftijd_16_75_to_79_years + delta0_leeftijd_over_80*leeftijd_16_over_80 + delta0_leeftijd_55_to_59_years*leeftijd_16_55_to_59_years + delta0_leeftijd_50_to_54_years*leeftijd_16_50_to_54_years + delta0_leeftijd_18_to_24_years*leeftijd_16_18_to_24_years + delta0_leeftijd_40_to_44_years*leeftijd_16_40_to_44_years + delta0_herkomstgroep_nan*herkomstgroep_16_nan + delta0_herkomstgroep_first_nonw*herkomstgroep_16_first_nonw + delta0_herkomstgroep_first_w*herkomstgroep_16_first_w + delta0_herkomstgroep_second_w*herkomstgroep_16_second_w + delta0_herkomstgroep_second_nonw*herkomstgroep_16_second_nonw + delta0_geslacht_nan*geslacht_16_nan + delta0_geslacht_male*geslacht_16_male + delta0_burgstat_married*burgstat_16_married + delta0_burgstat_nan*burgstat_16_nan + delta0_burgstat_widow_or_widower*burgstat_16_widow_or_widower + delta0_burgstat_separated*burgstat_16_separated + delta0_burgstat_never_been_married*burgstat_16_never_been_married + delta0_nettohh_f_nan*nettohh_f_16_nan + delta0_nettohh_f_15_to_25000*nettohh_f_16_15_to_25000 + delta0_nettohh_f_over_50000*nettohh_f_16_over_50000 + delta0_oplcat_nan*oplcat_16_nan + delta0_oplcat_wo*oplcat_16_wo + delta0_oplcat_primary_school*oplcat_16_primary_school + delta0_oplcat_vmbo*oplcat_16_vmbo + delta0_oplcat_mbo*oplcat_16_mbo + delta0_oplcat_hbo*oplcat_16_hbo + delta0_employment_nan*employment_16_nan + delta0_employment_homemaker*employment_16_homemaker + delta0_employment_retired*employment_16_retired + delta0_employment_unable_to_work*employment_16_unable_to_work + delta0_employment_self_employed*employment_16_self_employed + delta0_employment_out_of_work*employment_16_out_of_work + delta0_employment_student*employment_16_student + delta0_ch4_poor*ch4_16_poor + delta0_ch4_nan*ch4_16_nan + delta0_ch4_moderate*ch4_16_moderate + delta0_ch4_good*ch4_16_good + delta0_ch4_very_good*ch4_16_very_good + delta0_bmi_normal_weight*bmi_16_normal_weight + delta0_bmi_nan*bmi_16_nan + delta0_bmi_overweight*bmi_16_overweight + delta0_bmi_obese*bmi_16_obese + delta0_prev_depr*prev_depr_16
ch14_17 ~ beta0*cs104_17 + delta0_leeftijd_nan*leeftijd_17_nan + delta0_leeftijd_25_to_29_years*leeftijd_17_25_to_29_years + delta0_leeftijd_30_to_34_years*leeftijd_17_30_to_34_years + delta0_leeftijd_65_to_69_years*leeftijd_17_65_to_69_years + delta0_leeftijd_35_to_39_years*leeftijd_17_35_to_39_years + delta0_leeftijd_60_to_64_years*leeftijd_17_60_to_64_years + delta0_leeftijd_70_to_74_years*leeftijd_17_70_to_74_years + delta0_leeftijd_45_to_49_years*leeftijd_17_45_to_49_years + delta0_leeftijd_75_to_79_years*leeftijd_17_75_to_79_years + delta0_leeftijd_over_80*leeftijd_17_over_80 + delta0_leeftijd_55_to_59_years*leeftijd_17_55_to_59_years + delta0_leeftijd_50_to_54_years*leeftijd_17_50_to_54_years + delta0_leeftijd_18_to_24_years*leeftijd_17_18_to_24_years + delta0_leeftijd_40_to_44_years*leeftijd_17_40_to_44_years + delta0_herkomstgroep_nan*herkomstgroep_17_nan + delta0_herkomstgroep_first_nonw*herkomstgroep_17_first_nonw + delta0_herkomstgroep_first_w*herkomstgroep_17_first_w + delta0_herkomstgroep_second_w*herkomstgroep_17_second_w + delta0_herkomstgroep_second_nonw*herkomstgroep_17_second_nonw + delta0_geslacht_nan*geslacht_17_nan + delta0_geslacht_male*geslacht_17_male + delta0_burgstat_married*burgstat_17_married + delta0_burgstat_nan*burgstat_17_nan + delta0_burgstat_widow_or_widower*burgstat_17_widow_or_widower + delta0_burgstat_separated*burgstat_17_separated + delta0_burgstat_never_been_married*burgstat_17_never_been_married + delta0_nettohh_f_nan*nettohh_f_17_nan + delta0_nettohh_f_15_to_25000*nettohh_f_17_15_to_25000 + delta0_nettohh_f_over_50000*nettohh_f_17_over_50000 + delta0_oplcat_nan*oplcat_17_nan + delta0_oplcat_wo*oplcat_17_wo + delta0_oplcat_primary_school*oplcat_17_primary_school + delta0_oplcat_vmbo*oplcat_17_vmbo + delta0_oplcat_mbo*oplcat_17_mbo + delta0_oplcat_hbo*oplcat_17_hbo + delta0_employment_nan*employment_17_nan + delta0_employment_homemaker*employment_17_homemaker + delta0_employment_retired*employment_17_retired + delta0_employment_unable_to_work*employment_17_unable_to_work + delta0_employment_self_employed*employment_17_self_employed + delta0_employment_out_of_work*employment_17_out_of_work + delta0_employment_student*employment_17_student + delta0_ch4_poor*ch4_17_poor + delta0_ch4_nan*ch4_17_nan + delta0_ch4_moderate*ch4_17_moderate + delta0_ch4_good*ch4_17_good + delta0_ch4_very_good*ch4_17_very_good + delta0_bmi_normal_weight*bmi_17_normal_weight + delta0_bmi_nan*bmi_17_nan + delta0_bmi_overweight*bmi_17_overweight + delta0_bmi_obese*bmi_17_obese + delta0_prev_depr*prev_depr_17
ch14_18 ~ beta0*cs104_18 + delta0_leeftijd_nan*leeftijd_18_nan + delta0_leeftijd_25_to_29_years*leeftijd_18_25_to_29_years + delta0_leeftijd_30_to_34_years*leeftijd_18_30_to_34_years + delta0_leeftijd_65_to_69_years*leeftijd_18_65_to_69_years + delta0_leeftijd_35_to_39_years*leeftijd_18_35_to_39_years + delta0_leeftijd_60_to_64_years*leeftijd_18_60_to_64_years + delta0_leeftijd_70_to_74_years*leeftijd_18_70_to_74_years + delta0_leeftijd_45_to_49_years*leeftijd_18_45_to_49_years + delta0_leeftijd_75_to_79_years*leeftijd_18_75_to_79_years + delta0_leeftijd_over_80*leeftijd_18_over_80 + delta0_leeftijd_55_to_59_years*leeftijd_18_55_to_59_years + delta0_leeftijd_50_to_54_years*leeftijd_18_50_to_54_years + delta0_leeftijd_18_to_24_years*leeftijd_18_18_to_24_years + delta0_leeftijd_40_to_44_years*leeftijd_18_40_to_44_years + delta0_herkomstgroep_nan*herkomstgroep_18_nan + delta0_herkomstgroep_first_nonw*herkomstgroep_18_first_nonw + delta0_herkomstgroep_first_w*herkomstgroep_18_first_w + delta0_herkomstgroep_second_w*herkomstgroep_18_second_w + delta0_herkomstgroep_second_nonw*herkomstgroep_18_second_nonw + delta0_geslacht_nan*geslacht_18_nan + delta0_geslacht_male*geslacht_18_male + delta0_burgstat_married*burgstat_18_married + delta0_burgstat_nan*burgstat_18_nan + delta0_burgstat_widow_or_widower*burgstat_18_widow_or_widower + delta0_burgstat_separated*burgstat_18_separated + delta0_burgstat_never_been_married*burgstat_18_never_been_married + delta0_nettohh_f_nan*nettohh_f_18_nan + delta0_nettohh_f_35_to_50000*nettohh_f_18_35_to_50000 + delta0_nettohh_f_over_50000*nettohh_f_18_over_50000 + delta0_oplcat_nan*oplcat_18_nan + delta0_oplcat_wo*oplcat_18_wo + delta0_oplcat_primary_school*oplcat_18_primary_school + delta0_oplcat_vmbo*oplcat_18_vmbo + delta0_oplcat_mbo*oplcat_18_mbo + delta0_oplcat_hbo*oplcat_18_hbo + delta0_employment_nan*employment_18_nan + delta0_employment_homemaker*employment_18_homemaker + delta0_employment_retired*employment_18_retired + delta0_employment_unable_to_work*employment_18_unable_to_work + delta0_employment_self_employed*employment_18_self_employed + delta0_employment_out_of_work*employment_18_out_of_work + delta0_employment_student*employment_18_student + delta0_ch4_poor*ch4_18_poor + delta0_ch4_nan*ch4_18_nan + delta0_ch4_moderate*ch4_18_moderate + delta0_ch4_good*ch4_18_good + delta0_ch4_very_good*ch4_18_very_good + delta0_bmi_normal_weight*bmi_18_normal_weight + delta0_bmi_nan*bmi_18_nan + delta0_bmi_overweight*bmi_18_overweight + delta0_bmi_obese*bmi_18_obese + delta0_prev_depr*prev_depr_18
ch14_19 ~ beta0*cs104_19 + delta0_leeftijd_nan*leeftijd_19_nan + delta0_leeftijd_25_to_29_years*leeftijd_19_25_to_29_years + delta0_leeftijd_30_to_34_years*leeftijd_19_30_to_34_years + delta0_leeftijd_65_to_69_years*leeftijd_19_65_to_69_years + delta0_leeftijd_35_to_39_years*leeftijd_19_35_to_39_years + delta0_leeftijd_60_to_64_years*leeftijd_19_60_to_64_years + delta0_leeftijd_70_to_74_years*leeftijd_19_70_to_74_years + delta0_leeftijd_45_to_49_years*leeftijd_19_45_to_49_years + delta0_leeftijd_75_to_79_years*leeftijd_19_75_to_79_years + delta0_leeftijd_over_80*leeftijd_19_over_80 + delta0_leeftijd_55_to_59_years*leeftijd_19_55_to_59_years + delta0_leeftijd_50_to_54_years*leeftijd_19_50_to_54_years + delta0_leeftijd_18_to_24_years*leeftijd_19_18_to_24_years + delta0_leeftijd_40_to_44_years*leeftijd_19_40_to_44_years + delta0_herkomstgroep_nan*herkomstgroep_19_nan + delta0_herkomstgroep_first_nonw*herkomstgroep_19_first_nonw + delta0_herkomstgroep_first_w*herkomstgroep_19_first_w + delta0_herkomstgroep_second_w*herkomstgroep_19_second_w + delta0_herkomstgroep_second_nonw*herkomstgroep_19_second_nonw + delta0_geslacht_nan*geslacht_19_nan + delta0_geslacht_male*geslacht_19_male + delta0_burgstat_married*burgstat_19_married + delta0_burgstat_nan*burgstat_19_nan + delta0_burgstat_widow_or_widower*burgstat_19_widow_or_widower + delta0_burgstat_separated*burgstat_19_separated + delta0_burgstat_never_been_married*burgstat_19_never_been_married + delta0_nettohh_f_nan*nettohh_f_19_nan + delta0_nettohh_f_25_to_35000*nettohh_f_19_25_to_35000 + delta0_nettohh_f_15_to_25000*nettohh_f_19_15_to_25000 + delta0_nettohh_f_over_50000*nettohh_f_19_over_50000 + delta0_oplcat_nan*oplcat_19_nan + delta0_oplcat_wo*oplcat_19_wo + delta0_oplcat_primary_school*oplcat_19_primary_school + delta0_oplcat_vmbo*oplcat_19_vmbo + delta0_oplcat_mbo*oplcat_19_mbo + delta0_oplcat_hbo*oplcat_19_hbo + delta0_employment_nan*employment_19_nan + delta0_employment_homemaker*employment_19_homemaker + delta0_employment_retired*employment_19_retired + delta0_employment_unable_to_work*employment_19_unable_to_work + delta0_employment_self_employed*employment_19_self_employed + delta0_employment_out_of_work*employment_19_out_of_work + delta0_employment_student*employment_19_student + delta0_ch4_poor*ch4_19_poor + delta0_ch4_nan*ch4_19_nan + delta0_ch4_moderate*ch4_19_moderate + delta0_ch4_good*ch4_19_good + delta0_ch4_very_good*ch4_19_very_good + delta0_bmi_normal_weight*bmi_19_normal_weight + delta0_bmi_nan*bmi_19_nan + delta0_bmi_overweight*bmi_19_overweight + delta0_bmi_obese*bmi_19_obese + delta0_prev_depr*prev_depr_19
ch14_20 ~ beta0*cs104_20 + delta0_leeftijd_nan*leeftijd_20_nan + delta0_leeftijd_25_to_29_years*leeftijd_20_25_to_29_years + delta0_leeftijd_30_to_34_years*leeftijd_20_30_to_34_years + delta0_leeftijd_65_to_69_years*leeftijd_20_65_to_69_years + delta0_leeftijd_35_to_39_years*leeftijd_20_35_to_39_years + delta0_leeftijd_60_to_64_years*leeftijd_20_60_to_64_years + delta0_leeftijd_70_to_74_years*leeftijd_20_70_to_74_years + delta0_leeftijd_45_to_49_years*leeftijd_20_45_to_49_years + delta0_leeftijd_75_to_79_years*leeftijd_20_75_to_79_years + delta0_leeftijd_over_80*leeftijd_20_over_80 + delta0_leeftijd_55_to_59_years*leeftijd_20_55_to_59_years + delta0_leeftijd_50_to_54_years*leeftijd_20_50_to_54_years + delta0_leeftijd_18_to_24_years*leeftijd_20_18_to_24_years + delta0_leeftijd_40_to_44_years*leeftijd_20_40_to_44_years + delta0_herkomstgroep_nan*herkomstgroep_20_nan + delta0_herkomstgroep_first_nonw*herkomstgroep_20_first_nonw + delta0_herkomstgroep_first_w*herkomstgroep_20_first_w + delta0_herkomstgroep_second_w*herkomstgroep_20_second_w + delta0_herkomstgroep_second_nonw*herkomstgroep_20_second_nonw + delta0_geslacht_nan*geslacht_20_nan + delta0_geslacht_male*geslacht_20_male + delta0_burgstat_married*burgstat_20_married + delta0_burgstat_nan*burgstat_20_nan + delta0_burgstat_widow_or_widower*burgstat_20_widow_or_widower + delta0_burgstat_separated*burgstat_20_separated + delta0_burgstat_never_been_married*burgstat_20_never_been_married + delta0_nettohh_f_nan*nettohh_f_20_nan + delta0_nettohh_f_15_to_25000*nettohh_f_20_15_to_25000 + delta0_nettohh_f_35_to_50000*nettohh_f_20_35_to_50000 + delta0_nettohh_f_over_50000*nettohh_f_20_over_50000 + delta0_oplcat_nan*oplcat_20_nan + delta0_oplcat_wo*oplcat_20_wo + delta0_oplcat_primary_school*oplcat_20_primary_school + delta0_oplcat_vmbo*oplcat_20_vmbo + delta0_oplcat_mbo*oplcat_20_mbo + delta0_oplcat_hbo*oplcat_20_hbo + delta0_employment_nan*employment_20_nan + delta0_employment_homemaker*employment_20_homemaker + delta0_employment_retired*employment_20_retired + delta0_employment_unable_to_work*employment_20_unable_to_work + delta0_employment_self_employed*employment_20_self_employed + delta0_employment_out_of_work*employment_20_out_of_work + delta0_employment_student*employment_20_student + delta0_ch4_poor*ch4_20_poor + delta0_ch4_nan*ch4_20_nan + delta0_ch4_moderate*ch4_20_moderate + delta0_ch4_good*ch4_20_good + delta0_ch4_very_good*ch4_20_very_good + delta0_bmi_normal_weight*bmi_20_normal_weight + delta0_bmi_nan*bmi_20_nan + delta0_bmi_overweight*bmi_20_overweight + delta0_bmi_obese*bmi_20_obese + delta0_prev_depr*prev_depr_20
ch14_21 ~ beta0*cs104_21 + delta0_leeftijd_nan*leeftijd_21_nan + delta0_leeftijd_25_to_29_years*leeftijd_21_25_to_29_years + delta0_leeftijd_30_to_34_years*leeftijd_21_30_to_34_years + delta0_leeftijd_65_to_69_years*leeftijd_21_65_to_69_years + delta0_leeftijd_35_to_39_years*leeftijd_21_35_to_39_years + delta0_leeftijd_60_to_64_years*leeftijd_21_60_to_64_years + delta0_leeftijd_70_to_74_years*leeftijd_21_70_to_74_years + delta0_leeftijd_45_to_49_years*leeftijd_21_45_to_49_years + delta0_leeftijd_75_to_79_years*leeftijd_21_75_to_79_years + delta0_leeftijd_over_80*leeftijd_21_over_80 + delta0_leeftijd_55_to_59_years*leeftijd_21_55_to_59_years + delta0_leeftijd_50_to_54_years*leeftijd_21_50_to_54_years + delta0_leeftijd_18_to_24_years*leeftijd_21_18_to_24_years + delta0_leeftijd_40_to_44_years*leeftijd_21_40_to_44_years + delta0_herkomstgroep_nan*herkomstgroep_21_nan + delta0_herkomstgroep_first_nonw*herkomstgroep_21_first_nonw + delta0_herkomstgroep_first_w*herkomstgroep_21_first_w + delta0_herkomstgroep_second_w*herkomstgroep_21_second_w + delta0_herkomstgroep_second_nonw*herkomstgroep_21_second_nonw + delta0_geslacht_nan*geslacht_21_nan + delta0_geslacht_male*geslacht_21_male + delta0_burgstat_married*burgstat_21_married + delta0_burgstat_nan*burgstat_21_nan + delta0_burgstat_widow_or_widower*burgstat_21_widow_or_widower + delta0_burgstat_separated*burgstat_21_separated + delta0_burgstat_never_been_married*burgstat_21_never_been_married + delta0_nettohh_f_nan*nettohh_f_21_nan + delta0_nettohh_f_15_to_25000*nettohh_f_21_15_to_25000 + delta0_nettohh_f_over_50000*nettohh_f_21_over_50000 + delta0_oplcat_nan*oplcat_21_nan + delta0_oplcat_wo*oplcat_21_wo + delta0_oplcat_primary_school*oplcat_21_primary_school + delta0_oplcat_vmbo*oplcat_21_vmbo + delta0_oplcat_mbo*oplcat_21_mbo + delta0_oplcat_hbo*oplcat_21_hbo + delta0_employment_nan*employment_21_nan + delta0_employment_homemaker*employment_21_homemaker + delta0_employment_retired*employment_21_retired + delta0_employment_unable_to_work*employment_21_unable_to_work + delta0_employment_self_employed*employment_21_self_employed + delta0_employment_out_of_work*employment_21_out_of_work + delta0_employment_student*employment_21_student + delta0_ch4_poor*ch4_21_poor + delta0_ch4_nan*ch4_21_nan + delta0_ch4_moderate*ch4_21_moderate + delta0_ch4_good*ch4_21_good + delta0_ch4_very_good*ch4_21_very_good + delta0_bmi_normal_weight*bmi_21_normal_weight + delta0_bmi_nan*bmi_21_nan + delta0_bmi_overweight*bmi_21_overweight + delta0_bmi_obese*bmi_21_obese + delta0_prev_depr*prev_depr_21
ch14_22 ~ beta0*cs104_22 + delta0_leeftijd_nan*leeftijd_22_nan + delta0_leeftijd_25_to_29_years*leeftijd_22_25_to_29_years + delta0_leeftijd_30_to_34_years*leeftijd_22_30_to_34_years + delta0_leeftijd_65_to_69_years*leeftijd_22_65_to_69_years + delta0_leeftijd_35_to_39_years*leeftijd_22_35_to_39_years + delta0_leeftijd_60_to_64_years*leeftijd_22_60_to_64_years + delta0_leeftijd_70_to_74_years*leeftijd_22_70_to_74_years + delta0_leeftijd_45_to_49_years*leeftijd_22_45_to_49_years + delta0_leeftijd_75_to_79_years*leeftijd_22_75_to_79_years + delta0_leeftijd_over_80*leeftijd_22_over_80 + delta0_leeftijd_55_to_59_years*leeftijd_22_55_to_59_years + delta0_leeftijd_50_to_54_years*leeftijd_22_50_to_54_years + delta0_leeftijd_18_to_24_years*leeftijd_22_18_to_24_years + delta0_leeftijd_40_to_44_years*leeftijd_22_40_to_44_years + delta0_herkomstgroep_nan*herkomstgroep_22_nan + delta0_herkomstgroep_first_nonw*herkomstgroep_22_first_nonw + delta0_herkomstgroep_first_w*herkomstgroep_22_first_w + delta0_herkomstgroep_second_w*herkomstgroep_22_second_w + delta0_herkomstgroep_second_nonw*herkomstgroep_22_second_nonw + delta0_geslacht_other*geslacht_22_other + delta0_geslacht_nan*geslacht_22_nan + delta0_geslacht_male*geslacht_22_male + delta0_burgstat_married*burgstat_22_married + delta0_burgstat_nan*burgstat_22_nan + delta0_burgstat_widow_or_widower*burgstat_22_widow_or_widower + delta0_burgstat_separated*burgstat_22_separated + delta0_burgstat_never_been_married*burgstat_22_never_been_married + delta0_nettohh_f_nan*nettohh_f_22_nan + delta0_nettohh_f_15_to_25000*nettohh_f_22_15_to_25000 + delta0_oplcat_nan*oplcat_22_nan + delta0_oplcat_wo*oplcat_22_wo + delta0_oplcat_primary_school*oplcat_22_primary_school + delta0_oplcat_vmbo*oplcat_22_vmbo + delta0_oplcat_mbo*oplcat_22_mbo + delta0_oplcat_hbo*oplcat_22_hbo + delta0_employment_nan*employment_22_nan + delta0_employment_homemaker*employment_22_homemaker + delta0_employment_retired*employment_22_retired + delta0_employment_unable_to_work*employment_22_unable_to_work + delta0_employment_self_employed*employment_22_self_employed + delta0_employment_out_of_work*employment_22_out_of_work + delta0_employment_student*employment_22_student + delta0_ch4_poor*ch4_22_poor + delta0_ch4_nan*ch4_22_nan + delta0_ch4_moderate*ch4_22_moderate + delta0_ch4_good*ch4_22_good + delta0_ch4_very_good*ch4_22_very_good + delta0_bmi_normal_weight*bmi_22_normal_weight + delta0_bmi_nan*bmi_22_nan + delta0_bmi_overweight*bmi_22_overweight + delta0_bmi_obese*bmi_22_obese + delta0_prev_depr*prev_depr_22
ch14_23 ~ beta0*cs104_23 + delta0_leeftijd_nan*leeftijd_23_nan + delta0_leeftijd_25_to_29_years*leeftijd_23_25_to_29_years + delta0_leeftijd_30_to_34_years*leeftijd_23_30_to_34_years + delta0_leeftijd_65_to_69_years*leeftijd_23_65_to_69_years + delta0_leeftijd_35_to_39_years*leeftijd_23_35_to_39_years + delta0_leeftijd_60_to_64_years*leeftijd_23_60_to_64_years + delta0_leeftijd_70_to_74_years*leeftijd_23_70_to_74_years + delta0_leeftijd_45_to_49_years*leeftijd_23_45_to_49_years + delta0_leeftijd_75_to_79_years*leeftijd_23_75_to_79_years + delta0_leeftijd_over_80*leeftijd_23_over_80 + delta0_leeftijd_55_to_59_years*leeftijd_23_55_to_59_years + delta0_leeftijd_50_to_54_years*leeftijd_23_50_to_54_years + delta0_leeftijd_18_to_24_years*leeftijd_23_18_to_24_years + delta0_leeftijd_40_to_44_years*leeftijd_23_40_to_44_years + delta0_herkomstgroep_nan*herkomstgroep_23_nan + delta0_herkomstgroep_first_nonw*herkomstgroep_23_first_nonw + delta0_herkomstgroep_first_w*herkomstgroep_23_first_w + delta0_herkomstgroep_second_w*herkomstgroep_23_second_w + delta0_herkomstgroep_second_nonw*herkomstgroep_23_second_nonw + delta0_geslacht_other*geslacht_23_other + delta0_geslacht_nan*geslacht_23_nan + delta0_geslacht_male*geslacht_23_male + delta0_burgstat_married*burgstat_23_married + delta0_burgstat_nan*burgstat_23_nan + delta0_burgstat_widow_or_widower*burgstat_23_widow_or_widower + delta0_burgstat_separated*burgstat_23_separated + delta0_burgstat_never_been_married*burgstat_23_never_been_married + delta0_nettohh_f_nan*nettohh_f_23_nan + delta0_nettohh_f_25_to_35000*nettohh_f_23_25_to_35000 + delta0_nettohh_f_15_to_25000*nettohh_f_23_15_to_25000 + delta0_nettohh_f_35_to_50000*nettohh_f_23_35_to_50000 + delta0_nettohh_f_over_50000*nettohh_f_23_over_50000 + delta0_oplcat_nan*oplcat_23_nan + delta0_oplcat_wo*oplcat_23_wo + delta0_oplcat_primary_school*oplcat_23_primary_school + delta0_oplcat_vmbo*oplcat_23_vmbo + delta0_oplcat_mbo*oplcat_23_mbo + delta0_oplcat_hbo*oplcat_23_hbo + delta0_employment_nan*employment_23_nan + delta0_employment_homemaker*employment_23_homemaker + delta0_employment_retired*employment_23_retired + delta0_employment_unable_to_work*employment_23_unable_to_work + delta0_employment_self_employed*employment_23_self_employed + delta0_employment_out_of_work*employment_23_out_of_work + delta0_employment_student*employment_23_student + delta0_ch4_poor*ch4_23_poor + delta0_ch4_nan*ch4_23_nan + delta0_ch4_moderate*ch4_23_moderate + delta0_ch4_good*ch4_23_good + delta0_ch4_very_good*ch4_23_very_good + delta0_bmi_normal_weight*bmi_23_normal_weight + delta0_bmi_nan*bmi_23_nan + delta0_bmi_overweight*bmi_23_overweight + delta0_bmi_obese*bmi_23_obese + delta0_prev_depr*prev_depr_23

# Measurement part

# Additional covariances
ch14_12 ~~ sigma*ch14_12
ch14_13 ~~ sigma*ch14_13
ch14_15 ~~ sigma*ch14_15
ch14_16 ~~ sigma*ch14_16
ch14_17 ~~ sigma*ch14_17
ch14_18 ~~ sigma*ch14_18
ch14_19 ~~ sigma*ch14_19
ch14_20 ~~ sigma*ch14_20
ch14_21 ~~ sigma*ch14_21
ch14_22 ~~ sigma*ch14_22
ch14_23 ~~ sigma*ch14_23
ch14_12 ~~ gamma1*cs104_13 + gamma3*cs104_15 + gamma4*cs104_16 + gamma5*cs104_17 + gamma6*cs104_18 + gamma7*cs104_19 + gamma8*cs104_20 + gamma9*cs104_21 + gamma10*cs104_22 + gamma11*cs104_23
ch14_13 ~~ gamma2*cs104_15 + gamma3*cs104_16 + gamma4*cs104_17 + gamma5*cs104_18 + gamma6*cs104_19 + gamma7*cs104_20 + gamma8*cs104_21 + gamma9*cs104_22 + gamma10*cs104_23
ch14_15 ~~ gamma1*cs104_16 + gamma2*cs104_17 + gamma3*cs104_18 + gamma4*cs104_19 + gamma5*cs104_20 + gamma6*cs104_21 + gamma7*cs104_22 + gamma8*cs104_23
ch14_16 ~~ gamma1*cs104_17 + gamma2*cs104_18 + gamma3*cs104_19 + gamma4*cs104_20 + gamma5*cs104_21 + gamma6*cs104_22 + gamma7*cs104_23
ch14_17 ~~ gamma1*cs104_18 + gamma2*cs104_19 + gamma3*cs104_20 + gamma4*cs104_21 + gamma5*cs104_22 + gamma6*cs104_23
ch14_18 ~~ gamma1*cs104_19 + gamma2*cs104_20 + gamma3*cs104_21 + gamma4*cs104_22 + gamma5*cs104_23
ch14_19 ~~ gamma1*cs104_20 + gamma2*cs104_21 + gamma3*cs104_22 + gamma4*cs104_23
ch14_20 ~~ gamma1*cs104_21 + gamma2*cs104_22 + gamma3*cs104_23
ch14_21 ~~ gamma1*cs104_22 + gamma2*cs104_23
ch14_22 ~~ gamma1*cs104_23

# Operations/constraints

"
```

```{r}
# Fit the SEM model
sem_fit <- sem(sem_model, data = all_relevant_data)

# View summary of the model
summary(sem_fit, standardized = TRUE, fit.measures = TRUE)

# Visualize the SEM model
semPaths(sem_fit, what = "std", edge.label.cex = .8, layout = "tree")
```

```{r}
# Check model fit indices
fitMeasures(sem_fit, c("chisq", "df", "pvalue", "cfi", "tli", "rmsea", "srmr", "aic", "bic"))

# Modification indices - suggestions for model improvement
modificationIndices(sem_fit, sort = TRUE, minimum.value = 10)
```
